{
  config,
  pkgs,
  ...
}:

{

  environment.systemPackages = with pkgs; [
    gcc
    libtool
    ninja
    openssl_oqs
    python313
    uv
    zlib
    boost
    boost-build
    cmake
    cudaPackages.autoAddCudaCompatRunpath
    cudaPackages.backendStdenv
    cudaPackages.cuda_cccl
    #cudaPackages.cuda_compat
    #cudaPackages.cuda_crt
    #cudaPackages.cuda_ctadvisor
    cudaPackages.cuda_cudart
    cudaPackages.cuda_cudart
    #cudaPackages.cuda_culibos
    cudaPackages.cuda_cuobjdump
    cudaPackages.cuda_cupti
    cudaPackages.cuda_cupti
    cudaPackages.cuda_cuxxfilt
    cudaPackages.cuda_demo_suite
    cudaPackages.cuda_documentation
    cudaPackages.cuda_gdb
    cudaPackages.cuda_nsight
    cudaPackages.cuda_nvcc
    cudaPackages.cuda_nvdisasm
    cudaPackages.cuda_nvml_dev
    cudaPackages.cuda_nvprof
    cudaPackages.cuda_nvprune
    cudaPackages.cuda_nvrtc
    cudaPackages.cuda_nvrtc
    cudaPackages.cuda_nvtx
    cudaPackages.cuda_nvtx
    cudaPackages.cuda_nvvp
    cudaPackages.cuda_opencl
    cudaPackages.cuda_profiler_api
    cudaPackages.cuda-samples
    cudaPackages.cuda_sanitizer_api
    cudaPackages.cudatoolkit
    cudaPackages.cudatoolkit
    cudaPackages.cudnn
    cudaPackages.cudnn
    cudaPackages.cudnn-frontend
    cudaPackages.cuquantum
    cudaPackages.cutlass
    cudaPackages.fabricmanager
    cudaPackages.gdrcopy
    cudaPackages.imex
    cudaPackages.libcublas
    cudaPackages.libcublas
    cudaPackages.libcublasmp
    #cudaPackages.libcudla
    cudaPackages.libcudss
    cudaPackages.libcufft
    cudaPackages.libcufft
    cudaPackages.libcufile
    cudaPackages.libcurand
    cudaPackages.libcurand
    cudaPackages.libcusolver
    cudaPackages.libcusolver
    cudaPackages.libcusolvermp
    cudaPackages.libcusparse
    cudaPackages.libcusparse
    cudaPackages.libcusparse_lt
    cudaPackages.libcutensor
    cudaPackages.libnpp
    cudaPackages.libnpp_plus
    cudaPackages.libnvfatbin
    cudaPackages.libnvjitlink
    cudaPackages.libnvjitlink
    cudaPackages.libnvjpeg
    cudaPackages.libnvjpeg_2k
    #cudaPackages.libnvptxcompiler
    cudaPackages.libnvshmem
    cudaPackages.libnvtiff
    #cudaPackages.libnvvm
    cudaPackages.markForCudatoolkitRootHook
    cudaPackages.nccl
    cudaPackages.nccl
    cudaPackages.nccl-tests
    cudaPackages.nsight_compute
    cudaPackages.nsight_systems
    cudaPackages.nvcomp
    cudaPackages.nvidia_fs
    #cudaPackages.nvpl_blas
    #cudaPackages.nvpl_common
    #cudaPackages.nvpl_fft
    #cudaPackages.nvpl_lapack
    #cudaPackages.nvpl_rand
    #cudaPackages.nvpl_scalapack
    #cudaPackages.nvpl_sparse
    #cudaPackages.nvpl_tensor
    cudaPackages.removeStubsFromRunpathHook
    cudaPackages.saxpy
    cudaPackages.setupCudaHook
    cudaPackages.tensorrt
    cudaPackages.tensorrt-samples
  ];
}
