{
  config,
  pkgs,
  ...
}:
{
  # CUDA build dependencies (gcc, libtool, ninja, cmake, zlib, ...) live in
  # packages.nix; only the CUDA toolchain itself is listed here.
  environment.systemPackages = with pkgs; [
    cudaPackages.autoAddCudaCompatRunpath
    cudaPackages.backendStdenv
    cudaPackages.cccl
    cudaPackages.cuda_cudart
    cudaPackages.cuda_cuobjdump
    cudaPackages.cuda_cupti
    cudaPackages.cuda_cuxxfilt
    cudaPackages.cuda_demo_suite
    cudaPackages.cuda_documentation
    cudaPackages.cuda_gdb
    cudaPackages.cuda_nsight
    cudaPackages.cuda_nvcc
    cudaPackages.cuda_nvdisasm
    cudaPackages.cuda_nvml_dev
    cudaPackages.cuda_nvprof
    cudaPackages.cuda_nvprune
    cudaPackages.cuda_nvrtc
    cudaPackages.cuda_nvtx
    cudaPackages.cuda_nvvp
    cudaPackages.cuda_opencl
    cudaPackages.cuda_profiler_api
    cudaPackages.cuda-samples
    cudaPackages.cuda_sanitizer_api
    cudaPackages.cudatoolkit
    cudaPackages.cudnn
    cudaPackages.cudnn-frontend
    cudaPackages.cuquantum
    cudaPackages.cutlass
    cudaPackages.fabricmanager
    cudaPackages.gdrcopy
    cudaPackages.imex
    cudaPackages.libcublas
    cudaPackages.libcublasmp
    cudaPackages.libcudss
    cudaPackages.libcufft
    cudaPackages.libcufile
    cudaPackages.libcurand
    cudaPackages.libcusolver
    cudaPackages.libcusolvermp
    cudaPackages.libcusparse
    cudaPackages.libcusparse_lt
    cudaPackages.libcutensor
    cudaPackages.libnpp
    cudaPackages.libnpp_plus
    cudaPackages.libnvfatbin
    cudaPackages.libnvjitlink
    cudaPackages.libnvjpeg
    cudaPackages.libnvjpeg_2k
    cudaPackages.libnvshmem
    cudaPackages.libnvtiff
    cudaPackages.markForCudatoolkitRootHook
    cudaPackages.nccl
    cudaPackages.nsight_compute
    cudaPackages.nsight_systems
    cudaPackages.nvcomp
    cudaPackages.nvidia_fs
    cudaPackages.removeStubsFromRunpathHook
    cudaPackages.saxpy
    cudaPackages.setupCudaHook
  ];
}
