{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    alacritty
    amd-blis
    amdctl
    amdgpu_top
    amdvlk
    appimage-run
    aria2
    b612
    bat
    bc
    blueberry
    bluez-tools
    brasero
    btop
    buildah
    cargo
    cfssl
    chromium
    clinfo
    cliphist
    clipman
    clolcat
    colordiff
    copyq
    cri-o
    cri-tools
    criu
    crun
    ddcutil
    debootstrap
    delta
    detox
    diffuse
    difftastic
    dig
    dina-font
    dive
    doublecmd
    duf
    easyeffects
    gnomeExtensions.easyeffects-preset-selector
    envsubst
    eternal-terminal
    evtest
    fastfetch
    fastgron
    fd
    ffmpeg_6-full
    figlet
    file
    fio
    firefox
    fish
    fnm
    font-awesome
    foot
    fortune
    fzf
    gbar
    gdu
    gitFull
    git-repo
    gitAndTools.git-extras
    git-repo-updater
    glow
    gedit
    gnome.gnome-tweaks
    gnome.simple-scan
#go
    go
    gopls
    delve
    gomodifytags
    impl
    gotests
    go-tools
    golangci-lint
    golangci-lint-langserver

    gomi
    gossa
    gotty
    graphviz
    # gron
    gparted
    gping
    gvproxy
    hack-font
    htop
# hyprland
    hypr
    hyprland
    hyprpaper
    hyprland-protocols
    hyprpicker
    hyprshade
    xdg-desktop-portal-hyprland
    # xdg-desktop-portal-gtk

    imagemagick
#    input-remapper
    iotop
    iperf3
    iproute2
    jc
    jq
    jql
    # jupyter
    killall
    kitty
    koreader
    kubebuilder
    kubecolor
    kubectl
    kubectl-tree
    kubectx
    kubernetes
    kubetail
    kubevirt
    lazygit
    lego
    libnotify
    librewolf-wayland
    libreoffice-fresh
    libsForQt5.qt5ct
    libsForQt5.qtstyleplugin-kvantum
    libsForQt5.qt5.qtwayland
    libvirt
    light
    links2
    litestream
    logitech-udev-rules
    lsd
    ltunify
    luajit
    lua51Packages.telescope-nvim
    luajitPackages.telescope-nvim
    lunarvim
    mako
    maven
    mc
    meld
    microcodeAmd
    most
    mpv
    neovim
    nerdfonts
    # netbird-ui
    nettools
    nfs-utils
    nftables
    nil
    nix-top
    nixos-option
    nmap
    nodejs_20
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-cjk-serif
    noto-fonts-emoji
    noto-fonts-extra
    nushell
    nrfutil
    nvtop-amd
    openocd
    openssl
    #openvswitch
    p7zip
    pamixer
    pass
    perf-tools
    plasma-theme-switcher
    planify
    platformio
    platformio-core
    podman
    podman-compose
    podman-tui
    profont
    pstree
    pulseaudio
    pulsemixer
    pv
    pwgen

    python3Full
    python311Packages.pip

    # python311Full
    # python311Packages.setuptools
    # python311Packages.pip
    # python311Packages.pyserial
    # python312Full
    # python312Packages.setuptools
    # python312Packages.pip
    # python312Packages.pyserial
    # esphome
    # platformio
    # openocd

    # broken
    # python312Packages.pip
    # python312Packages.python
    # ml:
    # python310Packages.venvShellHook
    # python310Packages.numpy
    # python310Packages.requests
    # python310Packages.pre-commit-hooks
    # python310Packages.pandas
    # python310Packages.matplotlib
    # python310Packages.seaborn
    # python310Packages.kaggle
    # python310Packages.tqdm
    # python310Packages.wandb
    # python310Packages.scikit-learn
    # python310Packages.xgboost
    # python310Packages.lightgbm
    # python310Packages.catboost
    # python310Packages.tensorboard
    # python310Packages.torchWithRocm
    # python310Packages.torchvision
    # python310Packages.torchaudio
    # python310Packages.jupyter
    # python310Packages.jupyter-core    
    # python310Packages.notebook
    # python310Packages.ipykernel
    # streamlit
    # taglib
    # openssl
    # libxml2
    # libxslt
    # libzip
    # zlib

    pywal
    qemu
    qmk-udev-rules
    qrencode
    qt6.qtwayland
    ranger
    rename
    rgp
    ripgrep
    # rocm
    # rocmPackages.rocmlir
    # rocmPackages.rocminfo
    # rocmPackages.rocm-core
    # rocmPackages.rocm-thunk
    # rocmPackages.rocm-comgr
    # rocmPackages.rocm-cmake
    # rocmPackages.rocmlir-rock
    # rocmPackages.rocm-runtime
    # rocmPackages.rocm-docs-core
    # rocmPackages.rocm-device-libs
    # rocmPackages.llvm.rocmClangStdenv
    # rocmPackages.llvm.pstl
    # rocmPackages.llvm.polly
    # rocmPackages.llvm.openmp
    # rocmPackages.llvm.mlir
    # rocmPackages.llvm.llvm
    # rocmPackages.llvm.lldb
    # rocmPackages.llvm.lld
    # rocmPackages.llvm.libunwind
    # rocmPackages.llvm.libcxxabi
    # rocmPackages.llvm.libcxx
    # rocmPackages.llvm.libc
    # rocmPackages.llvm.compiler-rt
    # rocmPackages.llvm.clang-tools-extra
    # rocmPackages.llvm.clang
    # rocmPackages.llvm.bintools
    # rocmPackages.rocsparse
    # rocmPackages.rocsolver
    # rocmPackages.rocprim
    # rocmPackages.rocalution
    # rocmPackages.rccl
    # rocmPackages.miopen
    # rocmPackages.miopengemm
    # rocmPackages.hipsparse
    # rocmPackages.hipsolver
    # rocmPackages.hipblas
    # rocmPackages.rocgdb
    # end rocm
    rofi
    runc
    rustc
    rustup
    skopeo
    socat
    spacevim
    sqlite
    sqlitebrowser
    strace
    sudo-font
    sway
    swaylock-effects
    taskwarrior
    teensy-udev-rules
    telescope
    tmux
    tockloader
    tig
    tpmmanager
    tpm2-tools
    transmission
    transmission-gtk
    tree
    tree-sitter
    tree-sitter-grammars.tree-sitter-bash
    tree-sitter-grammars.tree-sitter-c
    tree-sitter-grammars.tree-sitter-cpp
    tree-sitter-grammars.tree-sitter-dot
    tree-sitter-grammars.tree-sitter-fish
    tree-sitter-grammars.tree-sitter-go
    tree-sitter-grammars.tree-sitter-html
    tree-sitter-grammars.tree-sitter-http
    tree-sitter-grammars.tree-sitter-java
    tree-sitter-grammars.tree-sitter-json
    tree-sitter-grammars.tree-sitter-llvm
    tree-sitter-grammars.tree-sitter-lua
    tree-sitter-grammars.tree-sitter-make
    tree-sitter-grammars.tree-sitter-nix
    tree-sitter-grammars.tree-sitter-rust
    tree-sitter-grammars.tree-sitter-sql
    tree-sitter-grammars.tree-sitter-toml
    tree-sitter-grammars.tree-sitter-vim
    tree-sitter-grammars.tree-sitter-yaml
    tree-sitter-grammars.tree-sitter-zig
    treesheets
    udiskie
    unzip
    unpaper
    unrar
    usbtop
    usbutils
    ustreamer
    utterly-nord-plasma
    via

    #vimPlugins
    vimPlugins.BetterLua-vim
    vimPlugins.BufOnly
    vimPlugins.BufOnly-vim
    vimPlugins.CSApprox
    vimPlugins.ChatGPT-nvim
    vimPlugins.CheckAttach
    vimPlugins.Colour-Sampler-Pack
    vimPlugins.Colour_Sampler_Pack
    vimPlugins.Coqtail
    vimPlugins.Cosco
    vimPlugins.DoxygenToolkit-vim
    vimPlugins.FTerm-nvim
    vimPlugins.FixCursorHold-nvim
    vimPlugins.Gist
    vimPlugins.Gundo
    vimPlugins.Hoogle
    vimPlugins.Improved-AnsiEsc
    vimPlugins.Ionide-vim
    vimPlugins.Jenkinsfile-vim-syntax
    vimPlugins.LanguageClient-neovim
    vimPlugins.LanguageTool-nvim
    vimPlugins.LazyVim
    vimPlugins.LeaderF
    vimPlugins.MatchTagAlways
    vimPlugins.Navigator-nvim
    vimPlugins.NeoSolarized
    vimPlugins.NrrwRgn
    vimPlugins.PreserveNoEOL
    vimPlugins.QFEnter
    vimPlugins.Recover-vim
    vimPlugins.Rename
    vimPlugins.ReplaceWithRegister
    vimPlugins.SchemaStore-nvim
    vimPlugins.Shade-nvim
    vimPlugins.ShowMultiBase
    vimPlugins.SimpylFold
    vimPlugins.SmartCase
    vimPlugins.Solarized
    vimPlugins.SpaceCamp
    vimPlugins.SpaceVim
    vimPlugins.Spacegray-vim
    vimPlugins.SudoEdit-vim
    vimPlugins.Supertab
    vimPlugins.Syntastic
    vimPlugins.SyntaxRange
    vimPlugins.Tabular
    vimPlugins.Tagbar
    vimPlugins.The_NERD_Commenter
    vimPlugins.The_NERD_tree
    vimPlugins.UltiSnips
    vimPlugins.VimCompletesMe
    vimPlugins.VimOrganizer
    vimPlugins.Vundle-vim
    vimPlugins.WebAPI
    vimPlugins.YUNOcommit-vim
    vimPlugins.YankRing-vim
    vimPlugins.Yankring
    vimPlugins.YouCompleteMe
    vimPlugins.a-vim
    vimPlugins.ack-vim
    vimPlugins.acp
    vimPlugins.actions-preview-nvim
    vimPlugins.adwaita-nvim
    vimPlugins.aerial-nvim
    vimPlugins.ag-nvim
    vimPlugins.agda-vim
    vimPlugins.ai-vim
    vimPlugins.airline
    vimPlugins.alchemist-vim
    vimPlugins.ale
    vimPlugins.align
    vimPlugins.alpha-nvim
    vimPlugins.alternative
    vimPlugins.aniseed
    vimPlugins.ansible-vim
    vimPlugins.antonys-macro-repeater
    vimPlugins.arcanist-vim
    vimPlugins.argtextobj-vim
    vimPlugins.async-vim
    vimPlugins.asyncomplete-buffer-vim
    vimPlugins.asyncomplete-file-vim
    vimPlugins.asyncomplete-lsp-vim
    vimPlugins.asyncomplete-omni-vim
    vimPlugins.asyncomplete-tags-vim
    vimPlugins.asyncomplete-ultisnips-vim
    vimPlugins.asyncomplete-vim
    vimPlugins.asyncrun-vim
    vimPlugins.asynctasks-vim
    vimPlugins.ats-vim
    vimPlugins.aurora
    vimPlugins.auto-git-diff
    vimPlugins.auto-hlsearch-nvim
    vimPlugins.auto-pairs
    vimPlugins.auto-save-nvim
    vimPlugins.auto-session
    vimPlugins.autoclose-nvim
    vimPlugins.autoload_cscope-vim
    vimPlugins.autosave-nvim
    vimPlugins.awesome-vim-colorschemes
    vimPlugins.ayu-vim
    vimPlugins.b64-nvim
    vimPlugins.barbar-nvim
    vimPlugins.barbecue-nvim
    vimPlugins.base16-vim
    vimPlugins.base46
    vimPlugins.bat-vim
    vimPlugins.bats
    vimPlugins.bats-vim
    vimPlugins.bclose-vim
    vimPlugins.better-escape-nvim
    vimPlugins.bigfile-nvim
    vimPlugins.bitbake-vim
    vimPlugins.blamer-nvim
    vimPlugins.block-nvim
    vimPlugins.blueballs-neovim
    vimPlugins.boole-nvim
    vimPlugins.bracey-vim
    vimPlugins.brainfuck-vim
    vimPlugins.bufdelete-nvim
    vimPlugins.bufexplorer
    vimPlugins.bufferize-vim
    vimPlugins.bufferline-nvim
    vimPlugins.bufjump-nvim
    vimPlugins.bullets-vim
    vimPlugins.calendar
    vimPlugins.calendar-vim
    vimPlugins.camelcasemotion
    vimPlugins.catppuccin-nvim
    vimPlugins.catppuccin-vim
    vimPlugins.caw
    vimPlugins.caw-vim
    vimPlugins.ccc-nvim
    vimPlugins.chad
    vimPlugins.chadtree
    vimPlugins.changeColorScheme-vim
    vimPlugins.cheatsheet-nvim
    vimPlugins.ci_dark
    vimPlugins.circles-nvim
    vimPlugins.clang_complete
    vimPlugins.clangd_extensions-nvim
    vimPlugins.clever-f-vim
    vimPlugins.clighter8
    vimPlugins.clipboard-image-nvim
    vimPlugins.close-buffers-vim
    vimPlugins.cmd-parser-nvim
    vimPlugins.cmp-async-path
    vimPlugins.cmp-beancount
    vimPlugins.cmp-buffer
    vimPlugins.cmp-calc
    vimPlugins.cmp-clippy
    vimPlugins.cmp-cmdline
    vimPlugins.cmp-cmdline-history
    vimPlugins.cmp-conjure
    vimPlugins.cmp-conventionalcommits
    vimPlugins.cmp-copilot
    vimPlugins.cmp-dap
    vimPlugins.cmp-dictionary
    vimPlugins.cmp-digraphs
    vimPlugins.cmp-emoji
    vimPlugins.cmp-fish
    vimPlugins.cmp-fuzzy-buffer
    vimPlugins.cmp-fuzzy-path
    vimPlugins.cmp-git
    vimPlugins.cmp-greek
    vimPlugins.cmp-latex-symbols
    vimPlugins.cmp-look
    vimPlugins.cmp-neosnippet
    vimPlugins.cmp-npm
    vimPlugins.cmp-nvim-lsp
    vimPlugins.cmp-nvim-lsp-document-symbol
    vimPlugins.cmp-nvim-lsp-signature-help
    vimPlugins.cmp-nvim-lua
    vimPlugins.cmp-nvim-tags
    vimPlugins.cmp-nvim-ultisnips
    vimPlugins.cmp-omni
    vimPlugins.cmp-pandoc-nvim
    vimPlugins.cmp-pandoc-references
    vimPlugins.cmp-path
    vimPlugins.cmp-rg
    vimPlugins.cmp-snippy
    vimPlugins.cmp-spell
    vimPlugins.cmp-tabby
    vimPlugins.cmp-tabnine
    vimPlugins.cmp-tmux
    vimPlugins.cmp-treesitter
    vimPlugins.cmp-under-comparator
    vimPlugins.cmp-vim-lsp
    vimPlugins.cmp-vimwiki-tags
    vimPlugins.cmp-vsnip
    vimPlugins.cmp-zsh
    vimPlugins.cmp_luasnip
    vimPlugins.coc-clangd
    vimPlugins.coc-clap
    vimPlugins.coc-cmake
    vimPlugins.coc-css
    vimPlugins.coc-denite
    vimPlugins.coc-diagnostic
    vimPlugins.coc-docker
    vimPlugins.coc-emmet
    vimPlugins.coc-eslint
    vimPlugins.coc-explorer
    vimPlugins.coc-flutter
    vimPlugins.coc-fzf
    vimPlugins.coc-git
    vimPlugins.coc-go
    vimPlugins.coc-haxe
    vimPlugins.coc-highlight
    vimPlugins.coc-html
    vimPlugins.coc-java
    vimPlugins.coc-jest
    vimPlugins.coc-json
    vimPlugins.coc-lists
    vimPlugins.coc-ltex
    vimPlugins.coc-lua
    vimPlugins.coc-markdownlint
    vimPlugins.coc-metals
    vimPlugins.coc-neco
    vimPlugins.coc-nginx
    vimPlugins.coc-nvim
    vimPlugins.coc-pairs
    vimPlugins.coc-prettier
    vimPlugins.coc-pyright
    vimPlugins.coc-python
    vimPlugins.coc-r-lsp
    vimPlugins.coc-rls
    vimPlugins.coc-rust-analyzer
    vimPlugins.coc-sh
    vimPlugins.coc-smartf
    vimPlugins.coc-snippets
    vimPlugins.coc-solargraph
    vimPlugins.coc-spell-checker
    vimPlugins.coc-sqlfluff
    vimPlugins.coc-stylelint
    vimPlugins.coc-sumneko-lua
    vimPlugins.coc-svelte
    vimPlugins.coc-tabnine
    vimPlugins.coc-tailwindcss
    vimPlugins.coc-texlab
    vimPlugins.coc-toml
    vimPlugins.coc-tslint
    vimPlugins.coc-tslint-plugin
    vimPlugins.coc-tsserver
    vimPlugins.coc-ultisnips
    vimPlugins.coc-vetur
    vimPlugins.coc-vimlsp
    vimPlugins.coc-vimtex
    vimPlugins.coc-wxml
    vimPlugins.coc-yaml
    vimPlugins.coc-yank
    vimPlugins.coconut-vim
    vimPlugins.codeium-nvim
    vimPlugins.codeium-vim
    vimPlugins.codewindow-nvim
    vimPlugins.codi-vim
    vimPlugins.coffee-script
    vimPlugins.coffeeScript
    vimPlugins.colorbuddy-nvim
    vimPlugins.colorizer
    vimPlugins.colors-solarized
    vimPlugins.colorsamplerpack
    vimPlugins.com-cloudedmountain-ide-neovim
    vimPlugins.command-t
    vimPlugins.command_T
    vimPlugins.comment-nvim
    vimPlugins.commentary
    vimPlugins.committia
    vimPlugins.committia-vim
    vimPlugins.compe-conjure
    vimPlugins.compe-latex-symbols
    vimPlugins.compe-tabnine
    vimPlugins.compe-zsh
    vimPlugins.compiler-explorer-nvim
    vimPlugins.completion-buffers
    vimPlugins.completion-nvim
    vimPlugins.completion-tabnine
    vimPlugins.completion-treesitter
    vimPlugins.concealedyank
    vimPlugins.concealedyank-vim
    vimPlugins.conflict-marker-vim
    vimPlugins.conform-nvim
    vimPlugins.conjure
    vimPlugins.context-filetype
    vimPlugins.context-vim
    vimPlugins.context_filetype-vim
    vimPlugins.copilot-cmp
    vimPlugins.copilot-lua
    vimPlugins.copilot-vim
    vimPlugins.coq-artifacts
    vimPlugins.coq-thirdparty
    vimPlugins.coq-vim
    vimPlugins.coq_nvim
    vimPlugins.cosco-vim
    vimPlugins.cpsm
    vimPlugins.crates-nvim
    vimPlugins.csapprox
    vimPlugins.csharpls-extended-lsp-nvim
    vimPlugins.css_color_5056
    vimPlugins.csv
    vimPlugins.csv-vim
    vimPlugins.ctrlp
    vimPlugins.ctrlp-cmatcher
    vimPlugins.ctrlp-py-matcher
    vimPlugins.ctrlp-vim
    vimPlugins.ctrlp-z
    vimPlugins.cute-python
    vimPlugins.dart-vim-plugin
    vimPlugins.dash-vim
    vimPlugins.dashboard-nvim
    vimPlugins.debugprint-nvim
    vimPlugins.defx-git
    vimPlugins.defx-icons
    vimPlugins.defx-nvim
    vimPlugins.delimitMate
    vimPlugins.denite
    vimPlugins.denite-extra
    vimPlugins.denite-git
    vimPlugins.denite-nvim
    vimPlugins.denops-vim
    vimPlugins.deol-nvim
    vimPlugins.deoplete-clang
    vimPlugins.deoplete-dictionary
    vimPlugins.deoplete-fish
    vimPlugins.deoplete-github
    vimPlugins.deoplete-go
    vimPlugins.deoplete-greek
    vimPlugins.deoplete-jedi
    vimPlugins.deoplete-julia
    vimPlugins.deoplete-khard
    vimPlugins.deoplete-lsp
    vimPlugins.deoplete-notmuch
    vimPlugins.deoplete-nvim
    vimPlugins.deoplete-phpactor
    vimPlugins.deoplete-rust
    vimPlugins.deoplete-tabnine
    vimPlugins.deoplete-ternjs
    vimPlugins.deoplete-vim-lsp
    vimPlugins.deoplete-zsh
    vimPlugins.devdocs-vim
    vimPlugins.dhall-vim
    vimPlugins.diaglist-nvim
    vimPlugins.diagnostic-nvim
    vimPlugins.dial-nvim
    vimPlugins.diffview-nvim
    vimPlugins.dirbuf-nvim
    vimPlugins.direnv-vim
    vimPlugins.distant-nvim
    vimPlugins.doki-theme-vim
    vimPlugins.dracula-nvim
    vimPlugins.dracula-vim
    vimPlugins.dressing-nvim
    vimPlugins.dropbar-nvim
    vimPlugins.easy-align
    vimPlugins.easygit
    vimPlugins.easymotion
    vimPlugins.echodoc
    vimPlugins.echodoc-vim
    vimPlugins.edge
    vimPlugins.edgedb-vim
    vimPlugins.edgy-nvim
    vimPlugins.editorconfig-nvim
    vimPlugins.editorconfig-vim
    vimPlugins.efmls-configs-nvim
    vimPlugins.eighties
    vimPlugins.elixir-tools-nvim
    vimPlugins.elm-vim
    vimPlugins.elvish-vim
    vimPlugins.embark-vim
    vimPlugins.emmet-vim
    vimPlugins.emodeline
    vimPlugins.errormarker-vim
    vimPlugins.everforest
    vimPlugins.executor-nvim
    vimPlugins.extradite
    vimPlugins.eyeliner-nvim
    vimPlugins.falcon
    vimPlugins.far-vim
    vimPlugins.fastfold
    vimPlugins.fcitx-vim
    vimPlugins.feline-nvim
    vimPlugins.fennel-vim
    vimPlugins.fern-vim
    vimPlugins.ferret
    vimPlugins.fidget-nvim
    vimPlugins.file-line
    vimPlugins.fileline-nvim
    vimPlugins.firenvim
    vimPlugins.flake8-vim
    vimPlugins.flash-nvim
    vimPlugins.flatten-nvim
    vimPlugins.flit-nvim
    vimPlugins.float-preview-nvim
    vimPlugins.floating-input-nvim
    vimPlugins.floating-nvim
    vimPlugins.floobits-neovim
    vimPlugins.flutter-tools-nvim
    vimPlugins.fold-preview-nvim
    vimPlugins.formatter-nvim
    vimPlugins.forms
    vimPlugins.friendly-snippets
    vimPlugins.fruzzy
    vimPlugins.fugitive
    vimPlugins.fugitive-gitlab-vim
    vimPlugins.futhark-vim
    vimPlugins.fuzzy-nvim
    vimPlugins.fwatch-nvim
    vimPlugins.fzf-checkout-vim
    vimPlugins.fzf-hoogle-vim
    vimPlugins.fzf-lsp-nvim
    vimPlugins.fzf-lua
    vimPlugins.fzf-vim
    vimPlugins.fzfWrapper
    vimPlugins.galaxyline-nvim
    vimPlugins.gen_tags-vim
    vimPlugins.gentoo-syntax
    vimPlugins.ghc-mod-vim
    vimPlugins.ghcid
    vimPlugins.ghcmod
    vimPlugins.ghcmod-vim
    vimPlugins.gina-vim
    vimPlugins.git-blame-nvim
    vimPlugins.git-conflict-nvim
    vimPlugins.git-messenger-vim
    vimPlugins.git-worktree-nvim
    vimPlugins.gitgutter
    vimPlugins.gitignore-vim
    vimPlugins.gitlinker-nvim
    vimPlugins.gitsigns-nvim
    vimPlugins.gitv
    vimPlugins.glance-nvim
    vimPlugins.gleam-vim
    vimPlugins.glow-nvim
    vimPlugins.go-nvim
    vimPlugins.godbolt-nvim
    vimPlugins.golden-ratio
    vimPlugins.gotests-vim
    vimPlugins.goto-preview
    vimPlugins.goyo
    vimPlugins.goyo-vim
    vimPlugins.grammar-guard-nvim
    vimPlugins.graphviz-vim
    vimPlugins.gruvbox
    vimPlugins.gruvbox-community
    vimPlugins.gruvbox-flat-nvim
    vimPlugins.gruvbox-material
    vimPlugins.gruvbox-nvim
    vimPlugins.guard-collection
    vimPlugins.guard-nvim
    vimPlugins.guess-indent-nvim
    vimPlugins.gundo
    vimPlugins.gundo-vim
    vimPlugins.gv-vim
    vimPlugins.hardtime-nvim
    vimPlugins.hare-vim
    vimPlugins.harpoon
    vimPlugins.harpoon2
    vimPlugins.haskell-scope-highlighting-nvim
    vimPlugins.haskell-tools-nvim
    vimPlugins.haskell-vim
    vimPlugins.haskell-with-unicode-vim
    vimPlugins.haskellConceal
    vimPlugins.haskellConcealPlus
    vimPlugins.haskellconceal
    vimPlugins.hasksyn
    vimPlugins.headlines-nvim
    vimPlugins.heirline-nvim
    vimPlugins.hex-nvim
    vimPlugins.hiPairs
    vimPlugins.hier
    vimPlugins.highlight-undo-nvim
    vimPlugins.himalaya-vim
    vimPlugins.hlint-refactor
    vimPlugins.hlint-refactor-vim
    vimPlugins.hmts-nvim
    vimPlugins.hologram-nvim
    vimPlugins.hoogle
    vimPlugins.hoon-vim
    vimPlugins.hop-nvim
    vimPlugins.hotpot-nvim
    vimPlugins.hover-nvim
    vimPlugins.html5-vim
    vimPlugins.hurl
    vimPlugins.hydra-nvim
    vimPlugins.i3config-vim
    vimPlugins.iceberg-vim
    vimPlugins.idris-vim
    vimPlugins.idris2-vim
    vimPlugins.image-nvim
    vimPlugins.impatient-nvim
    vimPlugins.inc-rename-nvim
    vimPlugins.increment-activator
    vimPlugins.incsearch-easymotion-vim
    vimPlugins.incsearch-vim
    vimPlugins.indent-blankline-nvim
    vimPlugins.indent-blankline-nvim-lua
    vimPlugins.indent-o-matic
    vimPlugins.indentLine
    vimPlugins.inkpot
    vimPlugins.instant-nvim
    vimPlugins.intellitab-nvim
    vimPlugins.intero-neovim
    vimPlugins.investigate-vim
    vimPlugins.iosvkem
    vimPlugins.ipython
    vimPlugins.ir_black
    vimPlugins.iron-nvim
    vimPlugins.is-vim
    vimPlugins.jdaddy-vim
    vimPlugins.jedi-vim
    vimPlugins.jellybeans-nvim
    vimPlugins.jellybeans-vim
    vimPlugins.jinja-vim
    vimPlugins.jq-vim
    vimPlugins.jsonc-vim
    vimPlugins.julia-vim
    vimPlugins.kanagawa-nvim
    vimPlugins.keymap-layer-nvim
    vimPlugins.kmonad-vim
    vimPlugins.knap
    vimPlugins.kommentary
    vimPlugins.kotlin-vim
    vimPlugins.lalrpop-vim
    vimPlugins.last256
    vimPlugins.latex-box
    vimPlugins.latex-live-preview
    vimPlugins.lazy-lsp-nvim
    vimPlugins.lazy-nvim
    vimPlugins.lazygit-nvim
    vimPlugins.lean-nvim
    vimPlugins.lean-vim
    vimPlugins.leap-ast-nvim
    vimPlugins.leap-nvim
    vimPlugins.legendary-nvim
    vimPlugins.lens-vim
    vimPlugins.lessspace-vim
    vimPlugins.lexima-vim
    vimPlugins.lf-vim
    vimPlugins.lh-brackets
    vimPlugins.lh-vim-lib
    vimPlugins.lightline-ale
    vimPlugins.lightline-bufferline
    vimPlugins.lightline-gruvbox-vim
    vimPlugins.lightline-lsp
    vimPlugins.lightline-vim
    vimPlugins.lightspeed-nvim
    vimPlugins.limelight-vim
    vimPlugins.lingua-franca-vim
    vimPlugins.lir-nvim
    vimPlugins.lispdocs-nvim
    vimPlugins.litee-calltree-nvim
    vimPlugins.litee-filetree-nvim
    vimPlugins.litee-nvim
    vimPlugins.litee-symboltree-nvim
    vimPlugins.live-command-nvim
    vimPlugins.lsp-colors-nvim
    vimPlugins.lsp-format-nvim
    vimPlugins.lsp-inlayhints-nvim
    vimPlugins.lsp-overloads-nvim
    vimPlugins.lsp-rooter-nvim
    vimPlugins.lsp-status-nvim
    vimPlugins.lsp-zero-nvim
    vimPlugins.lsp_extensions-nvim
    vimPlugins.lsp_lines-nvim
    vimPlugins.lsp_signature-nvim
    vimPlugins.lspcontainers-nvim
    vimPlugins.lspkind-nvim
    vimPlugins.lspsaga-nvim
    vimPlugins.ltex_extra-nvim
    vimPlugins.lualine-lsp-progress
    vimPlugins.lualine-nvim
    vimPlugins.luasnip
    vimPlugins.luatab-nvim
    vimPlugins.lush-nvim
    vimPlugins.lushtags
    vimPlugins.magma-nvim-goose
    vimPlugins.maktaba
    vimPlugins.mark-radar-nvim
    vimPlugins.markdown-preview-nvim
    vimPlugins.markid
    vimPlugins.marks-nvim
    vimPlugins.mason-lspconfig-nvim
    vimPlugins.mason-nvim
    vimPlugins.mason-tool-installer-nvim
    vimPlugins.matchit-zip
    vimPlugins.material-nvim
    vimPlugins.material-vim
    vimPlugins.mattn-calendar-vim
    vimPlugins.mayansmoke
    vimPlugins.mediawiki-vim
    vimPlugins.melange-nvim
    vimPlugins.meson
    vimPlugins.mind-nvim
    vimPlugins.mini-nvim
    vimPlugins.minimap-vim
    vimPlugins.minsnip-nvim
    vimPlugins.mkdir-nvim
    vimPlugins.mkdnflow-nvim
    vimPlugins.mkdx
    vimPlugins.modicator-nvim
    vimPlugins.modus-themes-nvim
    vimPlugins.molokai
    vimPlugins.molten-nvim
    vimPlugins.monokai-pro-nvim
    vimPlugins.moonscript-vim
    vimPlugins.mru
    vimPlugins.multicursors-nvim
    vimPlugins.multiple-cursors
    vimPlugins.nabla-nvim
    vimPlugins.ncm2
    vimPlugins.ncm2-bufword
    vimPlugins.ncm2-cssomni
    vimPlugins.ncm2-dictionary
    vimPlugins.ncm2-github
    vimPlugins.ncm2-html-subscope
    vimPlugins.ncm2-jedi
    vimPlugins.ncm2-markdown-subscope
    vimPlugins.ncm2-neoinclude
    vimPlugins.ncm2-neosnippet
    vimPlugins.ncm2-path
    vimPlugins.ncm2-syntax
    vimPlugins.ncm2-tagprefix
    vimPlugins.ncm2-tmux
    vimPlugins.ncm2-ultisnips
    vimPlugins.ncm2-vim
    vimPlugins.neco-ghc
    vimPlugins.neco-look
    vimPlugins.neco-syntax
    vimPlugins.neco-vim
    vimPlugins.necoGhc
    vimPlugins.neo-tree-nvim
    vimPlugins.neocomplete
    vimPlugins.neocomplete-vim
    vimPlugins.neoconf-nvim
    vimPlugins.neodark-vim
    vimPlugins.neodev-nvim
    vimPlugins.neoformat
    vimPlugins.neogen
    vimPlugins.neogit
    vimPlugins.neoinclude
    vimPlugins.neoinclude-vim
    vimPlugins.neomake
    vimPlugins.neomru
    vimPlugins.neomru-vim
    vimPlugins.neon
    vimPlugins.neorepl-nvim
    vimPlugins.neorg
    vimPlugins.neorg-telescope
    vimPlugins.neoscroll-nvim
    vimPlugins.neosnippet
    vimPlugins.neosnippet-snippets
    vimPlugins.neosnippet-vim
    vimPlugins.neoterm
    vimPlugins.neotest
    vimPlugins.neotest-dart
    vimPlugins.neotest-deno
    vimPlugins.neotest-dotnet
    vimPlugins.neotest-elixir
    vimPlugins.neotest-go
    vimPlugins.neotest-haskell
    vimPlugins.neotest-jest
    vimPlugins.neotest-pest
    vimPlugins.neotest-phpunit
    vimPlugins.neotest-plenary
    vimPlugins.neotest-python
    vimPlugins.neotest-rspec
    vimPlugins.neotest-rust
    vimPlugins.neotest-scala
    vimPlugins.neotest-testthat
    vimPlugins.neotest-vitest
    vimPlugins.neovim-ayu
    vimPlugins.neovim-fuzzy
    vimPlugins.neovim-sensible
    vimPlugins.neoyank-vim
    vimPlugins.nerdcommenter
    vimPlugins.nerdtree
    vimPlugins.nerdtree-git-plugin
    vimPlugins.netman-nvim
    vimPlugins.neuron-nvim
    vimPlugins.neuron-vim
    vimPlugins.nfnl
    vimPlugins.nginx-vim
    vimPlugins.nightfly
    vimPlugins.nightfox-nvim
    vimPlugins.nim-vim
    vimPlugins.nix-develop-nvim
    vimPlugins.nlsp-settings-nvim
    vimPlugins.nnn-vim
    vimPlugins.no-neck-pain-nvim
    vimPlugins.noice-nvim
    vimPlugins.none-ls-nvim
    vimPlugins.nord-nvim
    vimPlugins.nord-vim
    vimPlugins.nordic-nvim
    vimPlugins.notifier-nvim
    vimPlugins.nterm-nvim
    vimPlugins.nui-nvim
    vimPlugins.null-ls-nvim
    vimPlugins.numb-nvim
    vimPlugins.nvchad
    vimPlugins.nvchad-ui
    vimPlugins.nvcode-color-schemes-vim
    vimPlugins.nvim-FeMaco-lua
    vimPlugins.nvim-ale-diagnostic
    vimPlugins.nvim-autopairs
    vimPlugins.nvim-base16
    vimPlugins.nvim-biscuits
    vimPlugins.nvim-bqf
    vimPlugins.nvim-bufdel
    vimPlugins.nvim-cm-racer
    vimPlugins.nvim-cmp
    vimPlugins.nvim-code-action-menu
    vimPlugins.nvim-cokeline
    vimPlugins.nvim-colorizer-lua
    vimPlugins.nvim-comment
    vimPlugins.nvim-compe
    vimPlugins.nvim-completion-manager
    vimPlugins.nvim-config-local
    vimPlugins.nvim-coverage
    vimPlugins.nvim-cursorline
    vimPlugins.nvim-dap
    vimPlugins.nvim-dap-go
    vimPlugins.nvim-dap-python
    vimPlugins.nvim-dap-ui
    vimPlugins.nvim-dap-virtual-text
    vimPlugins.nvim-docs-view
    vimPlugins.nvim-expand-expr
    vimPlugins.nvim-fzf
    vimPlugins.nvim-fzf-commands
    vimPlugins.nvim-gdb
    vimPlugins.nvim-gps
    vimPlugins.nvim-highlight-colors
    vimPlugins.nvim-highlite
    vimPlugins.nvim-hlslens
    vimPlugins.nvim-hs-vim
    vimPlugins.nvim-jdtls
    vimPlugins.nvim-jqx
    vimPlugins.nvim-julia-autotest
    vimPlugins.nvim-lastplace
    vimPlugins.nvim-lightbulb
    vimPlugins.nvim-lightline-lsp
    vimPlugins.nvim-lilypond-suite
    vimPlugins.nvim-lint
    vimPlugins.nvim-lsp-notify
    vimPlugins.nvim-lsp-ts-utils
    vimPlugins.nvim-lspconfig
    vimPlugins.nvim-lsputils
    vimPlugins.nvim-lua-gf
    vimPlugins.nvim-luadev
    vimPlugins.nvim-luapad
    vimPlugins.nvim-metals
    vimPlugins.nvim-moonwalk
    vimPlugins.nvim-navbuddy
    vimPlugins.nvim-navic
    vimPlugins.nvim-neoclip-lua
    vimPlugins.nvim-nonicons
    vimPlugins.nvim-notify
    vimPlugins.nvim-nu
    vimPlugins.nvim-osc52
    vimPlugins.nvim-peekup
    vimPlugins.nvim-pqf
    vimPlugins.nvim-remote-containers
    vimPlugins.nvim-rename-state
    vimPlugins.nvim-scrollbar
    vimPlugins.nvim-scrollview
    vimPlugins.nvim-search-and-replace
    vimPlugins.nvim-snippy
    vimPlugins.nvim-solarized-lua
    vimPlugins.nvim-spectre
    vimPlugins.nvim-spider
    vimPlugins.nvim-surround
    vimPlugins.nvim-teal-maker
    vimPlugins.nvim-terminal-lua
    vimPlugins.nvim-test
    vimPlugins.nvim-tree-lua
    vimPlugins.nvim-treesitter
    vimPlugins.nvim-treesitter-context
    vimPlugins.nvim-treesitter-endwise
    vimPlugins.nvim-treesitter-parsers.ada
    vimPlugins.nvim-treesitter-parsers.agda
    vimPlugins.nvim-treesitter-parsers.angular
    vimPlugins.nvim-treesitter-parsers.apex
    vimPlugins.nvim-treesitter-parsers.arduino
    vimPlugins.nvim-treesitter-parsers.astro
    vimPlugins.nvim-treesitter-parsers.authzed
    vimPlugins.nvim-treesitter-parsers.awk
    vimPlugins.nvim-treesitter-parsers.bash
    vimPlugins.nvim-treesitter-parsers.bass
    vimPlugins.nvim-treesitter-parsers.beancount
    vimPlugins.nvim-treesitter-parsers.bibtex
    vimPlugins.nvim-treesitter-parsers.bicep
    vimPlugins.nvim-treesitter-parsers.bitbake
    vimPlugins.nvim-treesitter-parsers.blueprint
    vimPlugins.nvim-treesitter-parsers.c
    vimPlugins.nvim-treesitter-parsers.c_sharp
    vimPlugins.nvim-treesitter-parsers.cairo
    vimPlugins.nvim-treesitter-parsers.capnp
    vimPlugins.nvim-treesitter-parsers.chatito
    vimPlugins.nvim-treesitter-parsers.clojure
    vimPlugins.nvim-treesitter-parsers.cmake
    vimPlugins.nvim-treesitter-parsers.comment
    vimPlugins.nvim-treesitter-parsers.commonlisp
    vimPlugins.nvim-treesitter-parsers.cooklang
    vimPlugins.nvim-treesitter-parsers.corn
    vimPlugins.nvim-treesitter-parsers.cpon
    vimPlugins.nvim-treesitter-parsers.cpp
    vimPlugins.nvim-treesitter-parsers.css
    vimPlugins.nvim-treesitter-parsers.csv
    vimPlugins.nvim-treesitter-parsers.cuda
    vimPlugins.nvim-treesitter-parsers.cue
    vimPlugins.nvim-treesitter-parsers.d
    vimPlugins.nvim-treesitter-parsers.dart
    vimPlugins.nvim-treesitter-parsers.devicetree
    vimPlugins.nvim-treesitter-parsers.dhall
    vimPlugins.nvim-treesitter-parsers.diff
    vimPlugins.nvim-treesitter-parsers.disassembly
    vimPlugins.nvim-treesitter-parsers.dockerfile
    vimPlugins.nvim-treesitter-parsers.dot
    vimPlugins.nvim-treesitter-parsers.doxygen
    vimPlugins.nvim-treesitter-parsers.dtd
    vimPlugins.nvim-treesitter-parsers.ebnf
    vimPlugins.nvim-treesitter-parsers.eds
    vimPlugins.nvim-treesitter-parsers.eex
    vimPlugins.nvim-treesitter-parsers.elixir
    vimPlugins.nvim-treesitter-parsers.elm
    vimPlugins.nvim-treesitter-parsers.elsa
    vimPlugins.nvim-treesitter-parsers.elvish
    vimPlugins.nvim-treesitter-parsers.embedded_template
    vimPlugins.nvim-treesitter-parsers.erlang
    vimPlugins.nvim-treesitter-parsers.facility
    vimPlugins.nvim-treesitter-parsers.fennel
    vimPlugins.nvim-treesitter-parsers.firrtl
    vimPlugins.nvim-treesitter-parsers.fish
    vimPlugins.nvim-treesitter-parsers.foam
    vimPlugins.nvim-treesitter-parsers.forth
    vimPlugins.nvim-treesitter-parsers.fortran
    vimPlugins.nvim-treesitter-parsers.fsh
    vimPlugins.nvim-treesitter-parsers.func
    vimPlugins.nvim-treesitter-parsers.fusion
    vimPlugins.nvim-treesitter-parsers.gdscript
    vimPlugins.nvim-treesitter-parsers.git_config
    vimPlugins.nvim-treesitter-parsers.git_rebase
    vimPlugins.nvim-treesitter-parsers.gitattributes
    vimPlugins.nvim-treesitter-parsers.gitcommit
    vimPlugins.nvim-treesitter-parsers.gitignore
    vimPlugins.nvim-treesitter-parsers.gleam
    vimPlugins.nvim-treesitter-parsers.glimmer
    vimPlugins.nvim-treesitter-parsers.glsl
    vimPlugins.nvim-treesitter-parsers.gn
    vimPlugins.nvim-treesitter-parsers.go
    vimPlugins.nvim-treesitter-parsers.godot_resource
    vimPlugins.nvim-treesitter-parsers.gomod
    vimPlugins.nvim-treesitter-parsers.gosum
    vimPlugins.nvim-treesitter-parsers.gowork
    vimPlugins.nvim-treesitter-parsers.gpg
    vimPlugins.nvim-treesitter-parsers.graphql
    vimPlugins.nvim-treesitter-parsers.groovy
    vimPlugins.nvim-treesitter-parsers.gstlaunch
    vimPlugins.nvim-treesitter-parsers.hack
    vimPlugins.nvim-treesitter-parsers.hare
    vimPlugins.nvim-treesitter-parsers.haskell
    vimPlugins.nvim-treesitter-parsers.haskell_persistent
    vimPlugins.nvim-treesitter-parsers.hcl
    vimPlugins.nvim-treesitter-parsers.heex
    vimPlugins.nvim-treesitter-parsers.hjson
    vimPlugins.nvim-treesitter-parsers.hlsl
    vimPlugins.nvim-treesitter-parsers.hocon
    vimPlugins.nvim-treesitter-parsers.hoon
    vimPlugins.nvim-treesitter-parsers.html
    vimPlugins.nvim-treesitter-parsers.htmldjango
    vimPlugins.nvim-treesitter-parsers.http
    vimPlugins.nvim-treesitter-parsers.hurl
    vimPlugins.nvim-treesitter-parsers.ini
    vimPlugins.nvim-treesitter-parsers.ispc
    vimPlugins.nvim-treesitter-parsers.janet_simple
    vimPlugins.nvim-treesitter-parsers.java
    vimPlugins.nvim-treesitter-parsers.javascript
    vimPlugins.nvim-treesitter-parsers.jq
    vimPlugins.nvim-treesitter-parsers.jsdoc
    vimPlugins.nvim-treesitter-parsers.json
    vimPlugins.nvim-treesitter-parsers.json5
    vimPlugins.nvim-treesitter-parsers.jsonc
    vimPlugins.nvim-treesitter-parsers.jsonnet
    vimPlugins.nvim-treesitter-parsers.julia
    vimPlugins.nvim-treesitter-parsers.kconfig
    vimPlugins.nvim-treesitter-parsers.kdl
    vimPlugins.nvim-treesitter-parsers.kotlin
    vimPlugins.nvim-treesitter-parsers.kusto
    vimPlugins.nvim-treesitter-parsers.lalrpop
    vimPlugins.nvim-treesitter-parsers.latex
    vimPlugins.nvim-treesitter-parsers.ledger
    vimPlugins.nvim-treesitter-parsers.leo
    vimPlugins.nvim-treesitter-parsers.linkerscript
    vimPlugins.nvim-treesitter-parsers.liquidsoap
    vimPlugins.nvim-treesitter-parsers.llvm
    vimPlugins.nvim-treesitter-parsers.lua
    vimPlugins.nvim-treesitter-parsers.luadoc
    vimPlugins.nvim-treesitter-parsers.luap
    vimPlugins.nvim-treesitter-parsers.luau
    vimPlugins.nvim-treesitter-parsers.m68k
    vimPlugins.nvim-treesitter-parsers.make
    vimPlugins.nvim-treesitter-parsers.markdown
    vimPlugins.nvim-treesitter-parsers.markdown_inline
    vimPlugins.nvim-treesitter-parsers.matlab
    vimPlugins.nvim-treesitter-parsers.menhir
    vimPlugins.nvim-treesitter-parsers.mermaid
    vimPlugins.nvim-treesitter-parsers.meson
    vimPlugins.nvim-treesitter-parsers.mlir
    vimPlugins.nvim-treesitter-parsers.nasm
    vimPlugins.nvim-treesitter-parsers.nickel
    vimPlugins.nvim-treesitter-parsers.nim
    vimPlugins.nvim-treesitter-parsers.nim_format_string
    vimPlugins.nvim-treesitter-parsers.ninja
    vimPlugins.nvim-treesitter-parsers.nix
    vimPlugins.nvim-treesitter-parsers.norg
    vimPlugins.nvim-treesitter-parsers.nqc
    vimPlugins.nvim-treesitter-parsers.objc
    vimPlugins.nvim-treesitter-parsers.objdump
    vimPlugins.nvim-treesitter-parsers.ocaml
    vimPlugins.nvim-treesitter-parsers.ocaml_interface
    vimPlugins.nvim-treesitter-parsers.ocamllex
    vimPlugins.nvim-treesitter-parsers.odin
    vimPlugins.nvim-treesitter-parsers.org
    vimPlugins.nvim-treesitter-parsers.pascal
    vimPlugins.nvim-treesitter-parsers.passwd
    vimPlugins.nvim-treesitter-parsers.pem
    vimPlugins.nvim-treesitter-parsers.perl
    vimPlugins.nvim-treesitter-parsers.php
    vimPlugins.nvim-treesitter-parsers.php_only
    vimPlugins.nvim-treesitter-parsers.phpdoc
    vimPlugins.nvim-treesitter-parsers.pioasm
    vimPlugins.nvim-treesitter-parsers.po
    vimPlugins.nvim-treesitter-parsers.pod
    vimPlugins.nvim-treesitter-parsers.poe_filter
    vimPlugins.nvim-treesitter-parsers.pony
    vimPlugins.nvim-treesitter-parsers.printf
    vimPlugins.nvim-treesitter-parsers.prisma
    vimPlugins.nvim-treesitter-parsers.promql
    vimPlugins.nvim-treesitter-parsers.properties
    vimPlugins.nvim-treesitter-parsers.proto
    vimPlugins.nvim-treesitter-parsers.prql
    vimPlugins.nvim-treesitter-parsers.psv
    vimPlugins.nvim-treesitter-parsers.pug
    vimPlugins.nvim-treesitter-parsers.puppet
    vimPlugins.nvim-treesitter-parsers.purescript
    vimPlugins.nvim-treesitter-parsers.pymanifest
    vimPlugins.nvim-treesitter-parsers.python
    vimPlugins.nvim-treesitter-parsers.ql
    vimPlugins.nvim-treesitter-parsers.qmldir
    vimPlugins.nvim-treesitter-parsers.qmljs
    vimPlugins.nvim-treesitter-parsers.query
    vimPlugins.nvim-treesitter-parsers.r
    vimPlugins.nvim-treesitter-parsers.racket
    vimPlugins.nvim-treesitter-parsers.rasi
    vimPlugins.nvim-treesitter-parsers.rbs
    vimPlugins.nvim-treesitter-parsers.re2c
    vimPlugins.nvim-treesitter-parsers.regex
    vimPlugins.nvim-treesitter-parsers.rego
    vimPlugins.nvim-treesitter-parsers.requirements
    vimPlugins.nvim-treesitter-parsers.rnoweb
    vimPlugins.nvim-treesitter-parsers.robot
    vimPlugins.nvim-treesitter-parsers.ron
    vimPlugins.nvim-treesitter-parsers.rst
    vimPlugins.nvim-treesitter-parsers.ruby
    vimPlugins.nvim-treesitter-parsers.rust
    vimPlugins.nvim-treesitter-parsers.scala
    vimPlugins.nvim-treesitter-parsers.scfg
    vimPlugins.nvim-treesitter-parsers.scheme
    vimPlugins.nvim-treesitter-parsers.scss
    vimPlugins.nvim-treesitter-parsers.slang
    vimPlugins.nvim-treesitter-parsers.slint
    vimPlugins.nvim-treesitter-parsers.smali
    vimPlugins.nvim-treesitter-parsers.smithy
    vimPlugins.nvim-treesitter-parsers.snakemake
    vimPlugins.nvim-treesitter-parsers.solidity
    vimPlugins.nvim-treesitter-parsers.soql
    vimPlugins.nvim-treesitter-parsers.sosl
    vimPlugins.nvim-treesitter-parsers.sparql
    vimPlugins.nvim-treesitter-parsers.sql
    vimPlugins.nvim-treesitter-parsers.squirrel
    vimPlugins.nvim-treesitter-parsers.ssh_config
    vimPlugins.nvim-treesitter-parsers.starlark
    vimPlugins.nvim-treesitter-parsers.strace
    vimPlugins.nvim-treesitter-parsers.styled
    vimPlugins.nvim-treesitter-parsers.supercollider
    vimPlugins.nvim-treesitter-parsers.surface
    vimPlugins.nvim-treesitter-parsers.svelte
    vimPlugins.nvim-treesitter-parsers.swift
    vimPlugins.nvim-treesitter-parsers.sxhkdrc
    vimPlugins.nvim-treesitter-parsers.systemtap
    vimPlugins.nvim-treesitter-parsers.t32
    vimPlugins.nvim-treesitter-parsers.tablegen
    vimPlugins.nvim-treesitter-parsers.teal
    vimPlugins.nvim-treesitter-parsers.templ
    vimPlugins.nvim-treesitter-parsers.terraform
    vimPlugins.nvim-treesitter-parsers.textproto
    vimPlugins.nvim-treesitter-parsers.thrift
    vimPlugins.nvim-treesitter-parsers.tiger
    vimPlugins.nvim-treesitter-parsers.tlaplus
    vimPlugins.nvim-treesitter-parsers.todotxt
    vimPlugins.nvim-treesitter-parsers.toml
    vimPlugins.nvim-treesitter-parsers.tsv
    vimPlugins.nvim-treesitter-parsers.tsx
    vimPlugins.nvim-treesitter-parsers.turtle
    vimPlugins.nvim-treesitter-parsers.twig
    vimPlugins.nvim-treesitter-parsers.typescript
    vimPlugins.nvim-treesitter-parsers.typoscript
    vimPlugins.nvim-treesitter-parsers.udev
    vimPlugins.nvim-treesitter-parsers.ungrammar
    vimPlugins.nvim-treesitter-parsers.unison
    vimPlugins.nvim-treesitter-parsers.usd
    vimPlugins.nvim-treesitter-parsers.uxntal
    vimPlugins.nvim-treesitter-parsers.v
    vimPlugins.nvim-treesitter-parsers.vala
    vimPlugins.nvim-treesitter-parsers.verilog
    vimPlugins.nvim-treesitter-parsers.vhs
    vimPlugins.nvim-treesitter-parsers.vim
    vimPlugins.nvim-treesitter-parsers.vimdoc
    vimPlugins.nvim-treesitter-parsers.vue
    vimPlugins.nvim-treesitter-parsers.wgsl
    vimPlugins.nvim-treesitter-parsers.wgsl_bevy
    vimPlugins.nvim-treesitter-parsers.wing
    vimPlugins.nvim-treesitter-parsers.xcompose
    vimPlugins.nvim-treesitter-parsers.xml
    vimPlugins.nvim-treesitter-parsers.yaml
    vimPlugins.nvim-treesitter-parsers.yang
    vimPlugins.nvim-treesitter-parsers.yuck
    vimPlugins.nvim-treesitter-parsers.zathurarc
    vimPlugins.nvim-treesitter-parsers.zig
    vimPlugins.nvim-treesitter-pyfold
    vimPlugins.nvim-treesitter-refactor
    vimPlugins.nvim-treesitter-textobjects
    vimPlugins.nvim-treesitter-textsubjects
    vimPlugins.nvim-ts-autotag
    vimPlugins.nvim-ts-context-commentstring
    vimPlugins.nvim-ufo
    vimPlugins.nvim-unception
    vimPlugins.nvim-web-devicons
    vimPlugins.nvim-whichkey-setup-lua
    vimPlugins.nvim-window-picker
    vimPlugins.nvim-yarp
    vimPlugins.nvim_context_vt
    vimPlugins.nvimdev-nvim
    vimPlugins.nvterm
    vimPlugins.obsidian-nvim
    vimPlugins.oceanic-material
    vimPlugins.oceanic-next
    vimPlugins.octo-nvim
    vimPlugins.oil-nvim
    vimPlugins.ollama-nvim
    vimPlugins.omnisharp-extended-lsp-nvim
    vimPlugins.one-nvim
    vimPlugins.onedark-nvim
    vimPlugins.onedark-vim
    vimPlugins.onedarkpro-nvim
    vimPlugins.onehalf
    vimPlugins.onenord-nvim
    vimPlugins.open-browser
    vimPlugins.open-browser-github-vim
    vimPlugins.open-browser-vim
    vimPlugins.openingh-nvim
    vimPlugins.openscad-nvim
    vimPlugins.orgmode
    vimPlugins.other-nvim
    vimPlugins.otter-nvim
    vimPlugins.overseer-nvim
    vimPlugins.oxocarbon-nvim
    vimPlugins.package-info-nvim
    vimPlugins.packer-nvim
    vimPlugins.palenight-vim
    vimPlugins.palette-nvim
    vimPlugins.papercolor-theme
    vimPlugins.parinfer-rust
    vimPlugins.pathogen
    vimPlugins.pear-tree
    vimPlugins.pears-nvim
    vimPlugins.persistence-nvim
    vimPlugins.peskcolor-vim
    vimPlugins.pest-vim
    vimPlugins.pgsql-vim
    vimPlugins.phpactor
    vimPlugins.pig-vim
    vimPlugins.plantuml-previewer-vim
    vimPlugins.plantuml-syntax
    vimPlugins.playground
    vimPlugins.plenary-nvim
    vimPlugins.poimandres-nvim
    vimPlugins.polyglot
    vimPlugins.pony-vim-syntax
    vimPlugins.popfix
    vimPlugins.popup-nvim
    vimPlugins.presence-nvim
    vimPlugins.presenting-vim
    vimPlugins.preto
    vimPlugins.pretty-fold-nvim
    vimPlugins.prettyprint
    vimPlugins.prev_indent
    vimPlugins.project-nvim
    vimPlugins.promise-async
    vimPlugins.psc-ide-vim
    vimPlugins.pure-lua
    vimPlugins.purescript-vim
    vimPlugins.python-mode
    vimPlugins.python-syntax
    vimPlugins.pywal-nvim
    vimPlugins.quarto-nvim
    vimPlugins.quick-scope
    vimPlugins.quickfix-reflector-vim
    vimPlugins.quickfixstatus
    vimPlugins.quickmath-nvim
    vimPlugins.quickrun
    vimPlugins.rainbow
    vimPlugins.rainbow-delimiters-nvim
    vimPlugins.rainbow_parentheses
    vimPlugins.rainbow_parentheses-vim
    vimPlugins.random-vim
    vimPlugins.range-highlight-nvim
    vimPlugins.ranger-vim
    vimPlugins.rcshell-vim
    vimPlugins.readline-vim
    vimPlugins.refactoring-nvim
    vimPlugins.registers-nvim
    vimPlugins.remember-nvim
    vimPlugins.renamer-nvim
    vimPlugins.repeat
    vimPlugins.replacer-nvim
    vimPlugins.rest-nvim
    vimPlugins.restore-view-vim
    vimPlugins.rhubarb
    vimPlugins.riv
    vimPlugins.riv-vim
    vimPlugins.rnvimr
    vimPlugins.robotframework-vim
    vimPlugins.ron-vim
    vimPlugins.rose-pine
    vimPlugins.roslyn-nvim
    vimPlugins.rspec-vim
    vimPlugins.rtorrent-syntax-file
    vimPlugins.rust-tools-nvim
    vimPlugins.rust-vim
    vimPlugins.rustaceanvim
    vimPlugins.sad-vim
    vimPlugins.salt-vim
    vimPlugins.samodostal-image-nvim
    vimPlugins.satellite-nvim
    vimPlugins.scnvim
    vimPlugins.scope-nvim
    vimPlugins.scrollbar-nvim
    vimPlugins.scss-syntax-vim
    vimPlugins.searchbox-nvim
    vimPlugins.securemodelines
    vimPlugins.self
    vimPlugins.semantic-highlight-vim
    vimPlugins.semshi
    vimPlugins.sensible
    vimPlugins.seoul256-vim
    vimPlugins.sg-nvim
    vimPlugins.shabadou-vim
    vimPlugins.sideways-vim
    vimPlugins.signature
    vimPlugins.skim
    vimPlugins.skim-vim
    vimPlugins.sky-color-clock-vim
    vimPlugins.sleuth
    vimPlugins.slimv
    vimPlugins.smart-splits-nvim
    vimPlugins.smartcolumn-nvim
    vimPlugins.smartpairs-vim
    vimPlugins.smartyank-nvim
    vimPlugins.snap
    vimPlugins.snipmate
    vimPlugins.snippets-nvim
    vimPlugins.sniprun
    vimPlugins.solarized
    vimPlugins.solarized-nvim
    vimPlugins.solidity
    vimPlugins.sonokai
    vimPlugins.sort-nvim
    vimPlugins.sourcemap-vim
    vimPlugins.space-vim
    vimPlugins.spacevim
    vimPlugins.sparkup
    vimPlugins.specs-nvim
    vimPlugins.spellsitter-nvim
    vimPlugins.sphinx-nvim
    vimPlugins.splice-vim
    vimPlugins.split-term-vim
    vimPlugins.splitjoin-vim
    vimPlugins.sqlite-lua
    vimPlugins.srcery-vim
    vimPlugins.sslsecure-vim
    vimPlugins.ssr
    vimPlugins.ssr-nvim
    vimPlugins.stabilize-nvim
    vimPlugins.stan-vim
    vimPlugins.starrynight
    vimPlugins.starsearch-vim
    vimPlugins.startup-nvim
    vimPlugins.statix
    vimPlugins.statuscol-nvim
    vimPlugins.stylish-haskell
    vimPlugins.stylish-nvim
    vimPlugins.stylishHaskell
    vimPlugins.substitute-nvim
    vimPlugins.substrata-nvim
    vimPlugins.suda-vim
    vimPlugins.supertab
    vimPlugins.surround
    vimPlugins.surround-nvim
    vimPlugins.sved
    vimPlugins.swayconfig-vim
    vimPlugins.swift-vim
    vimPlugins.switch-vim
    vimPlugins.symbols-outline-nvim
    vimPlugins.syntastic
    vimPlugins.tabby-nvim
    vimPlugins.table-mode
    vimPlugins.tabline-nvim
    vimPlugins.tabmerge
    vimPlugins.tabnine-vim
    vimPlugins.taboo-vim
    vimPlugins.tabout-nvim
    vimPlugins.tabpagebuffer
    vimPlugins.tabpagebuffer-vim
    vimPlugins.tabpagecd
    vimPlugins.tabular
    vimPlugins.tagalong-vim
    vimPlugins.tagbar
    vimPlugins.taglist
    vimPlugins.taglist-vim
    vimPlugins.tailwindcss-colors-nvim
    vimPlugins.targets-vim
    vimPlugins.taskwarrior
    vimPlugins.taskwiki
    vimPlugins.tcomment_vim
    vimPlugins.telekasten-nvim
    vimPlugins.telescope-asynctasks-nvim
    vimPlugins.telescope-cheat-nvim
    vimPlugins.telescope-coc-nvim
    vimPlugins.telescope-dap-nvim
    vimPlugins.telescope-file-browser-nvim
    vimPlugins.telescope-frecency-nvim
    vimPlugins.telescope-fzf-native-nvim
    vimPlugins.telescope-fzf-writer-nvim
    vimPlugins.telescope-fzy-native-nvim
    vimPlugins.telescope-github-nvim
    vimPlugins.telescope-live-grep-args-nvim
    vimPlugins.telescope-lsp-handlers-nvim
    vimPlugins.telescope-manix
    vimPlugins.telescope-media-files-nvim
    vimPlugins.telescope-nvim
    vimPlugins.telescope-project-nvim
    vimPlugins.telescope-sg
    vimPlugins.telescope-symbols-nvim
    vimPlugins.telescope-ui-select-nvim
    vimPlugins.telescope-ultisnips-nvim
    vimPlugins.telescope-undo-nvim
    vimPlugins.telescope-vim-bookmarks-nvim
    vimPlugins.telescope-z-nvim
    vimPlugins.telescope-zf-native-nvim
    vimPlugins.telescope-zoxide
    vimPlugins.telescope_hoogle
    vimPlugins.template-string-nvim
    vimPlugins.tender-vim
    vimPlugins.term-edit-nvim
    vimPlugins.terminus
    vimPlugins.termwrapper-nvim
    vimPlugins.tern_for_vim
    vimPlugins.tex-conceal-vim
    vimPlugins.text-case-nvim
    vimPlugins.thesaurus_query-vim
    vimPlugins.thumbnail
    vimPlugins.thumbnail-vim
    vimPlugins.timestamp-vim
    vimPlugins.tint-nvim
    vimPlugins.tinykeymap
    vimPlugins.tlib
    vimPlugins.tlib_vim
    vimPlugins.tmux-complete-vim
    vimPlugins.tmux-navigator
    vimPlugins.tmux-nvim
    vimPlugins.tmuxNavigator
    vimPlugins.tmuxline-vim
    vimPlugins.todo-comments-nvim
    vimPlugins.todo-txt-vim
    vimPlugins.toggleterm-nvim
    vimPlugins.tokyonight-nvim
    vimPlugins.traces-vim
    vimPlugins.train-nvim
    vimPlugins.treesj
    vimPlugins.tremor-vim
    vimPlugins.trim-nvim
    vimPlugins.trouble-nvim
    vimPlugins.true-zen-nvim
    vimPlugins.tslime
    vimPlugins.tslime-vim
    vimPlugins.tsuquyomi
    vimPlugins.tup
    vimPlugins.twilight-nvim
    vimPlugins.typescript-nvim
    vimPlugins.typescript-tools-nvim
    vimPlugins.typescript-vim
    vimPlugins.typst-vim
    vimPlugins.ultisnips
    vimPlugins.undotree
    vimPlugins.unicode-vim
    vimPlugins.unison
    vimPlugins.unite
    vimPlugins.unite-vim
    vimPlugins.urlview-nvim
    vimPlugins.utl-vim
    vimPlugins.vCoolor-vim
    vimPlugins.vader-vim
    vimPlugins.venn-nvim
    vimPlugins.verilog_systemverilog-vim
    vimPlugins.vifm-vim
    vimPlugins.vim-CtrlXA
    vimPlugins.vim-DetectSpellLang
    vimPlugins.vim-LanguageTool
    vimPlugins.vim-ReplaceWithRegister
    vimPlugins.vim-ReplaceWithSameIndentRegister
    vimPlugins.vim-SyntaxRange
    vimPlugins.vim-abolish
    vimPlugins.vim-addon-actions
    vimPlugins.vim-addon-async
    vimPlugins.vim-addon-background-cmd
    vimPlugins.vim-addon-commenting
    vimPlugins.vim-addon-completion
    vimPlugins.vim-addon-errorformats
    vimPlugins.vim-addon-goto-thing-at-cursor
    vimPlugins.vim-addon-local-vimrc
    vimPlugins.vim-addon-manager
    vimPlugins.vim-addon-mru
    vimPlugins.vim-addon-mw-utils
    vimPlugins.vim-addon-nix
    vimPlugins.vim-addon-other
    vimPlugins.vim-addon-php-manual
    vimPlugins.vim-addon-signs
    vimPlugins.vim-addon-sql
    vimPlugins.vim-addon-syntax-checker
    vimPlugins.vim-addon-toggle-buffer
    vimPlugins.vim-addon-vim2nix
    vimPlugins.vim-addon-xdebug
    vimPlugins.vim-advanced-sorters
    vimPlugins.vim-after-object
    vimPlugins.vim-agda
    vimPlugins.vim-airline
    vimPlugins.vim-airline-clock
    vimPlugins.vim-airline-themes
    vimPlugins.vim-alias
    vimPlugins.vim-android
    vimPlugins.vim-anzu
    vimPlugins.vim-apm
    vimPlugins.vim-argumentative
    vimPlugins.vim-argwrap
    vimPlugins.vim-asterisk
    vimPlugins.vim-astro
    vimPlugins.vim-asymptote
    vimPlugins.vim-auto-save
    vimPlugins.vim-autoformat
    vimPlugins.vim-automkdir
    vimPlugins.vim-autosource
    vimPlugins.vim-autoswap
    vimPlugins.vim-bazel
    vimPlugins.vim-bbye
    vimPlugins.vim-be-good
    vimPlugins.vim-beancount
    vimPlugins.vim-bepoptimist
    vimPlugins.vim-better-whitespace
    vimPlugins.vim-bookmarks
    vimPlugins.vim-boxdraw
    vimPlugins.vim-bracketed-paste
    vimPlugins.vim-bsv
    vimPlugins.vim-buffergator
    vimPlugins.vim-bufferline
    vimPlugins.vim-bufkill
    vimPlugins.vim-caddyfile
    vimPlugins.vim-capslock
    vimPlugins.vim-carbon-now-sh
    vimPlugins.vim-ccls
    vimPlugins.vim-choosewin
    vimPlugins.vim-clang-format
    vimPlugins.vim-clap
    vimPlugins.vim-clojure-highlight
    vimPlugins.vim-clojure-static
    vimPlugins.vim-closer
    vimPlugins.vim-closetag
    vimPlugins.vim-cmake
    vimPlugins.vim-code-dark
    vimPlugins.vim-codefmt
    vimPlugins.vim-coffee-script
    vimPlugins.vim-colemak
    vimPlugins.vim-colors-solarized
    vimPlugins.vim-colorschemes
    vimPlugins.vim-colorstepper
    vimPlugins.vim-commentary
    vimPlugins.vim-concourse
    vimPlugins.vim-cool
    vimPlugins.vim-cpp-enhanced-highlight
    vimPlugins.vim-crates
    vimPlugins.vim-crystal
    vimPlugins.vim-csharp
    vimPlugins.vim-css-color
    vimPlugins.vim-cue
    vimPlugins.vim-cursorword
    vimPlugins.vim-cute-python
    vimPlugins.vim-dadbod
    vimPlugins.vim-dadbod-completion
    vimPlugins.vim-dadbod-ui
    vimPlugins.vim-dasht
    vimPlugins.vim-deus
    vimPlugins.vim-devicons
    vimPlugins.vim-dim
    vimPlugins.vim-diminactive
    vimPlugins.vim-dirdiff
    vimPlugins.vim-dirvish
    vimPlugins.vim-dirvish-git
    vimPlugins.vim-dispatch
    vimPlugins.vim-dispatch-neovim
    vimPlugins.vim-docbk
    vimPlugins.vim-docbk-snippets
    vimPlugins.vim-dotenv
    vimPlugins.vim-easy-align
    vimPlugins.vim-easyescape
    vimPlugins.vim-easygit
    vimPlugins.vim-easymotion
    vimPlugins.vim-easytags
    vimPlugins.vim-eighties
    vimPlugins.vim-elixir
    vimPlugins.vim-elm-syntax
    vimPlugins.vim-emoji
    vimPlugins.vim-endwise
    vimPlugins.vim-enmasse
    vimPlugins.vim-erlang-compiler
    vimPlugins.vim-erlang-omnicomplete
    vimPlugins.vim-erlang-runtime
    vimPlugins.vim-erlang-tags
    vimPlugins.vim-eunuch
    vimPlugins.vim-exchange
    vimPlugins.vim-expand-region
    vimPlugins.vim-extradite
    vimPlugins.vim-fetch
    vimPlugins.vim-figlet
    vimPlugins.vim-fireplace
    vimPlugins.vim-fish
    vimPlugins.vim-flagship
    vimPlugins.vim-flake8
    vimPlugins.vim-flatbuffers
    vimPlugins.vim-floaterm
    vimPlugins.vim-flog
    vimPlugins.vim-flutter
    vimPlugins.vim-fsharp
    vimPlugins.vim-ft-diff_fold
    vimPlugins.vim-fubitive
    vimPlugins.vim-fugitive
    vimPlugins.vim-fzf-coauthorship
    vimPlugins.vim-gas
    vimPlugins.vim-gh-line
    vimPlugins.vim-ghost
    vimPlugins.vim-gist
    vimPlugins.vim-gista
    vimPlugins.vim-git
    vimPlugins.vim-gitbranch
    vimPlugins.vim-gitgutter
    vimPlugins.vim-github-dashboard
    vimPlugins.vim-glsl
    vimPlugins.vim-gnupg
    vimPlugins.vim-go
    vimPlugins.vim-grammarous
    vimPlugins.vim-graphql
    vimPlugins.vim-grepper
    vimPlugins.vim-gruvbox8
    vimPlugins.vim-gui-position
    vimPlugins.vim-gutentags
    vimPlugins.vim-hardtime
    vimPlugins.vim-haskell-module-name
    vimPlugins.vim-haskellConcealPlus
    vimPlugins.vim-haskellconceal
    vimPlugins.vim-hcl
    vimPlugins.vim-hdevtools
    vimPlugins.vim-helm
    vimPlugins.vim-hexokinase
    vimPlugins.vim-hier
    vimPlugins.vim-highlightedyank
    vimPlugins.vim-hindent
    vimPlugins.vim-hocon
    vimPlugins.vim-hoogle
    vimPlugins.vim-horizon
    vimPlugins.vim-html-template-literals
    vimPlugins.vim-husk
    vimPlugins.vim-hybrid
    vimPlugins.vim-hybrid-material
    vimPlugins.vim-iced-coffee-script
    vimPlugins.vim-illuminate
    vimPlugins.vim-indent-guides
    vimPlugins.vim-indent-object
    vimPlugins.vim-indentwise
    vimPlugins.vim-indexed-search
    vimPlugins.vim-ipython
    vimPlugins.vim-isort
    vimPlugins.vim-jack-in
    vimPlugins.vim-janah
    vimPlugins.vim-javacomplete2
    vimPlugins.vim-javascript
    vimPlugins.vim-javascript-syntax
    vimPlugins.vim-jinja
    vimPlugins.vim-jinja-languages
    vimPlugins.vim-jsbeautify
    vimPlugins.vim-jsdoc
    vimPlugins.vim-json
    vimPlugins.vim-jsonnet
    vimPlugins.vim-jsonpath
    vimPlugins.vim-jsx-pretty
    vimPlugins.vim-jsx-typescript
    vimPlugins.vim-julia-cell
    vimPlugins.vim-just
    vimPlugins.vim-kitty-navigator
    vimPlugins.vim-lark-syntax
    vimPlugins.vim-lastplace
    vimPlugins.vim-latex-live-preview
    vimPlugins.vim-lawrencium
    vimPlugins.vim-leader-guide
    vimPlugins.vim-lean
    vimPlugins.vim-ledger
    vimPlugins.vim-lexical
    vimPlugins.vim-lfe
    vimPlugins.vim-lightline-coc
    vimPlugins.vim-lion
    vimPlugins.vim-liquid
    vimPlugins.vim-llvm
    vimPlugins.vim-localvimrc
    vimPlugins.vim-logreview
    vimPlugins.vim-loves-dafny
    vimPlugins.vim-lsc
    vimPlugins.vim-lsp
    vimPlugins.vim-lsp-ale
    vimPlugins.vim-lsp-cxx-highlight
    vimPlugins.vim-lsp-settings
    vimPlugins.vim-lsp-snippets
    vimPlugins.vim-lsp-ultisnips
    vimPlugins.vim-lua
    vimPlugins.vim-maktaba
    vimPlugins.vim-manpager
    vimPlugins.vim-markbar
    vimPlugins.vim-markdown
    vimPlugins.vim-markdown-composer
    vimPlugins.vim-markdown-toc
    vimPlugins.vim-matchup
    vimPlugins.vim-mediawiki-editor
    vimPlugins.vim-mergetool
    vimPlugins.vim-merginal
    vimPlugins.vim-metamath
    vimPlugins.vim-misc
    vimPlugins.vim-molokai-delroth
    vimPlugins.vim-monokai
    vimPlugins.vim-monokai-pro
    vimPlugins.vim-monokai-tasty
    vimPlugins.vim-move
    vimPlugins.vim-mucomplete
    vimPlugins.vim-multiple-cursors
    vimPlugins.vim-mundo
    vimPlugins.vim-mustache-handlebars
    vimPlugins.vim-nerdtree-syntax-highlight
    vimPlugins.vim-nerdtree-tabs
    vimPlugins.vim-nftables
    vimPlugins.vim-niceblock
    vimPlugins.vim-nickel
    vimPlugins.vim-ninja-feet
    vimPlugins.vim-nix
    vimPlugins.vim-nixhash
    vimPlugins.vim-noctu
    vimPlugins.vim-nong-theme
    vimPlugins.vim-numbertoggle
    vimPlugins.vim-obsession
    vimPlugins.vim-ocaml
    vimPlugins.vim-one
    vimPlugins.vim-opencl
    vimPlugins.vim-openscad
    vimPlugins.vim-operator-replace
    vimPlugins.vim-operator-surround
    vimPlugins.vim-operator-user
    vimPlugins.vim-orgmode
    vimPlugins.vim-ormolu
    vimPlugins.vim-osc52
    vimPlugins.vim-oscyank
    vimPlugins.vim-over
    vimPlugins.vim-packer
    vimPlugins.vim-pager
    vimPlugins.vim-pandoc
    vimPlugins.vim-pandoc-after
    vimPlugins.vim-pandoc-syntax
    vimPlugins.vim-paper
    vimPlugins.vim-parinfer
    vimPlugins.vim-pasta
    vimPlugins.vim-pathogen
    vimPlugins.vim-peekaboo
    vimPlugins.vim-pencil
    vimPlugins.vim-phabricator
    vimPlugins.vim-pico8-syntax
    vimPlugins.vim-plug
    vimPlugins.vim-plugin-AnsiEsc
    vimPlugins.vim-pluto
    vimPlugins.vim-polyglot
    vimPlugins.vim-pony
    vimPlugins.vim-poweryank
    vimPlugins.vim-prettier
    vimPlugins.vim-prettyprint
    vimPlugins.vim-printer
    vimPlugins.vim-prisma
    vimPlugins.vim-projectionist
    vimPlugins.vim-prosession
    vimPlugins.vim-protobuf
    vimPlugins.vim-ps1
    vimPlugins.vim-pug
    vimPlugins.vim-puppet
    vimPlugins.vim-python-pep8-indent
    vimPlugins.vim-qf
    vimPlugins.vim-qlist
    vimPlugins.vim-qml
    vimPlugins.vim-quickrun
    vimPlugins.vim-racer
    vimPlugins.vim-racket
    vimPlugins.vim-ragtag
    vimPlugins.vim-rails
    vimPlugins.vim-reasonml
    vimPlugins.vim-repeat
    vimPlugins.vim-rhubarb
    vimPlugins.vim-rooter
    vimPlugins.vim-rsi
    vimPlugins.vim-ruby
    vimPlugins.vim-salve
    vimPlugins.vim-sandwich
    vimPlugins.vim-sayonara
    vimPlugins.vim-scala
    vimPlugins.vim-scouter
    vimPlugins.vim-scriptease
    vimPlugins.vim-search-pulse
    vimPlugins.vim-sensible
    vimPlugins.vim-sentence-chopper
    vimPlugins.vim-sexp
    vimPlugins.vim-sexp-mappings-for-regular-people
    vimPlugins.vim-shellcheck
    vimPlugins.vim-signature
    vimPlugins.vim-signify
    vimPlugins.vim-simpledb
    vimPlugins.vim-slash
    vimPlugins.vim-sleuth
    vimPlugins.vim-slime
    vimPlugins.vim-smali
    vimPlugins.vim-smalls
    vimPlugins.vim-smartbd
    vimPlugins.vim-smartbw
    vimPlugins.vim-smoothie
    vimPlugins.vim-smt2
    vimPlugins.vim-sneak
    vimPlugins.vim-snipmate
    vimPlugins.vim-snippets
    vimPlugins.vim-solarized8
    vimPlugins.vim-solidity
    vimPlugins.vim-sort-motion
    vimPlugins.vim-speeddating
    vimPlugins.vim-spirv
    vimPlugins.vim-startify
    vimPlugins.vim-startuptime
    vimPlugins.vim-strip-trailing-whitespace
    vimPlugins.vim-stylish-haskell
    vimPlugins.vim-stylishask
    vimPlugins.vim-substrata
    vimPlugins.vim-subversive
    vimPlugins.vim-surround
    vimPlugins.vim-svelte
    vimPlugins.vim-swap
    vimPlugins.vim-table-mode
    vimPlugins.vim-tabpagecd
    vimPlugins.vim-tbone
    vimPlugins.vim-teal
    vimPlugins.vim-terminator
    vimPlugins.vim-terraform
    vimPlugins.vim-terraform-completion
    vimPlugins.vim-test
    vimPlugins.vim-textobj-comment
    vimPlugins.vim-textobj-entire
    vimPlugins.vim-textobj-function
    vimPlugins.vim-textobj-haskell
    vimPlugins.vim-textobj-multiblock
    vimPlugins.vim-textobj-user
    vimPlugins.vim-textobj-variable-segment
    vimPlugins.vim-themis
    vimPlugins.vim-tmux
    vimPlugins.vim-tmux-clipboard
    vimPlugins.vim-tmux-focus-events
    vimPlugins.vim-tmux-navigator
    vimPlugins.vim-togglelist
    vimPlugins.vim-toml
    vimPlugins.vim-tpipeline
    vimPlugins.vim-trailing-whitespace
    vimPlugins.vim-tridactyl
    vimPlugins.vim-tsx
    vimPlugins.vim-twig
    vimPlugins.vim-twiggy
    vimPlugins.vim-ultest
    vimPlugins.vim-unicoder
    vimPlugins.vim-unimpaired
    vimPlugins.vim-vagrant
    vimPlugins.vim-vinegar
    vimPlugins.vim-visual-increment
    vimPlugins.vim-visual-multi
    vimPlugins.vim-visual-star-search
    vimPlugins.vim-visualstar
    vimPlugins.vim-vp4
    vimPlugins.vim-vsnip
    vimPlugins.vim-vsnip-integ
    vimPlugins.vim-vue
    vimPlugins.vim-vue-plugin
    vimPlugins.vim-wakatime
    vimPlugins.vim-watchdogs
    vimPlugins.vim-wayland-clipboard
    vimPlugins.vim-which-key
    vimPlugins.vim-windowswap
    vimPlugins.vim-wordmotion
    vimPlugins.vim-wordy
    vimPlugins.vim-xdebug
    vimPlugins.vim-xkbswitch
    vimPlugins.vim-xtabline
    vimPlugins.vim-yaml
    vimPlugins.vim-yapf
    vimPlugins.vim-zettel
    vimPlugins.vim2hs
    vimPlugins.vim2nix
    vimPlugins.vim9-stargate
    vimPlugins.vim_current_word
    vimPlugins.vimacs
    vimPlugins.vimade
    vimPlugins.vimagit
    vimPlugins.vimelette
    vimPlugins.vimfiler-vim
    vimPlugins.vimoutliner
    vimPlugins.vimpreviewpandoc
    vimPlugins.vimproc
    vimPlugins.vimproc-vim
    vimPlugins.vimsence
    vimPlugins.vimshell
    vimPlugins.vimshell-vim
    vimPlugins.vimspector
    vimPlugins.vimtex
    vimPlugins.vimux
    vimPlugins.vimwiki
    vimPlugins.vinegar
    vimPlugins.virtual-types-nvim
    vimPlugins.vis
    vimPlugins.vissort-vim
    vimPlugins.vista-vim
    vimPlugins.vscode-nvim
    vimPlugins.wal-vim
    vimPlugins.watchdogs
    vimPlugins.webapi-vim
    vimPlugins.wgsl-vim
    vimPlugins.which-key-nvim
    vimPlugins.whitespace-nvim
    vimPlugins.wiki-ft-vim
    vimPlugins.wiki-vim
    vimPlugins.wilder-nvim
    vimPlugins.wildfire-vim
    vimPlugins.winbar-nvim
    vimPlugins.windows-nvim
    vimPlugins.winshift-nvim
    vimPlugins.wmgraphviz-vim
    vimPlugins.wombat256
    vimPlugins.wombat256-vim
    vimPlugins.workflowish
    vimPlugins.wrapping-nvim
    vimPlugins.wstrip-vim
    vimPlugins.wtf-nvim
    vimPlugins.xptemplate
    vimPlugins.xterm-color-table
    vimPlugins.xterm-color-table-vim
    vimPlugins.yankring
    vimPlugins.yanky-nvim
    vimPlugins.yats-vim
    vimPlugins.yescapsquit-vim
    vimPlugins.yuck-vim
    vimPlugins.zeavim
    vimPlugins.zeavim-vim
    vimPlugins.zen-mode-nvim
    vimPlugins.zenbones-nvim
    vimPlugins.zenburn
    vimPlugins.zephyr-nvim
    vimPlugins.zig-vim
    vimPlugins.zk-nvim
    vimPlugins.zoomwintab-vim
    vimPlugins.zoxide-vim
    vimPluginsUpdater

    virt-manager
    virt-top
    virtiofsd
    vit
    vscodium
#    (vscode-with-extensions.override {
#      vscode = vscodium;
#      vscodeExtensions = with vscode-extensions; [
#        ms-vscode.cpptools
#      ];
#    })
    w3m
    watch
    waybar
    wdisplays
#    webex
    wezterm
    wget
    wireguard-tools
    wl-clipboard
    wl-clip-persist
    wlsunset
    wofi
    wpgtk
    wshowkeys
    xkcd-font
    xkcdpass
    yarn
    zathura
    zenmonitor
    yt-dlp
    zip
    zstd
  ];
}
