{
  system,
  config,
  pkgs,
  pkgs-stable,
  inputs,
  ...
}:
{

  environment.systemPackages = with pkgs; [

    abcde
    abiword
    akkuPackages.scheme-langserver
    alacritty
    alsa-utils
    amd-blis
    amdctl
    amdgpu_top
    #amdvlk
    android-file-transfer
    appimage-run
    aria2
    asciinema
    b612
    bat
    bc
    #    beets
    binocle
    blocky
    blueberry
    bluetui
    bluetuith
    bluez-tools
    bottom
    #    brasero
    # broken
    broot
    btop
    buildah
    bun
    caddy
    canta-theme
    can-utils
    cargo
    cfssl
    chafa
    chromium
    circt
    clblast
    clinfo
    #    clipgrab
    #    cliphist
    clipman
    clipse
    clolcat
    cmake
    colordiff
    conky
    #    copyq
    cosmic-term
    cri-o
    cri-tools
    criu
    crrcsim
    crun
    cups-brother-hll3230cdw
    cups-browsed
    cups-filters
    cups-printers
    #    cups-zj-58
    dbus-broker
    ddcutil
    debootstrap
    delta
    delve
    deno
    detox
    #diffoscope
    difftastic
    diffuse
    dig
    dina-font
    diskus
    dive
    #    doublecmd
    duf
    duff
    dunst
    dust
    #easyeffects
    elementary-xfce-icon-theme
    emacs
    # end rocm
    envsubst
    epson-escpr
    # esphome
    eternal-terminal
    evtest
    exfat
    exfatprogs
    fastfetch
    fastgron
    fd
    feishin
    ffmpeg_6-full
    figlet
    file
    file-roller
    fio
    firefox
    fish
    #    flightgear
    fnm
    foliate
    font-awesome
    foot
    fortune
    freetube
    fx
    fzf
    #    gbar
    gdu
    gedit
    ghostty
    gimp
    #    gitAndTools.git-extras
    gitbatch
    git-extras
    gitFull
    gitg
    git-lfs
    #gitMinimal
    git-repo
    git-repo-updater
    gkrellm
    glib
    glow
    # gnomeExtensions.easyeffects-preset-selector
    gnome-firmware
    # gnome-themes-extra
    # gnome-tweaks
    gnumeric
    #go
    go
    #    golangci-lint
    #    golangci-lint-langserver
    gomi
    gomodifytags
    gopls
    gossa
    gotests
    go-tools
    gotty
    gparted
    gping
    gptfdisk
    graphviz
    # gron
    guile
    gvproxy
    hack-font
    helix
    hexyl
    htmlq
    htop
    httrack
    hunspell
    hunspellDicts.en_US
    hyperfine
    hypr
    hyprcursor
    hypridle
    # hyprland
    hyprland
    hyprland-protocols
    hyprlauncher
    hyprlock
    hyprpaper
    hyprpicker
    hyprpolkitagent
    hyprpwcenter
    hyprshade
    hyprshot
    hyprsunset
    hyprsysteminfo
    idevicerestore
    ifuse
    imagemagick
    imhex
    impl
    imv
    #    input-remapper
    #    inputs.zen-browser.packages."${system}".twilight
    #    iotop
    iotop-c
    iperf3
    iproute2
    #isd
    isd
    jc
    # jeezyvim
    #    jmtpfs
    jq
    jql
    # jupyter
    kdiff3
    killall
    kind
    kitty
    # klipper graphs
    koreader
    kubebuilder
    kubecolor
    kubectl
    kubectl-tree
    kubectx
    kubernetes
    kubetail
    kubevirt
    lagrange
    lagrange-tui
    lazygit
    ledger
    lego
    libedit
    libfido2
    libimobiledevice
    libnotify
    libreoffice-fresh
    #    libreoffice-qt6-fresh
    #librewolf
    #    libsForQt5.qt5ct
    #    libsForQt5.qt5.qtwayland
    #    libsForQt5.qtstyleplugin-kvantum
    libva-utils
    libvirt
    libxml2
    libxslt
    libzip
    light
    links2
    #    litestream
    lix
    llama-cpp
    lldb
    # llm
    #llvmPackages.mlir
    logiops
    logitech-udev-rules
    losslesscut-bin
    loupe
    lsd
    lsix
    lsof
    ltunify
    lua51Packages.telescope-nvim
    luajit
    luajitPackages.telescope-nvim
    #lunarvim
    lvm2
    lvm2_dmeventd
    lvm2_vdo
    lynx
    mako
    maven
    mc
    meld
    microcode-amd
    minicom
    # ml:
    most
    mpv
    #        ms-vscode.cpptools
    mupdf
    nautilus
    ##nemo-with-extensions
    #    neovide
    neovim
    #nerdfonts
    nerd-fonts._0xproto
    nerd-fonts._3270
    nerd-fonts.agave
    nerd-fonts.anonymice
    nerd-fonts.arimo
    nerd-fonts.aurulent-sans-mono
    nerd-fonts.bigblue-terminal
    nerd-fonts.bitstream-vera-sans-mono
    nerd-fonts.blex-mono
    nerd-fonts.caskaydia-cove
    nerd-fonts.caskaydia-mono
    nerd-fonts.code-new-roman
    nerd-fonts.comic-shanns-mono
    nerd-fonts.commit-mono
    nerd-fonts.cousine
    nerd-fonts.d2coding
    nerd-fonts.daddy-time-mono
    nerd-fonts.dejavu-sans-mono
    nerd-fonts.departure-mono
    nerd-fonts.droid-sans-mono
    nerd-fonts.envy-code-r
    nerd-fonts.fantasque-sans-mono
    nerd-fonts.fira-code
    nerd-fonts.fira-mono
    nerd-fonts.geist-mono
    nerd-fonts.gohufont
    nerd-fonts.go-mono
    nerd-fonts.hack
    nerd-fonts.hasklug
    nerd-fonts.heavy-data
    nerd-fonts.hurmit
    nerd-fonts.im-writing
    nerd-fonts.inconsolata
    nerd-fonts.inconsolata-go
    nerd-fonts.inconsolata-lgc
    nerd-fonts.intone-mono
    nerd-fonts.iosevka
    nerd-fonts.iosevka-term
    nerd-fonts.iosevka-term-slab
    nerd-fonts.jetbrains-mono
    nerd-fonts.lekton
    nerd-fonts.liberation
    nerd-fonts.lilex
    nerd-fonts.martian-mono
    nerd-fonts.meslo-lg
    nerd-fonts.monaspace
    nerd-fonts.monofur
    nerd-fonts.monoid
    nerd-fonts.mononoki
    #    nerd-fonts.mplus
    nerd-fonts.noto
    nerd-fonts.open-dyslexic
    nerd-fonts.overpass
    nerd-fonts.profont
    nerd-fonts.proggy-clean-tt
    nerd-fonts.recursive-mono
    nerd-fonts.roboto-mono
    nerd-fonts.sauce-code-pro
    nerd-fonts.shure-tech-mono
    nerd-fonts.space-mono
    nerd-fonts.symbols-only
    nerd-fonts.terminess-ttf
    nerd-fonts.tinos
    nerd-fonts.ubuntu
    nerd-fonts.ubuntu-mono
    nerd-fonts.ubuntu-sans
    nerd-fonts.victor-mono
    nerd-fonts.zed-mono
    # netbird-ui
    nettools
    nfs-utils
    nftables
    nginx
    #    nil
    nix-du
    nixfmt
    nixfmt-tree
    nixos-artwork.wallpapers.stripes
    nixos-option
    nix-output-monitor
    nix-search-tv
    nix-top
    nix-tree
    nmap
    nodejs_20
    nordzy-cursor-theme
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-cjk-serif
    noto-fonts-color-emoji
    #    nrfutil
    ntfs3g
    numbat
    nushell
    #nvtopPackages.amd
    nwg-look
    #    ollama
    #ollama-rocm
    # openocd
    openocd
    openssl
    #    opentoonz
    #openvswitch
    p7zip
    pamixer
    #    paperless-ngx
    pass
    passExtensions.pass-otp
    pastel
    pavucontrol
    pciutils
    perf-tools
    picocom
    pinentry-curses
    #    planify
    #    plasma-theme-switcher
    # platformio
    # platformio-core
    playerctl
    podman
    podman-compose
    podman-desktop
    podman-tui
    #    popcorntime
    poppler-utils
    procs
    profont
    progress
    progress-tracker
    pstree
    pulseaudio
    pulsemixer
    pv
    pwgen
    pwru
    pw-volume
    # python310Packages.catboost
    # python310Packages.ipykernel
    # python310Packages.jupyter
    # python310Packages.jupyter-core
    # python310Packages.kaggle
    # python310Packages.lightgbm
    # python310Packages.matplotlib
    # python310Packages.notebook
    # python310Packages.numpy
    # python310Packages.pandas
    # python310Packages.pre-commit-hooks
    # python310Packages.requests
    # python310Packages.scikit-learn
    # python310Packages.seaborn
    # python310Packages.tensorboard
    # python310Packages.torchaudio
    # python310Packages.torchvision
    # python310Packages.torchWithRocm
    # python310Packages.tqdm
    # python310Packages.venvShellHook
    # python310Packages.wandb
    # python310Packages.xgboost
    # python311Full
    #python311Packages.matplotlib
    #python311Packages.numpy
    # python311Packages.pip
    #python311Packages.pip
    # python311Packages.pyserial
    # python311Packages.setuptools
    # python312Full
    # python312Packages.pip
    # python312Packages.pyserial
    # python312Packages.python
    # python312Packages.setuptools
    python313
    #python313Packages.smolagents
    #    python3Full
    pywal
    pywalfox-native
    qemu
    qmk-udev-rules
    qrencode
    #qt6.qtwayland
    quickemu
    racket
    ranger
    recutils
    rename
    #    rgp
    rio
    ripgrep
    # rocm
    # rocmPackages.hipblas
    # rocmPackages.hipsolver
    # rocmPackages.hipsparse
    # rocmPackages.llvm.bintools
    # rocmPackages.llvm.clang
    # rocmPackages.llvm.clang-tools-extra
    # rocmPackages.llvm.compiler-rt
    # rocmPackages.llvm.libc
    # rocmPackages.llvm.libcxx
    # rocmPackages.llvm.libcxxabi
    # rocmPackages.llvm.libunwind
    # rocmPackages.llvm.lld
    # rocmPackages.llvm.lldb
    # rocmPackages.llvm.llvm
    # rocmPackages.llvm.mlir
    # rocmPackages.llvm.openmp
    # rocmPackages.llvm.polly
    # rocmPackages.llvm.pstl
    # rocmPackages.llvm.rocmClangStdenv
    # rocmPackages.miopen
    # rocmPackages.miopengemm
    # rocmPackages.rccl
    # rocmPackages.rocalution
    # rocmPackages.rocgdb
    # rocmPackages.rocm-cmake
    # rocmPackages.rocm-comgr
    # rocmPackages.rocm-core
    # rocmPackages.rocm-device-libs
    # rocmPackages.rocm-docs-core
    # rocmPackages.rocminfo
    # rocmPackages.rocmlir
    # rocmPackages.rocmlir-rock
    # rocmPackages.rocm-runtime
    # rocmPackages.rocm-thunk
    # rocmPackages.rocprim
    # rocmPackages.rocsolver
    # rocmPackages.rocsparse
    rofi
    rr
    runc
    rustc
    rustup
    scrot
    sd
    simple-scan
    sioyek
    skopeo
    socat
    solo2-cli
    # sommelier
    #spacevim
    spice-gtk
    sqlite
    #    sqlitebrowser
    starship
    strace
    #streamlit
    sudo-font
    sway
    swayidle
    swaylock
    swaylock-effects
    synfigstudio
    systemctl-tui
    taglib
    taskwarrior3
    taskwarrior-tui
    teensy-udev-rules
    telescope
    termdown
    terraform-providers.dmacvicar_libvirt
    #terraform-providers.libvirt
    tesseract
    tig
    tio
    tmux
    tockloader
    tpm2-tools
    #    tpmmanager
    transmission_4
    transmission_4-gtk
    tree
    treesheets
    tree-sitter
    tree-sitter-grammars.tree-sitter-ada
    tree-sitter-grammars.tree-sitter-adl
    tree-sitter-grammars.tree-sitter-agda
    tree-sitter-grammars.tree-sitter-alloy
    tree-sitter-grammars.tree-sitter-amber
    tree-sitter-grammars.tree-sitter-astro
    tree-sitter-grammars.tree-sitter-awk
    tree-sitter-grammars.tree-sitter-bash
    tree-sitter-grammars.tree-sitter-bass
    tree-sitter-grammars.tree-sitter-beancount
    tree-sitter-grammars.tree-sitter-bibtex
    tree-sitter-grammars.tree-sitter-bicep
    tree-sitter-grammars.tree-sitter-bitbake
    tree-sitter-grammars.tree-sitter-blade
    tree-sitter-grammars.tree-sitter-blueprint
    tree-sitter-grammars.tree-sitter-bqn
    tree-sitter-grammars.tree-sitter-c
    tree-sitter-grammars.tree-sitter-caddyfile
    tree-sitter-grammars.tree-sitter-cairo
    tree-sitter-grammars.tree-sitter-capnp
    tree-sitter-grammars.tree-sitter-cel
    tree-sitter-grammars.tree-sitter-circom
    tree-sitter-grammars.tree-sitter-clarity
    tree-sitter-grammars.tree-sitter-clojure
    tree-sitter-grammars.tree-sitter-cmake
    tree-sitter-grammars.tree-sitter-comment
    tree-sitter-grammars.tree-sitter-commonlisp
    tree-sitter-grammars.tree-sitter-cpon
    tree-sitter-grammars.tree-sitter-cpp
    tree-sitter-grammars.tree-sitter-crystal
    tree-sitter-grammars.tree-sitter-c-sharp
    tree-sitter-grammars.tree-sitter-css
    tree-sitter-grammars.tree-sitter-csv
    tree-sitter-grammars.tree-sitter-cuda
    tree-sitter-grammars.tree-sitter-cue
    tree-sitter-grammars.tree-sitter-cylc
    tree-sitter-grammars.tree-sitter-d
    tree-sitter-grammars.tree-sitter-dart
    tree-sitter-grammars.tree-sitter-dbml
    tree-sitter-grammars.tree-sitter-debian
    tree-sitter-grammars.tree-sitter-devicetree
    tree-sitter-grammars.tree-sitter-dhall
    tree-sitter-grammars.tree-sitter-diff
    tree-sitter-grammars.tree-sitter-djot
    tree-sitter-grammars.tree-sitter-dockerfile
    tree-sitter-grammars.tree-sitter-dot
    tree-sitter-grammars.tree-sitter-dtd
    tree-sitter-grammars.tree-sitter-dunstrc
    tree-sitter-grammars.tree-sitter-earthfile
    tree-sitter-grammars.tree-sitter-edoc
    tree-sitter-grammars.tree-sitter-eex
    tree-sitter-grammars.tree-sitter-elisp
    tree-sitter-grammars.tree-sitter-elixir
    tree-sitter-grammars.tree-sitter-elm
    tree-sitter-grammars.tree-sitter-elvish
    tree-sitter-grammars.tree-sitter-embedded-template
    tree-sitter-grammars.tree-sitter-erlang
    tree-sitter-grammars.tree-sitter-esdl
    tree-sitter-grammars.tree-sitter-factor
    tree-sitter-grammars.tree-sitter-fennel
    tree-sitter-grammars.tree-sitter-fga
    tree-sitter-grammars.tree-sitter-fidl
    tree-sitter-grammars.tree-sitter-fish
    tree-sitter-grammars.tree-sitter-forth
    tree-sitter-grammars.tree-sitter-fortran
    tree-sitter-grammars.tree-sitter-fsharp
    tree-sitter-grammars.tree-sitter-gas
    tree-sitter-grammars.tree-sitter-gdscript
    tree-sitter-grammars.tree-sitter-gemini
    tree-sitter-grammars.tree-sitter-gherkin
    tree-sitter-grammars.tree-sitter-ghostty
    tree-sitter-grammars.tree-sitter-gitattributes
    tree-sitter-grammars.tree-sitter-gitcommit
    tree-sitter-grammars.tree-sitter-git-config
    tree-sitter-grammars.tree-sitter-gitignore
    tree-sitter-grammars.tree-sitter-git-rebase
    tree-sitter-grammars.tree-sitter-gleam
    tree-sitter-grammars.tree-sitter-glimmer
    tree-sitter-grammars.tree-sitter-glsl
    tree-sitter-grammars.tree-sitter-gn
    tree-sitter-grammars.tree-sitter-go
    tree-sitter-grammars.tree-sitter-godot-resource
    tree-sitter-grammars.tree-sitter-gomod
    tree-sitter-grammars.tree-sitter-go-template
    tree-sitter-grammars.tree-sitter-gotmpl
    tree-sitter-grammars.tree-sitter-gowork
    tree-sitter-grammars.tree-sitter-gpr
    tree-sitter-grammars.tree-sitter-graphql
    tree-sitter-grammars.tree-sitter-gren
    tree-sitter-grammars.tree-sitter-groovy
    tree-sitter-grammars.tree-sitter-hare
    tree-sitter-grammars.tree-sitter-haskell
    tree-sitter-grammars.tree-sitter-haskell-persistent
    tree-sitter-grammars.tree-sitter-hcl
    tree-sitter-grammars.tree-sitter-heex
    tree-sitter-grammars.tree-sitter-hjson
    tree-sitter-grammars.tree-sitter-hocon
    tree-sitter-grammars.tree-sitter-hoon
    tree-sitter-grammars.tree-sitter-hosts
    tree-sitter-grammars.tree-sitter-html
    tree-sitter-grammars.tree-sitter-htmldjango
    tree-sitter-grammars.tree-sitter-http
    tree-sitter-grammars.tree-sitter-hurl
    tree-sitter-grammars.tree-sitter-hyprlang
    tree-sitter-grammars.tree-sitter-iex
    tree-sitter-grammars.tree-sitter-ini
    tree-sitter-grammars.tree-sitter-ink
    tree-sitter-grammars.tree-sitter-inko
    tree-sitter-grammars.tree-sitter-janet-simple
    tree-sitter-grammars.tree-sitter-java
    tree-sitter-grammars.tree-sitter-javascript
    tree-sitter-grammars.tree-sitter-jinja2
    tree-sitter-grammars.tree-sitter-jjdescription
    tree-sitter-grammars.tree-sitter-jq
    tree-sitter-grammars.tree-sitter-jsdoc
    tree-sitter-grammars.tree-sitter-json
    tree-sitter-grammars.tree-sitter-json5
    tree-sitter-grammars.tree-sitter-jsonnet
    tree-sitter-grammars.tree-sitter-julia
    tree-sitter-grammars.tree-sitter-just
    tree-sitter-grammars.tree-sitter-kdl
    tree-sitter-grammars.tree-sitter-koka
    tree-sitter-grammars.tree-sitter-kotlin
    tree-sitter-grammars.tree-sitter-koto
    tree-sitter-grammars.tree-sitter-latex
    tree-sitter-grammars.tree-sitter-ld
    tree-sitter-grammars.tree-sitter-ldif
    tree-sitter-grammars.tree-sitter-lean
    tree-sitter-grammars.tree-sitter-ledger
    tree-sitter-grammars.tree-sitter-llvm
    tree-sitter-grammars.tree-sitter-llvm-mir
    tree-sitter-grammars.tree-sitter-log
    tree-sitter-grammars.tree-sitter-lpf
    tree-sitter-grammars.tree-sitter-lua
    tree-sitter-grammars.tree-sitter-luau
    tree-sitter-grammars.tree-sitter-mail
    tree-sitter-grammars.tree-sitter-make
    tree-sitter-grammars.tree-sitter-markdoc
    tree-sitter-grammars.tree-sitter-markdown
    tree-sitter-grammars.tree-sitter-markdown-inline
    tree-sitter-grammars.tree-sitter-matlab
    tree-sitter-grammars.tree-sitter-mermaid
    tree-sitter-grammars.tree-sitter-meson
    tree-sitter-grammars.tree-sitter-mojo
    tree-sitter-grammars.tree-sitter-move
    tree-sitter-grammars.tree-sitter-nasm
    tree-sitter-grammars.tree-sitter-netlinx
    tree-sitter-grammars.tree-sitter-nginx
    tree-sitter-grammars.tree-sitter-nickel
    tree-sitter-grammars.tree-sitter-nim
    tree-sitter-grammars.tree-sitter-nix
    tree-sitter-grammars.tree-sitter-norg
    tree-sitter-grammars.tree-sitter-norg-meta
    tree-sitter-grammars.tree-sitter-nu
    tree-sitter-grammars.tree-sitter-ocaml
    tree-sitter-grammars.tree-sitter-ocaml-interface
    tree-sitter-grammars.tree-sitter-odin
    tree-sitter-grammars.tree-sitter-ohm
    tree-sitter-grammars.tree-sitter-opencl
    tree-sitter-grammars.tree-sitter-openscad
    tree-sitter-grammars.tree-sitter-org
    tree-sitter-grammars.tree-sitter-org-nvim
    tree-sitter-grammars.tree-sitter-pascal
    tree-sitter-grammars.tree-sitter-passwd
    tree-sitter-grammars.tree-sitter-pem
    tree-sitter-grammars.tree-sitter-perl
    tree-sitter-grammars.tree-sitter-pest
    tree-sitter-grammars.tree-sitter-pgn
    tree-sitter-grammars.tree-sitter-php
    tree-sitter-grammars.tree-sitter-phpdoc
    tree-sitter-grammars.tree-sitter-php-only
    tree-sitter-grammars.tree-sitter-pioasm
    tree-sitter-grammars.tree-sitter-pkl
    tree-sitter-grammars.tree-sitter-po
    tree-sitter-grammars.tree-sitter-pod
    tree-sitter-grammars.tree-sitter-ponylang
    tree-sitter-grammars.tree-sitter-powershell
    tree-sitter-grammars.tree-sitter-prisma
    tree-sitter-grammars.tree-sitter-prolog
    tree-sitter-grammars.tree-sitter-properties
    tree-sitter-grammars.tree-sitter-proto
    tree-sitter-grammars.tree-sitter-prql
    tree-sitter-grammars.tree-sitter-pug
    tree-sitter-grammars.tree-sitter-purescript
    tree-sitter-grammars.tree-sitter-python
    tree-sitter-grammars.tree-sitter-ql
    tree-sitter-grammars.tree-sitter-ql-dbscheme
    tree-sitter-grammars.tree-sitter-qmljs
    tree-sitter-grammars.tree-sitter-query
    tree-sitter-grammars.tree-sitter-quint
    tree-sitter-grammars.tree-sitter-r
    tree-sitter-grammars.tree-sitter-razor
    tree-sitter-grammars.tree-sitter-readline
    tree-sitter-grammars.tree-sitter-regex
    tree-sitter-grammars.tree-sitter-rego
    tree-sitter-grammars.tree-sitter-rescript
    tree-sitter-grammars.tree-sitter-river
    tree-sitter-grammars.tree-sitter-robot
    tree-sitter-grammars.tree-sitter-ron
    tree-sitter-grammars.tree-sitter-rst
    tree-sitter-grammars.tree-sitter-ruby
    tree-sitter-grammars.tree-sitter-rust
    tree-sitter-grammars.tree-sitter-rust-format-args
    tree-sitter-grammars.tree-sitter-scala
    tree-sitter-grammars.tree-sitter-scheme
    tree-sitter-grammars.tree-sitter-scss
    tree-sitter-grammars.tree-sitter-slang
    tree-sitter-grammars.tree-sitter-slint
    tree-sitter-grammars.tree-sitter-smali
    tree-sitter-grammars.tree-sitter-smithy
    tree-sitter-grammars.tree-sitter-sml
    tree-sitter-grammars.tree-sitter-snakemake
    tree-sitter-grammars.tree-sitter-solidity
    tree-sitter-grammars.tree-sitter-sourcepawn
    tree-sitter-grammars.tree-sitter-spade
    tree-sitter-grammars.tree-sitter-sparql
    tree-sitter-grammars.tree-sitter-spicedb
    tree-sitter-grammars.tree-sitter-sql
    tree-sitter-grammars.tree-sitter-sshclientconfig
    tree-sitter-grammars.tree-sitter-strace
    tree-sitter-grammars.tree-sitter-supercollider
    tree-sitter-grammars.tree-sitter-surface
    tree-sitter-grammars.tree-sitter-svelte
    tree-sitter-grammars.tree-sitter-sway
    tree-sitter-grammars.tree-sitter-swift
    tree-sitter-grammars.tree-sitter-t32
    tree-sitter-grammars.tree-sitter-tablegen
    tree-sitter-grammars.tree-sitter-tact
    tree-sitter-grammars.tree-sitter-talon
    tree-sitter-grammars.tree-sitter-task
    tree-sitter-grammars.tree-sitter-tcl
    tree-sitter-grammars.tree-sitter-teal
    tree-sitter-grammars.tree-sitter-templ
    tree-sitter-grammars.tree-sitter-tera
    tree-sitter-grammars.tree-sitter-textproto
    tree-sitter-grammars.tree-sitter-thrift
    tree-sitter-grammars.tree-sitter-tiger
    tree-sitter-grammars.tree-sitter-tlaplus
    tree-sitter-grammars.tree-sitter-todotxt
    tree-sitter-grammars.tree-sitter-toml
    tree-sitter-grammars.tree-sitter-tsq
    tree-sitter-grammars.tree-sitter-tsx
    tree-sitter-grammars.tree-sitter-turtle
    tree-sitter-grammars.tree-sitter-twig
    tree-sitter-grammars.tree-sitter-typescript
    tree-sitter-grammars.tree-sitter-typespec
    tree-sitter-grammars.tree-sitter-typst
    tree-sitter-grammars.tree-sitter-uiua
    tree-sitter-grammars.tree-sitter-ungrammar
    tree-sitter-grammars.tree-sitter-unison
    tree-sitter-grammars.tree-sitter-uxntal
    tree-sitter-grammars.tree-sitter-v
    tree-sitter-grammars.tree-sitter-vala
    tree-sitter-grammars.tree-sitter-vento
    tree-sitter-grammars.tree-sitter-verilog
    tree-sitter-grammars.tree-sitter-vhdl
    tree-sitter-grammars.tree-sitter-vhs
    tree-sitter-grammars.tree-sitter-vim
    tree-sitter-grammars.tree-sitter-vue
    tree-sitter-grammars.tree-sitter-wast
    tree-sitter-grammars.tree-sitter-wat
    tree-sitter-grammars.tree-sitter-werk
    tree-sitter-grammars.tree-sitter-wesl
    tree-sitter-grammars.tree-sitter-wgsl
    tree-sitter-grammars.tree-sitter-wing
    tree-sitter-grammars.tree-sitter-wit
    tree-sitter-grammars.tree-sitter-wren
    tree-sitter-grammars.tree-sitter-xit
    tree-sitter-grammars.tree-sitter-xml
    tree-sitter-grammars.tree-sitter-xtc
    tree-sitter-grammars.tree-sitter-yaml
    tree-sitter-grammars.tree-sitter-yang
    tree-sitter-grammars.tree-sitter-yara
    tree-sitter-grammars.tree-sitter-yuck
    tree-sitter-grammars.tree-sitter-zig
    tuigreet
    udiskie
    unpaper
    unrar
    unzip
    up
    usbmuxd
    usbtop
    usbutils
    #ustreamer
    utterly-nord-plasma
    vanilla-dmz
    vhs
    via
    vimPlugins.accent-vim
    vimPlugins.ack-vim
    vimPlugins.acp
    vimPlugins.actions-preview-nvim
    vimPlugins.advanced-git-search-nvim
    vimPlugins.adwaita-nvim
    vimPlugins.aerial-nvim
    vimPlugins.agda-vim
    vimPlugins.agitator-nvim
    vimPlugins.ag-nvim
    vimPlugins.aider-nvim
    vimPlugins.airline
    vimPlugins.ai-vim
    vimPlugins.alabaster-nvim
    vimPlugins.alchemist-vim
    vimPlugins.ale
    vimPlugins.align
    vimPlugins.align-nvim
    vimPlugins.alpha-nvim
    vimPlugins.alternative
    vimPlugins.amp-nvim
    vimPlugins.animation-nvim
    vimPlugins.aniseed
    vimPlugins.ansible-vim
    vimPlugins.antonys-macro-repeater
    vimPlugins.arcanist-vim
    vimPlugins.argtextobj-vim
    vimPlugins.arrow-nvim
    vimPlugins.arshlib-nvim
    vimPlugins.artio-nvim
    vimPlugins.astrocore
    vimPlugins.astrolsp
    vimPlugins.astrotheme
    vimPlugins.astroui
    vimPlugins.asyncomplete-buffer-vim
    vimPlugins.asyncomplete-file-vim
    vimPlugins.asyncomplete-lsp-vim
    vimPlugins.asyncomplete-omni-vim
    vimPlugins.asyncomplete-tags-vim
    vimPlugins.asyncomplete-ultisnips-vim
    vimPlugins.asyncomplete-vim
    vimPlugins.asyncrun-vim
    vimPlugins.asynctasks-vim
    vimPlugins.async-vim
    vimPlugins.ats-vim
    vimPlugins.augment-vim
    vimPlugins.aurora
    vimPlugins.autoclose-nvim
    vimPlugins.auto-fix-return-nvim
    vimPlugins.auto-git-diff
    vimPlugins.auto-hlsearch-nvim
    vimPlugins.autolist-nvim
    vimPlugins.autoload_cscope-vim
    vimPlugins.auto-pairs
    vimPlugins.auto-save-nvim
    vimPlugins.autosave-nvim
    vimPlugins.auto-session
    vimPlugins.avante-nvim
    vimPlugins.a-vim
    vimPlugins.awesome-vim-colorschemes
    vimPlugins.aw-watcher-nvim
    vimPlugins.aw-watcher-vim
    vimPlugins.aylin-vim
    vimPlugins.ayu-vim
    vimPlugins.b64-nvim
    vimPlugins.baleia-nvim
    vimPlugins.bamboo-nvim
    vimPlugins.barbar-nvim
    vimPlugins.barbecue-nvim
    vimPlugins.base16-nvim
    vimPlugins.base16-vim
    vimPlugins.base46
    vimPlugins.bats
    vimPlugins.bats-vim
    vimPlugins.bat-vim
    vimPlugins.bclose-vim
    vimPlugins.better-escape-nvim
    vimPlugins.BetterLua-vim
    vimPlugins.bigfile-nvim
    vimPlugins.bitbake-vim
    vimPlugins.blame-nvim
    vimPlugins.blamer-nvim
    vimPlugins.blink-cmp
    vimPlugins.blink-cmp-avante
    vimPlugins.blink-cmp-conventional-commits
    vimPlugins.blink-cmp-copilot
    vimPlugins.blink-cmp-dictionary
    vimPlugins.blink-cmp-env
    vimPlugins.blink-cmp-git
    vimPlugins.blink-cmp-latex
    vimPlugins.blink-cmp-nixpkgs-maintainers
    vimPlugins.blink-cmp-npm-nvim
    vimPlugins.blink-cmp-spell
    vimPlugins.blink-cmp-tmux
    vimPlugins.blink-cmp-words
    vimPlugins.blink-cmp-yanky
    vimPlugins.blink-compat
    vimPlugins.blink-copilot
    vimPlugins.blink-emoji-nvim
    vimPlugins.blink-indent
    vimPlugins.blink-nerdfont-nvim
    vimPlugins.blink-pairs
    vimPlugins.blink-ripgrep-nvim
    vimPlugins.bloat-nvim
    vimPlugins.block-nvim
    vimPlugins.bluloco-nvim
    vimPlugins.boo-colorscheme-nvim
    vimPlugins.boole-nvim
    vimPlugins.bracey-vim
    vimPlugins.brainfuck-vim
    vimPlugins.bufdelete-nvim
    vimPlugins.bufexplorer
    vimPlugins.bufferize-vim
    vimPlugins.bufferline-nvim
    vimPlugins.bufjump-nvim
    vimPlugins.BufOnly
    vimPlugins.BufOnly-vim
    vimPlugins.bufresize-nvim
    vimPlugins.bullets-vim
    vimPlugins.calendar
    vimPlugins.calendar-vim
    vimPlugins.camelcasemotion
    vimPlugins.catppuccin-nvim
    vimPlugins.catppuccin-vim
    vimPlugins.caw
    vimPlugins.caw-vim
    vimPlugins.ccc-nvim
    vimPlugins.cellular-automaton-nvim
    vimPlugins.chad
    vimPlugins.chadtree
    vimPlugins.changeColorScheme-vim
    vimPlugins.ChatGPT-nvim
    vimPlugins.cheatsheet-nvim
    vimPlugins.CheckAttach
    vimPlugins.checkmate-nvim
    vimPlugins.ci_dark
    vimPlugins.cinnamon-nvim
    vimPlugins.circles-nvim
    vimPlugins.citruszest-nvim
    vimPlugins.clang_complete
    vimPlugins.clangd_extensions-nvim
    vimPlugins.claude-code-nvim
    vimPlugins.claudecode-nvim
    vimPlugins.claude-fzf-history-nvim
    vimPlugins.claude-fzf-nvim
    vimPlugins.clever-f-vim
    vimPlugins.clighter8
    vimPlugins.clipboard-image-nvim
    vimPlugins.cloak-nvim
    vimPlugins.close-buffers-vim
    vimPlugins.cmake-tools-nvim
    vimPlugins.cmdalias-vim
    vimPlugins.cmd-parser-nvim
    vimPlugins.cmp-ai
    vimPlugins.cmp-async-path
    vimPlugins.cmp-beancount
    vimPlugins.cmp-buffer
    vimPlugins.cmp-calc
    vimPlugins.cmp-clippy
    vimPlugins.cmp-cmdline
    vimPlugins.cmp-cmdline-history
    vimPlugins.cmp-conjure
    vimPlugins.cmp-conventionalcommits
    vimPlugins.cmp-copilot
    vimPlugins.cmp-ctags
    vimPlugins.cmp-dap
    vimPlugins.cmp-dictionary
    vimPlugins.cmp-digraphs
    vimPlugins.cmp-dotenv
    vimPlugins.cmp-emoji
    vimPlugins.cmp-fish
    vimPlugins.cmp-fuzzy-buffer
    vimPlugins.cmp-fuzzy-path
    vimPlugins.cmp-git
    vimPlugins.cmp-greek
    vimPlugins.cmp-latex-symbols
    vimPlugins.cmp-look
    vimPlugins.cmp_luasnip
    vimPlugins.cmp-neosnippet
    vimPlugins.cmp-nixpkgs-maintainers
    vimPlugins.cmp-npm
    vimPlugins.cmp-nvim-lsp
    vimPlugins.cmp-nvim-lsp-document-symbol
    vimPlugins.cmp-nvim-lsp-signature-help
    vimPlugins.cmp-nvim-lua
    vimPlugins.cmp-nvim-tags
    vimPlugins.cmp-nvim-ultisnips
    vimPlugins.cmp-omni
    vimPlugins.cmp-pandoc-nvim
    vimPlugins.cmp-pandoc-references
    vimPlugins.cmp-path
    vimPlugins.cmp-rg
    vimPlugins.cmp-snippy
    vimPlugins.cmp-spell
    vimPlugins.cmp-tabby
    vimPlugins.cmp-tabnine
    vimPlugins.cmp-tmux
    vimPlugins.cmp-treesitter
    vimPlugins.cmp-under-comparator
    vimPlugins.cmp-vim-lsp
    vimPlugins.cmp-vimtex
    vimPlugins.cmp-vimwiki-tags
    vimPlugins.cmp-vsnip
    vimPlugins.cmp_yanky
    vimPlugins.cmp-zsh
    vimPlugins.cobalt2-nvim
    vimPlugins.coc-basedpyright
    vimPlugins.coc-clangd
    vimPlugins.coc-clap
    vimPlugins.coc-cmake
    vimPlugins.coc-css
    vimPlugins.coc-denite
    vimPlugins.coc-diagnostic
    vimPlugins.coc-docker
    vimPlugins.coc-emmet
    vimPlugins.coc-eslint
    vimPlugins.coc-explorer
    vimPlugins.coc-flutter
    vimPlugins.coc-fzf
    vimPlugins.coc-git
    vimPlugins.coc-haxe
    vimPlugins.coc-highlight
    vimPlugins.coc-html
    vimPlugins.coc-java
    vimPlugins.coc-jest
    vimPlugins.coc-json
    vimPlugins.coc-lists
    vimPlugins.coc-lua
    vimPlugins.coc-markdownlint
    vimPlugins.coc-neco
    vimPlugins.coc-nginx
    vimPlugins.coc-nvim
    vimPlugins.coconut-vim
    vimPlugins.coc-pairs
    vimPlugins.coc-prettier
    vimPlugins.coc-pyright
    vimPlugins.coc-r-lsp
    vimPlugins.coc-rust-analyzer
    vimPlugins.coc-sh
    vimPlugins.coc-smartf
    vimPlugins.coc-snippets
    vimPlugins.coc-solargraph
    vimPlugins.coc-spell-checker
    vimPlugins.coc-sqlfluff
    vimPlugins.coc-stylelint
    vimPlugins.coc-svelte
    vimPlugins.coc-tabnine
    vimPlugins.coc-tailwindcss
    vimPlugins.coc-texlab
    vimPlugins.coc-toml
    vimPlugins.coc-vimlsp
    vimPlugins.coc-vimtex
    vimPlugins.coc-wxml
    vimPlugins.coc-yaml
    vimPlugins.coc-yank
    vimPlugins.codecompanion-history-nvim
    vimPlugins.codecompanion-lualine-nvim
    vimPlugins.codecompanion-nvim
    vimPlugins.codecompanion-spinner-nvim
    vimPlugins.codediff-nvim
    vimPlugins.codeium-nvim
    vimPlugins.codeium-vim
    vimPlugins.codesettings-nvim
    vimPlugins.codesnap-nvim
    vimPlugins.codewindow-nvim
    vimPlugins.codi-vim
    vimPlugins.coffee-script
    vimPlugins.coffeeScript
    vimPlugins.colibri-vim
    vimPlugins.colorbuddy-nvim
    vimPlugins.colorful-menu-nvim
    vimPlugins.colorful-winsep-nvim
    vimPlugins.colorizer
    vimPlugins.colorsamplerpack
    vimPlugins.colors-solarized
    vimPlugins.Colour-Sampler-Pack
    vimPlugins.Colour_Sampler_Pack
    vimPlugins.com-cloudedmountain-ide-neovim
    vimPlugins.comfy-line-numbers-nvim
    vimPlugins.command-t
    vimPlugins.command_T
    vimPlugins.commasemi-nvim
    vimPlugins.commentary
    vimPlugins.comment-box-nvim
    vimPlugins.comment-nvim
    vimPlugins.committia
    vimPlugins.committia-vim
    vimPlugins.compe-conjure
    vimPlugins.compe-latex-symbols
    vimPlugins.compe-tabnine
    vimPlugins.competitest-nvim
    vimPlugins.compe-zsh
    vimPlugins.compiler-explorer-nvim
    vimPlugins.compiler-nvim
    vimPlugins.completion-buffers
    vimPlugins.completion-nvim
    vimPlugins.completion-tabnine
    vimPlugins.concealedyank
    vimPlugins.concealedyank-vim
    vimPlugins.conflict-marker-vim
    vimPlugins.conform-nvim
    vimPlugins.conjure
    vimPlugins.conjure-nvim
    vimPlugins.contextfiles-nvim
    vimPlugins.context-filetype
    vimPlugins.context_filetype-vim
    vimPlugins.context-vim
    vimPlugins.CopilotChat-nvim
    vimPlugins.copilot-cmp
    vimPlugins.copilot-lsp
    vimPlugins.copilot-lua
    vimPlugins.copilot-lualine
    vimPlugins.copilot-vim
    vimPlugins.coq-artifacts
    vimPlugins.coq-lsp-nvim
    vimPlugins.coq_nvim
    vimPlugins.Coqtail
    vimPlugins.coq-thirdparty
    vimPlugins.coq-vim
    vimPlugins.cord-nvim
    vimPlugins.corePlugins
    vimPlugins.cornelis
    vimPlugins.Cosco
    vimPlugins.cosco-vim
    vimPlugins.cpsm
    vimPlugins.crates-nvim
    vimPlugins.csapprox
    vimPlugins.CSApprox
    vimPlugins.csharpls-extended-lsp-nvim
    vimPlugins.cspell-nvim
    vimPlugins.css_color_5056
    vimPlugins.csv
    vimPlugins.csvview-nvim
    vimPlugins.csv-vim
    vimPlugins.ctrlp
    vimPlugins.ctrlp-cmatcher
    vimPlugins.ctrlp-py-matcher
    vimPlugins.ctrlp-vim
    vimPlugins.ctrlp-z
    vimPlugins.cute-python
    vimPlugins.cutlass-nvim
    vimPlugins.cyberdream-nvim
    vimPlugins.cybu-nvim
    vimPlugins.d2-vim
    vimPlugins.dailies-nvim
    vimPlugins.darcubox-nvim
    vimPlugins.darkearth-nvim
    vimPlugins.dart-nvim
    vimPlugins.dart-vim-plugin
    vimPlugins.dashboard-nvim
    vimPlugins.dash-vim
    vimPlugins.ddc-filter-matcher_head
    vimPlugins.ddc-filter-sorter_rank
    vimPlugins.ddc-fuzzy
    vimPlugins.ddc-source-around
    vimPlugins.ddc-source-file
    vimPlugins.ddc-source-lsp
    vimPlugins.ddc-ui-native
    vimPlugins.ddc-ui-pum
    vimPlugins.ddc-vim
    vimPlugins.debugmaster-nvim
    vimPlugins.debugprint-nvim
    vimPlugins.deepwhite-nvim
    vimPlugins.defx-git
    vimPlugins.defx-icons
    vimPlugins.defx-nvim
    vimPlugins.delimitMate
    vimPlugins.demicolon-nvim
    vimPlugins.denite
    vimPlugins.denite-extra
    vimPlugins.denite-git
    vimPlugins.denite-nvim
    vimPlugins.denops-vim
    vimPlugins.deol-nvim
    vimPlugins.deoplete-clang
    vimPlugins.deoplete-dictionary
    vimPlugins.deoplete-fish
    vimPlugins.deoplete-github
    vimPlugins.deoplete-go
    vimPlugins.deoplete-greek
    vimPlugins.deoplete-jedi
    vimPlugins.deoplete-julia
    vimPlugins.deoplete-khard
    vimPlugins.deoplete-lsp
    vimPlugins.deoplete-notmuch
    vimPlugins.deoplete-nvim
    vimPlugins.deoplete-phpactor
    vimPlugins.deoplete-rust
    vimPlugins.deoplete-tabnine
    vimPlugins.deoplete-ternjs
    vimPlugins.deoplete-vim-lsp
    vimPlugins.deoplete-zsh
    vimPlugins.devdocs-nvim
    vimPlugins.devdocs-vim
    vimPlugins.dhall-vim
    vimPlugins.diagflow-nvim
    vimPlugins.diaglist-nvim
    vimPlugins.diagnostic-nvim
    vimPlugins.diagram-nvim
    vimPlugins.dial-nvim
    vimPlugins.diffview-nvim
    vimPlugins.dirbuf-nvim
    vimPlugins.direnv-vim
    vimPlugins.distant-nvim
    vimPlugins.doki-theme-vim
    vimPlugins.doom-one-nvim
    vimPlugins.dotnet-nvim
    vimPlugins.DoxygenToolkit-vim
    vimPlugins.dracula-nvim
    vimPlugins.dracula-vim
    vimPlugins.dressing-nvim
    vimPlugins.dropbar-nvim
    vimPlugins.earthly-vim
    vimPlugins.easy-align
    vimPlugins.easy-dotnet-nvim
    vimPlugins.easygit
    vimPlugins.easymotion
    vimPlugins.easyread-nvim
    vimPlugins.echodoc
    vimPlugins.echodoc-vim
    vimPlugins.ecolog-nvim
    vimPlugins.edge
    vimPlugins.edgedb-vim
    vimPlugins.edgy-nvim
    vimPlugins.editorconfig-nvim
    vimPlugins.editorconfig-vim
    vimPlugins.efmls-configs-nvim
    vimPlugins.eighties
    vimPlugins.elixir-tools-nvim
    vimPlugins.elm-vim
    vimPlugins.elvish-vim
    vimPlugins.embark-vim
    vimPlugins.emmet-vim
    vimPlugins.emodeline
    vimPlugins.endec-nvim
    vimPlugins.errormarker-vim
    vimPlugins.ethersync
    vimPlugins.eva01-vim
    vimPlugins.everforest
    vimPlugins.evergarden-nvim
    vimPlugins.executor-nvim
    vimPlugins.extradite
    vimPlugins.eyeliner-nvim
    vimPlugins.falcon
    vimPlugins.famous-quotes-nvim
    vimPlugins.far-vim
    vimPlugins.fastaction-nvim
    vimPlugins.faster-nvim
    vimPlugins.fastfold
    vimPlugins.faust-nvim
    vimPlugins.fcitx-vim
    vimPlugins.fennel-vim
    vimPlugins.fern-vim
    vimPlugins.ferret
    vimPlugins.fff-nvim
    vimPlugins.fidget-nvim
    vimPlugins.file-line
    vimPlugins.fileline-nvim
    vimPlugins.fine-cmdline-nvim
    vimPlugins.firenvim
    vimPlugins.FixCursorHold-nvim
    vimPlugins.flake8-vim
    vimPlugins.flash-nvim
    vimPlugins.flatten-nvim
    vimPlugins.fleet-theme-nvim
    vimPlugins.flit-nvim
    vimPlugins.floaterm
    vimPlugins.floating-input-nvim
    vimPlugins.float-preview-nvim
    vimPlugins.floobits-neovim
    vimPlugins.flow-nvim
    vimPlugins.fluent-vim
    vimPlugins.flutter-tools-nvim
    vimPlugins.focus-nvim
    vimPlugins.fold-preview-nvim
    vimPlugins.follow-md-links-nvim
    vimPlugins.formatter-nvim
    vimPlugins.forms
    vimPlugins.fortune-nvim
    vimPlugins.freeze-nvim
    vimPlugins.friendly-snippets
    vimPlugins.FTerm-nvim
    vimPlugins.fugit2-nvim
    vimPlugins.fugitive
    vimPlugins.fugitive-gitlab-vim
    vimPlugins.futhark-vim
    vimPlugins.fuzzy-nvim
    vimPlugins.fwatch-nvim
    vimPlugins.fyler-nvim
    vimPlugins.fzf-checkout-vim
    vimPlugins.fzf-hoogle-vim
    vimPlugins.fzf-lsp-nvim
    vimPlugins.fzf-lua
    vimPlugins.fzf-vim
    vimPlugins.fzf-wrapper
    vimPlugins.fzfWrapper
    vimPlugins.galaxyline-nvim
    vimPlugins.gbprod-nord
    vimPlugins.gdscript-extended-lsp-nvim
    vimPlugins.gen-nvim
    vimPlugins.gen_tags-vim
    vimPlugins.gentoo-syntax
    vimPlugins.ghcid
    vimPlugins.ghcmod
    vimPlugins.ghc-mod-vim
    vimPlugins.ghcmod-vim
    vimPlugins.gh-nvim
    vimPlugins.gina-vim
    vimPlugins.Gist
    vimPlugins.git-blame-nvim
    vimPlugins.git-conflict-nvim
    vimPlugins.git-dashboard-nvim
    vimPlugins.gitgutter
    vimPlugins.github-nvim-theme
    vimPlugins.gitignore-nvim
    vimPlugins.gitignore-vim
    vimPlugins.gitlab-vim
    vimPlugins.gitlinker-nvim
    vimPlugins.git-messenger-vim
    vimPlugins.gitportal-nvim
    vimPlugins.git-prompt-string-lualine-nvim
    vimPlugins.gitsigns-nvim
    vimPlugins.gitv
    vimPlugins.git-worktree-nvim
    vimPlugins.glance-nvim
    vimPlugins.glow-nvim
    vimPlugins.godbolt-nvim
    vimPlugins.golden-ratio
    vimPlugins.go-nvim
    vimPlugins.gotests-vim
    vimPlugins.goto-preview
    vimPlugins.goyo
    vimPlugins.goyo-vim
    vimPlugins.GPTModels-nvim
    vimPlugins.grammar-guard-nvim
    vimPlugins.graphviz-vim
    vimPlugins.grapple-nvim
    vimPlugins.gruber-darker-nvim
    vimPlugins.grug-far-nvim
    vimPlugins.gruvbox
    vimPlugins.gruvbox-alabaster-nvim
    vimPlugins.gruvbox-baby
    vimPlugins.gruvbox-community
    vimPlugins.gruvbox-flat-nvim
    vimPlugins.gruvbox-material
    vimPlugins.gruvbox-material-nvim
    vimPlugins.gruvbox-nvim
    vimPlugins.guard-collection
    vimPlugins.guard-nvim
    vimPlugins.guess-indent-nvim
    vimPlugins.guihua-lua
    vimPlugins.gundo
    vimPlugins.Gundo
    vimPlugins.gundo-vim
    vimPlugins.gv-vim
    vimPlugins.gx-nvim
    vimPlugins.hardhat-nvim
    vimPlugins.hardtime-nvim
    vimPlugins.hare-vim
    vimPlugins.harpoon
    vimPlugins.harpoon2
    vimPlugins.haskellconceal
    vimPlugins.haskellConceal
    vimPlugins.haskellConcealPlus
    vimPlugins.haskell-scope-highlighting-nvim
    vimPlugins.haskell-snippets-nvim
    vimPlugins.haskell-tools-nvim
    vimPlugins.haskell-vim
    vimPlugins.haskell-with-unicode-vim
    vimPlugins.hasksyn
    vimPlugins.headhunter-nvim
    vimPlugins.headlines-nvim
    vimPlugins.heirline-nvim
    vimPlugins.helm-ls-nvim
    vimPlugins.helpview-nvim
    vimPlugins.hex-nvim
    vimPlugins.hier
    vimPlugins.highlight-undo-nvim
    vimPlugins.himalaya-vim
    vimPlugins.hiPairs
    vimPlugins.hlargs-nvim
    vimPlugins.hlchunk-nvim
    vimPlugins.hlint-refactor
    vimPlugins.hlint-refactor-vim
    vimPlugins.hmts-nvim
    vimPlugins.hologram-nvim
    vimPlugins.hoogle
    vimPlugins.Hoogle
    vimPlugins.hoon-vim
    vimPlugins.hop-nvim
    vimPlugins.hotpot-nvim
    vimPlugins.houdini-nvim
    vimPlugins.hover-nvim
    vimPlugins.html5-vim
    vimPlugins.hunk-nvim
    vimPlugins.hurl
    vimPlugins.hurl-nvim
    vimPlugins.hydra-nvim
    vimPlugins.i3config-vim
    vimPlugins.iceberg-vim
    vimPlugins.idris2-nvim
    vimPlugins.idris2-vim
    vimPlugins.idris-vim
    vimPlugins.image-nvim
    vimPlugins.img-clip-nvim
    vimPlugins.impatient-nvim
    vimPlugins.Improved-AnsiEsc
    vimPlugins.improved-search-nvim
    vimPlugins.im-select-nvim
    vimPlugins.incline-nvim
    vimPlugins.increment-activator
    vimPlugins.inc-rename-nvim
    vimPlugins.incsearch-easymotion-vim
    vimPlugins.incsearch-vim
    vimPlugins.indent-blankline-nvim
    vimPlugins.indent-blankline-nvim-lua
    vimPlugins.indentLine
    vimPlugins.indent-o-matic
    vimPlugins.indent-tools-nvim
    vimPlugins.inkpot
    vimPlugins.instant-nvim
    vimPlugins.intellitab-nvim
    vimPlugins.intero-neovim
    vimPlugins.investigate-vim
    vimPlugins.Ionide-vim
    vimPlugins.iosvkem
    vimPlugins.ipython
    vimPlugins.ir_black
    vimPlugins.iron-nvim
    vimPlugins.is-vim
    vimPlugins.iswap-nvim
    vimPlugins.jdaddy-vim
    vimPlugins.jdd-nvim
    vimPlugins.jedi-vim
    vimPlugins.jellybeans-nvim
    vimPlugins.jellybeans-vim
    vimPlugins.Jenkinsfile-vim-syntax
    vimPlugins.jinja-vim
    vimPlugins.jj-nvim
    vimPlugins.jq-vim
    vimPlugins.jsonc-vim
    vimPlugins.jsonfly-nvim
    vimPlugins.jule-nvim
    vimPlugins.julia-vim
    vimPlugins.jupyter-api-nvim
    vimPlugins.jupytext-nvim
    vimPlugins.kanagawa-nvim
    vimPlugins.kanagawa-paper-nvim
    vimPlugins.kanso-nvim
    vimPlugins.kdl-vim
    vimPlugins.keymap-layer-nvim
    vimPlugins.kitty-scrollback-nvim
    vimPlugins.kiwi-nvim
    vimPlugins.kmonad-vim
    vimPlugins.knap
    vimPlugins.koda-nvim
    vimPlugins.kommentary
    vimPlugins.kotlin-vim
    vimPlugins.kulala-nvim
    vimPlugins.lackluster-nvim
    vimPlugins.lalrpop-vim
    vimPlugins.langmapper-nvim
    vimPlugins.LanguageClient-neovim
    vimPlugins.LanguageTool-nvim
    vimPlugins.last256
    vimPlugins.latex-box
    vimPlugins.latex-live-preview
    vimPlugins.lazydev-nvim
    vimPlugins.lazydocker-nvim
    vimPlugins.lazygit-nvim
    vimPlugins.lazyjj-nvim
    vimPlugins.lazy-lsp-nvim
    vimPlugins.lazy-nvim
    vimPlugins.LazyVim
    vimPlugins.LeaderF
    vimPlugins.lean-nvim
    vimPlugins.lean-vim
    vimPlugins.leap-ast-nvim
    vimPlugins.leap-nvim
    vimPlugins.leetcode-nvim
    vimPlugins.legendary-nvim
    vimPlugins.lensline-nvim
    vimPlugins.lens-vim
    vimPlugins.lessspace-vim
    vimPlugins.lexima-vim
    vimPlugins.lf-nvim
    vimPlugins.lf-vim
    vimPlugins.lh-brackets
    vimPlugins.lh-vim-lib
    vimPlugins.LibDeflate-nvim
    vimPlugins.lightline-ale
    vimPlugins.lightline-bufferline
    vimPlugins.lightline-gruvbox-vim
    vimPlugins.lightline-lsp
    vimPlugins.lightline-vim
    vimPlugins.lightspeed-nvim
    vimPlugins.lightswitch-nvim
    vimPlugins.limelight-vim
    vimPlugins.linediff-vim
    vimPlugins.lingua-franca-vim
    vimPlugins.lir-nvim
    vimPlugins.lispdocs-nvim
    vimPlugins.litee-calltree-nvim
    vimPlugins.litee-filetree-nvim
    vimPlugins.litee-nvim
    vimPlugins.litee-symboltree-nvim
    vimPlugins.live-command-nvim
    vimPlugins.live-preview-nvim
    vimPlugins.live-rename-nvim
    vimPlugins.live-share-nvim
    vimPlugins.llama-vim
    vimPlugins.llm-nvim
    vimPlugins.lsp-colors-nvim
    vimPlugins.lspcontainers-nvim
    vimPlugins.lspecho-nvim
    vimPlugins.lsp_extensions-nvim
    vimPlugins.lsp-format-modifications-nvim
    vimPlugins.lsp-format-nvim
    vimPlugins.lsp-inlayhints-nvim
    vimPlugins.lspkind-nvim
    vimPlugins.lsp_lines-nvim
    vimPlugins.lsp-overloads-nvim
    vimPlugins.lsp-progress-nvim
    vimPlugins.lsp-rooter-nvim
    vimPlugins.lspsaga-nvim
    vimPlugins.lsp_signature-nvim
    vimPlugins.lsp-status-nvim
    vimPlugins.lsp-zero-nvim
    vimPlugins.ltex_extra-nvim
    vimPlugins.lua-async
    vimPlugins.lua-async-await
    vimPlugins.lualine-lsp-progress
    vimPlugins.lualine-nvim
    vimPlugins.luasnip
    vimPlugins.luasnip-latex-snippets-nvim
    vimPlugins.LuaSnip-snippets-nvim
    vimPlugins.luatab-nvim
    vimPlugins.luau-lsp-nvim
    vimPlugins.lush-nvim
    vimPlugins.lushtags
    vimPlugins.luvit-meta
    vimPlugins.lze
    vimPlugins.lzextras
    vimPlugins.lz-n
    vimPlugins.lzn-auto-require
    vimPlugins.magma-nvim
    vimPlugins.magma-nvim-goose
    vimPlugins.maktaba
    vimPlugins.maple-nvim
    vimPlugins.markdoc-nvim
    vimPlugins.markdown-nvim
    vimPlugins.markdown-preview-nvim
    vimPlugins.markid
    vimPlugins.mark-radar-nvim
    vimPlugins.marks-nvim
    vimPlugins.markview-nvim
    vimPlugins.mason-lspconfig-nvim
    vimPlugins.mason-null-ls-nvim
    vimPlugins.mason-nvim
    vimPlugins.mason-nvim-dap-nvim
    vimPlugins.mason-tool-installer-nvim
    vimPlugins.matchit-zip
    vimPlugins.MatchTagAlways
    vimPlugins.material-nvim
    vimPlugins.material-vim
    vimPlugins.mattn-calendar-vim
    vimPlugins.mayansmoke
    vimPlugins.mcphub-nvim
    vimPlugins.mediawiki-vim
    vimPlugins.melange-nvim
    vimPlugins.meson
    vimPlugins.messenger-nvim
    vimPlugins.miasma-nvim
    vimPlugins.middleclass
    vimPlugins.midnight-nvim
    vimPlugins.mind-nvim
    vimPlugins.mini-ai
    vimPlugins.mini-align
    vimPlugins.mini-animate
    vimPlugins.mini-base16
    vimPlugins.mini-basics
    vimPlugins.mini-bracketed
    vimPlugins.mini-bufremove
    vimPlugins.mini-clue
    vimPlugins.mini-cmdline
    vimPlugins.mini-colors
    vimPlugins.mini-comment
    vimPlugins.mini-completion
    vimPlugins.mini-cursorword
    vimPlugins.mini-deps
    vimPlugins.mini-diff
    vimPlugins.mini-doc
    vimPlugins.mini-extra
    vimPlugins.mini-files
    vimPlugins.mini-fuzzy
    vimPlugins.mini-git
    vimPlugins.mini-hipatterns
    vimPlugins.mini-hues
    vimPlugins.mini-icons
    vimPlugins.mini-indentscope
    vimPlugins.mini-jump
    vimPlugins.mini-jump2d
    vimPlugins.mini-keymap
    vimPlugins.mini-map
    vimPlugins.minimap-vim
    vimPlugins.mini-misc
    vimPlugins.mini-move
    vimPlugins.mini-notify
    vimPlugins.mini-nvim
    vimPlugins.mini-operators
    vimPlugins.mini-pairs
    vimPlugins.mini-pick
    vimPlugins.mini-sessions
    vimPlugins.mini-snippets
    vimPlugins.mini-splitjoin
    vimPlugins.mini-starter
    vimPlugins.mini-statusline
    vimPlugins.mini-surround
    vimPlugins.mini-tabline
    vimPlugins.mini-test
    vimPlugins.mini-trailspace
    vimPlugins.mini-visits
    vimPlugins.minuet-ai-nvim
    vimPlugins.mkdir-nvim
    vimPlugins.mkdnflow-nvim
    vimPlugins.mkdx
    vimPlugins.model-nvim
    vimPlugins.modicator-nvim
    vimPlugins.modus-themes-nvim
    vimPlugins.molokai
    vimPlugins.molten-nvim
    vimPlugins.monaspace-nvim
    vimPlugins.monokai-pro-nvim
    vimPlugins.moonlight-nvim
    vimPlugins.moonscript-vim
    vimPlugins.moveline-nvim
    vimPlugins.mru
    vimPlugins.multicursor-nvim
    vimPlugins.multicursors-nvim
    vimPlugins.multiple-cursors
    vimPlugins.muren-nvim
    vimPlugins.nabla-nvim
    vimPlugins.Navigator-nvim
    vimPlugins.ncm2
    vimPlugins.ncm2-bufword
    vimPlugins.ncm2-cssomni
    vimPlugins.ncm2-dictionary
    vimPlugins.ncm2-github
    vimPlugins.ncm2-html-subscope
    vimPlugins.ncm2-jedi
    vimPlugins.ncm2-markdown-subscope
    vimPlugins.ncm2-neoinclude
    vimPlugins.ncm2-neosnippet
    vimPlugins.ncm2-path
    vimPlugins.ncm2-syntax
    vimPlugins.ncm2-tagprefix
    vimPlugins.ncm2-tmux
    vimPlugins.ncm2-ultisnips
    vimPlugins.ncm2-vim
    vimPlugins.neco-ghc
    vimPlugins.necoGhc
    vimPlugins.neco-look
    vimPlugins.neco-syntax
    vimPlugins.neco-vim
    vimPlugins.neocomplete
    vimPlugins.neocomplete-vim
    vimPlugins.neoconf-nvim
    vimPlugins.neocord
    vimPlugins.neodark-vim
    vimPlugins.neodev-nvim
    vimPlugins.neoformat
    vimPlugins.neogen
    vimPlugins.neogit
    vimPlugins.neoinclude
    vimPlugins.neoinclude-vim
    vimPlugins.neomake
    vimPlugins.neomodern-nvim
    vimPlugins.neomru
    vimPlugins.neomru-vim
    vimPlugins.neomutt-vim
    vimPlugins.neon
    vimPlugins.neorepl-nvim
    vimPlugins.neorg
    vimPlugins.neorg-interim-ls
    vimPlugins.neorg-telescope
    vimPlugins.neoscroll-nvim
    vimPlugins.neosnippet
    vimPlugins.neosnippet-snippets
    vimPlugins.neosnippet-vim
    vimPlugins.NeoSolarized
    vimPlugins.neoterm
    vimPlugins.neotest
    vimPlugins.neotest-bash
    vimPlugins.neotest-ctest
    vimPlugins.neotest-dart
    vimPlugins.neotest-deno
    vimPlugins.neotest-dotnet
    vimPlugins.neotest-elixir
    vimPlugins.neotest-foundry
    vimPlugins.neotest-go
    vimPlugins.neotest-golang
    vimPlugins.neotest-gradle
    vimPlugins.neotest-gtest
    vimPlugins.neotest-haskell
    vimPlugins.neotest-java
    vimPlugins.neotest-jest
    vimPlugins.neotest-minitest
    vimPlugins.neotest-mocha
    vimPlugins.neotest-pest
    vimPlugins.neotest-phpunit
    vimPlugins.neotest-playwright
    vimPlugins.neotest-plenary
    vimPlugins.neotest-python
    vimPlugins.neotest-rspec
    vimPlugins.neotest-rust
    vimPlugins.neotest-scala
    vimPlugins.neotest-testthat
    vimPlugins.neotest-vitest
    vimPlugins.neotest-zig
    vimPlugins.neo-tree-nvim
    vimPlugins.neovim-ayu
    vimPlugins.neovim-fuzzy
    vimPlugins.neovim-sensible
    vimPlugins.neovim-tips
    vimPlugins.neovim-trunk
    vimPlugins.neoyank-vim
    vimPlugins.nerdcommenter
    vimPlugins.nerdtree
    vimPlugins.nerdtree-git-plugin
    vimPlugins.nerdy-nvim
    vimPlugins.netman-nvim
    vimPlugins.netrw-nvim
    vimPlugins.neuron-vim
    vimPlugins.nfnl
    vimPlugins.nginx-vim
    vimPlugins.ng-nvim
    vimPlugins.nidhogg-nvim
    vimPlugins.nightfly
    vimPlugins.nightfox-nvim
    vimPlugins.nightly-nvim
    vimPlugins.night-owl-nvim
    vimPlugins.nim-vim
    vimPlugins.nix-develop-nvim
    vimPlugins.nlsp-settings-nvim
    vimPlugins.nnn-vim
    vimPlugins.no-clown-fiesta-nvim
    vimPlugins.noctis-nvim
    vimPlugins.noice-nvim
    vimPlugins.no-neck-pain-nvim
    vimPlugins.none-ls-nvim
    vimPlugins.nordic-nvim
    vimPlugins.nord-nvim
    vimPlugins.nord-vim
    vimPlugins.NotebookNavigator-nvim
    vimPlugins.notifier-nvim
    vimPlugins.notmuch-vim
    vimPlugins.NrrwRgn
    vimPlugins.nterm-nvim
    vimPlugins.nui-nvim
    vimPlugins.null-ls-nvim
    vimPlugins.numb-nvim
    vimPlugins.nvchad
    vimPlugins.nvchad-ui
    vimPlugins.nvcode-color-schemes-vim
    vimPlugins.nvim-ale-diagnostic
    vimPlugins.nvim-autopairs
    vimPlugins.nvim-bacon
    vimPlugins.nvim-base16
    vimPlugins.nvim-biscuits
    vimPlugins.nvim-bqf
    vimPlugins.nvim-bufdel
    vimPlugins.nvim-cmp
    vimPlugins.nvim-cm-racer
    vimPlugins.nvim-code-action-menu
    vimPlugins.nvim-cokeline
    vimPlugins.nvim-colorizer-lua
    vimPlugins.nvim-comment
    vimPlugins.nvim-compe
    vimPlugins.nvim-completion-manager
    vimPlugins.nvim-config-local
    vimPlugins.nvim_context_vt
    vimPlugins.nvim-coverage
    vimPlugins.nvim-cursorline
    vimPlugins.nvim-dap
    vimPlugins.nvim-dap-cortex-debug
    vimPlugins.nvim-dap-go
    vimPlugins.nvim-dap-lldb
    vimPlugins.nvim-dap-python
    vimPlugins.nvim-dap-rego
    vimPlugins.nvim-dap-rr
    vimPlugins.nvim-dap-ui
    vimPlugins.nvim-dap-view
    vimPlugins.nvim-dap-virtual-text
    vimPlugins.nvim-dap-vscode-js
    vimPlugins.nvim-dbee
    vimPlugins.nvimdev-nvim
    vimPlugins.nvim-docs-view
    vimPlugins.nvim-early-retirement
    vimPlugins.nvim-expand-expr
    vimPlugins.nvim-FeMaco-lua
    vimPlugins.nvim-fzf
    vimPlugins.nvim-fzf-commands
    vimPlugins.nvim-gdb
    vimPlugins.nvim-genghis
    vimPlugins.nvim-gomove
    vimPlugins.nvim-highlight-colors
    vimPlugins.nvim-highlite
    vimPlugins.nvim-hlslens
    vimPlugins.nvim-hs-vim
    vimPlugins.nvim-impairative
    vimPlugins.nvim-java
    vimPlugins.nvim-java-core
    vimPlugins.nvim-java-dap
    vimPlugins.nvim-java-refactor
    vimPlugins.nvim-java-test
    vimPlugins.nvim-jdtls
    vimPlugins.nvim-jqx
    vimPlugins.nvim-julia-autotest
    vimPlugins.nvim-k8s-crd
    vimPlugins.nvim-lastplace
    vimPlugins.nvim-lightbulb
    vimPlugins.nvim-lightline-lsp
    vimPlugins.nvim-lilypond-suite
    vimPlugins.nvim-lint
    vimPlugins.nvim-lspconfig
    vimPlugins.nvim-lsp-file-operations
    vimPlugins.nvim-lsp-notify
    vimPlugins.nvim-lsp-ts-utils
    vimPlugins.nvim-lsputils
    vimPlugins.nvim-luadev
    vimPlugins.nvim-lua-gf
    vimPlugins.nvim-luapad
    vimPlugins.nvim-metals
    vimPlugins.nvim-moonwalk
    vimPlugins.nvim-navbuddy
    vimPlugins.nvim-navic
    vimPlugins.nvim-neoclip-lua
    vimPlugins.nvim-next
    vimPlugins.nvim-nio
    vimPlugins.nvim-nonicons
    vimPlugins.nvim-notify
    vimPlugins.nvim-nu
    vimPlugins.nvim-numbertoggle
    vimPlugins.nvim-origami
    vimPlugins.nvim-osc52
    vimPlugins.nvim-paredit
    vimPlugins.nvim-parinfer
    vimPlugins.nvim-peekup
    vimPlugins.nvim-pqf
    vimPlugins.nvim-remote-containers
    vimPlugins.nvim-rename-state
    vimPlugins.nvim-rg
    vimPlugins.nvim-rip-substitute
    vimPlugins.nvim-scissors
    vimPlugins.nvim-scrollbar
    vimPlugins.nvim-scrollview
    vimPlugins.nvim-search-and-replace
    vimPlugins.nvim-silicon
    vimPlugins.nvim-snippets
    vimPlugins.nvim-snippy
    vimPlugins.nvim-solarized-lua
    vimPlugins.nvim-sops
    vimPlugins.nvim-spectre
    vimPlugins.nvim-spider
    vimPlugins.nvim-surround
    vimPlugins.nvim-teal-maker
    vimPlugins.nvim-terminal-lua
    vimPlugins.nvim-test
    vimPlugins.nvim-tinygit
    vimPlugins.nvim-tree-lua
    vimPlugins.nvim-treesitter
    vimPlugins.nvim-treesitter-context
    vimPlugins.nvim-treesitter-endwise
    vimPlugins.nvim-treesitter-legacy
    vimPlugins.nvim-treesitter-locals
    vimPlugins.nvim-treesitter-pairs
    vimPlugins.nvim-treesitter-parsers.ada
    vimPlugins.nvim-treesitter-parsers.agda
    vimPlugins.nvim-treesitter-parsers.angular
    vimPlugins.nvim-treesitter-parsers.apex
    vimPlugins.nvim-treesitter-parsers.arduino
    vimPlugins.nvim-treesitter-parsers.asm
    vimPlugins.nvim-treesitter-parsers.astro
    vimPlugins.nvim-treesitter-parsers.authzed
    vimPlugins.nvim-treesitter-parsers.awk
    vimPlugins.nvim-treesitter-parsers.bash
    vimPlugins.nvim-treesitter-parsers.bass
    vimPlugins.nvim-treesitter-parsers.beancount
    vimPlugins.nvim-treesitter-parsers.bibtex
    vimPlugins.nvim-treesitter-parsers.bicep
    vimPlugins.nvim-treesitter-parsers.bitbake
    vimPlugins.nvim-treesitter-parsers.blade
    vimPlugins.nvim-treesitter-parsers.bp
    vimPlugins.nvim-treesitter-parsers.bpftrace
    vimPlugins.nvim-treesitter-parsers.brightscript
    vimPlugins.nvim-treesitter-parsers.c
    vimPlugins.nvim-treesitter-parsers.c3
    vimPlugins.nvim-treesitter-parsers.caddy
    vimPlugins.nvim-treesitter-parsers.cairo
    vimPlugins.nvim-treesitter-parsers.capnp
    vimPlugins.nvim-treesitter-parsers.chatito
    vimPlugins.nvim-treesitter-parsers.circom
    vimPlugins.nvim-treesitter-parsers.clojure
    vimPlugins.nvim-treesitter-parsers.cmake
    vimPlugins.nvim-treesitter-parsers.comment
    vimPlugins.nvim-treesitter-parsers.commonlisp
    vimPlugins.nvim-treesitter-parsers.cooklang
    vimPlugins.nvim-treesitter-parsers.corn
    vimPlugins.nvim-treesitter-parsers.cpon
    vimPlugins.nvim-treesitter-parsers.cpp
    vimPlugins.nvim-treesitter-parsers.c_sharp
    vimPlugins.nvim-treesitter-parsers.css
    vimPlugins.nvim-treesitter-parsers.csv
    vimPlugins.nvim-treesitter-parsers.cuda
    vimPlugins.nvim-treesitter-parsers.cue
    vimPlugins.nvim-treesitter-parsers.cylc
    vimPlugins.nvim-treesitter-parsers.d
    vimPlugins.nvim-treesitter-parsers.dart
    vimPlugins.nvim-treesitter-parsers.desktop
    vimPlugins.nvim-treesitter-parsers.devicetree
    vimPlugins.nvim-treesitter-parsers.dhall
    vimPlugins.nvim-treesitter-parsers.diff
    vimPlugins.nvim-treesitter-parsers.disassembly
    vimPlugins.nvim-treesitter-parsers.djot
    vimPlugins.nvim-treesitter-parsers.dockerfile
    vimPlugins.nvim-treesitter-parsers.dot
    vimPlugins.nvim-treesitter-parsers.doxygen
    vimPlugins.nvim-treesitter-parsers.dtd
    vimPlugins.nvim-treesitter-parsers.earthfile
    vimPlugins.nvim-treesitter-parsers.ebnf
    vimPlugins.nvim-treesitter-parsers.editorconfig
    vimPlugins.nvim-treesitter-parsers.eds
    vimPlugins.nvim-treesitter-parsers.eex
    vimPlugins.nvim-treesitter-parsers.elixir
    vimPlugins.nvim-treesitter-parsers.elm
    vimPlugins.nvim-treesitter-parsers.elsa
    vimPlugins.nvim-treesitter-parsers.elvish
    vimPlugins.nvim-treesitter-parsers.embedded_template
    vimPlugins.nvim-treesitter-parsers.enforce
    vimPlugins.nvim-treesitter-parsers.erlang
    vimPlugins.nvim-treesitter-parsers.facility
    vimPlugins.nvim-treesitter-parsers.faust
    vimPlugins.nvim-treesitter-parsers.fennel
    vimPlugins.nvim-treesitter-parsers.fidl
    vimPlugins.nvim-treesitter-parsers.firrtl
    vimPlugins.nvim-treesitter-parsers.fish
    vimPlugins.nvim-treesitter-parsers.foam
    vimPlugins.nvim-treesitter-parsers.forth
    vimPlugins.nvim-treesitter-parsers.fortran
    vimPlugins.nvim-treesitter-parsers.fsh
    vimPlugins.nvim-treesitter-parsers.fsharp
    vimPlugins.nvim-treesitter-parsers.func
    vimPlugins.nvim-treesitter-parsers.gap
    vimPlugins.nvim-treesitter-parsers.gaptst
    vimPlugins.nvim-treesitter-parsers.gdscript
    vimPlugins.nvim-treesitter-parsers.gdshader
    vimPlugins.nvim-treesitter-parsers.gitattributes
    vimPlugins.nvim-treesitter-parsers.gitcommit
    vimPlugins.nvim-treesitter-parsers.git_config
    vimPlugins.nvim-treesitter-parsers.gitignore
    vimPlugins.nvim-treesitter-parsers.git_rebase
    vimPlugins.nvim-treesitter-parsers.gleam
    vimPlugins.nvim-treesitter-parsers.glimmer
    vimPlugins.nvim-treesitter-parsers.glimmer_javascript
    vimPlugins.nvim-treesitter-parsers.glimmer_typescript
    vimPlugins.nvim-treesitter-parsers.glsl
    vimPlugins.nvim-treesitter-parsers.gn
    vimPlugins.nvim-treesitter-parsers.gnuplot
    vimPlugins.nvim-treesitter-parsers.go
    vimPlugins.nvim-treesitter-parsers.goctl
    vimPlugins.nvim-treesitter-parsers.godot_resource
    vimPlugins.nvim-treesitter-parsers.gomod
    vimPlugins.nvim-treesitter-parsers.gosum
    vimPlugins.nvim-treesitter-parsers.gotmpl
    vimPlugins.nvim-treesitter-parsers.gowork
    vimPlugins.nvim-treesitter-parsers.gpg
    vimPlugins.nvim-treesitter-parsers.graphql
    vimPlugins.nvim-treesitter-parsers.gren
    vimPlugins.nvim-treesitter-parsers.groovy
    vimPlugins.nvim-treesitter-parsers.groq
    vimPlugins.nvim-treesitter-parsers.gstlaunch
    vimPlugins.nvim-treesitter-parsers.hack
    vimPlugins.nvim-treesitter-parsers.hare
    vimPlugins.nvim-treesitter-parsers.haskell
    vimPlugins.nvim-treesitter-parsers.haskell_persistent
    vimPlugins.nvim-treesitter-parsers.hcl
    vimPlugins.nvim-treesitter-parsers.heex
    vimPlugins.nvim-treesitter-parsers.helm
    vimPlugins.nvim-treesitter-parsers.hjson
    vimPlugins.nvim-treesitter-parsers.hlsl
    vimPlugins.nvim-treesitter-parsers.hlsplaylist
    vimPlugins.nvim-treesitter-parsers.hocon
    vimPlugins.nvim-treesitter-parsers.hoon
    vimPlugins.nvim-treesitter-parsers.html
    vimPlugins.nvim-treesitter-parsers.htmldjango
    vimPlugins.nvim-treesitter-parsers.http
    vimPlugins.nvim-treesitter-parsers.hurl
    vimPlugins.nvim-treesitter-parsers.hyprlang
    vimPlugins.nvim-treesitter-parsers.idl
    vimPlugins.nvim-treesitter-parsers.idris
    vimPlugins.nvim-treesitter-parsers.ini
    vimPlugins.nvim-treesitter-parsers.inko
    vimPlugins.nvim-treesitter-parsers.ispc
    vimPlugins.nvim-treesitter-parsers.janet_simple
    vimPlugins.nvim-treesitter-parsers.java
    vimPlugins.nvim-treesitter-parsers.javadoc
    vimPlugins.nvim-treesitter-parsers.javascript
    vimPlugins.nvim-treesitter-parsers.jinja
    vimPlugins.nvim-treesitter-parsers.jinja_inline
    vimPlugins.nvim-treesitter-parsers.jq
    vimPlugins.nvim-treesitter-parsers.jsdoc
    vimPlugins.nvim-treesitter-parsers.json
    vimPlugins.nvim-treesitter-parsers.json5
    vimPlugins.nvim-treesitter-parsers.jsonnet
    vimPlugins.nvim-treesitter-parsers.julia
    vimPlugins.nvim-treesitter-parsers.just
    vimPlugins.nvim-treesitter-parsers.kcl
    vimPlugins.nvim-treesitter-parsers.kconfig
    vimPlugins.nvim-treesitter-parsers.kdl
    vimPlugins.nvim-treesitter-parsers.kitty
    vimPlugins.nvim-treesitter-parsers.kos
    vimPlugins.nvim-treesitter-parsers.kotlin
    vimPlugins.nvim-treesitter-parsers.koto
    vimPlugins.nvim-treesitter-parsers.kusto
    vimPlugins.nvim-treesitter-parsers.lalrpop
    vimPlugins.nvim-treesitter-parsers.latex
    vimPlugins.nvim-treesitter-parsers.ledger
    vimPlugins.nvim-treesitter-parsers.leo
    vimPlugins.nvim-treesitter-parsers.linkerscript
    vimPlugins.nvim-treesitter-parsers.liquid
    vimPlugins.nvim-treesitter-parsers.liquidsoap
    vimPlugins.nvim-treesitter-parsers.llvm
    vimPlugins.nvim-treesitter-parsers.lua
    vimPlugins.nvim-treesitter-parsers.luadoc
    vimPlugins.nvim-treesitter-parsers.luap
    vimPlugins.nvim-treesitter-parsers.luau
    vimPlugins.nvim-treesitter-parsers.m68k
    vimPlugins.nvim-treesitter-parsers.make
    vimPlugins.nvim-treesitter-parsers.markdown
    vimPlugins.nvim-treesitter-parsers.markdown_inline
    vimPlugins.nvim-treesitter-parsers.matlab
    vimPlugins.nvim-treesitter-parsers.menhir
    vimPlugins.nvim-treesitter-parsers.mermaid
    vimPlugins.nvim-treesitter-parsers.meson
    vimPlugins.nvim-treesitter-parsers.mlir
    vimPlugins.nvim-treesitter-parsers.muttrc
    vimPlugins.nvim-treesitter-parsers.nasm
    vimPlugins.nvim-treesitter-parsers.nginx
    vimPlugins.nvim-treesitter-parsers.nickel
    vimPlugins.nvim-treesitter-parsers.nim
    vimPlugins.nvim-treesitter-parsers.nim_format_string
    vimPlugins.nvim-treesitter-parsers.ninja
    vimPlugins.nvim-treesitter-parsers.nix
    vimPlugins.nvim-treesitter-parsers.nqc
    vimPlugins.nvim-treesitter-parsers.nu
    vimPlugins.nvim-treesitter-parsers.objc
    vimPlugins.nvim-treesitter-parsers.objdump
    vimPlugins.nvim-treesitter-parsers.ocaml
    vimPlugins.nvim-treesitter-parsers.ocaml_interface
    vimPlugins.nvim-treesitter-parsers.ocamllex
    vimPlugins.nvim-treesitter-parsers.odin
    vimPlugins.nvim-treesitter-parsers.pascal
    vimPlugins.nvim-treesitter-parsers.passwd
    vimPlugins.nvim-treesitter-parsers.pem
    vimPlugins.nvim-treesitter-parsers.perl
    vimPlugins.nvim-treesitter-parsers.php
    vimPlugins.nvim-treesitter-parsers.phpdoc
    vimPlugins.nvim-treesitter-parsers.php_only
    vimPlugins.nvim-treesitter-parsers.pioasm
    vimPlugins.nvim-treesitter-parsers.pkl
    vimPlugins.nvim-treesitter-parsers.po
    vimPlugins.nvim-treesitter-parsers.pod
    vimPlugins.nvim-treesitter-parsers.poe_filter
    vimPlugins.nvim-treesitter-parsers.pony
    vimPlugins.nvim-treesitter-parsers.powershell
    vimPlugins.nvim-treesitter-parsers.printf
    vimPlugins.nvim-treesitter-parsers.prisma
    vimPlugins.nvim-treesitter-parsers.problog
    vimPlugins.nvim-treesitter-parsers.prolog
    vimPlugins.nvim-treesitter-parsers.promql
    vimPlugins.nvim-treesitter-parsers.properties
    vimPlugins.nvim-treesitter-parsers.proto
    vimPlugins.nvim-treesitter-parsers.prql
    vimPlugins.nvim-treesitter-parsers.psv
    vimPlugins.nvim-treesitter-parsers.pug
    vimPlugins.nvim-treesitter-parsers.puppet
    vimPlugins.nvim-treesitter-parsers.purescript
    vimPlugins.nvim-treesitter-parsers.pymanifest
    vimPlugins.nvim-treesitter-parsers.python
    vimPlugins.nvim-treesitter-parsers.ql
    vimPlugins.nvim-treesitter-parsers.qmldir
    vimPlugins.nvim-treesitter-parsers.qmljs
    vimPlugins.nvim-treesitter-parsers.query
    vimPlugins.nvim-treesitter-parsers.r
    vimPlugins.nvim-treesitter-parsers.racket
    vimPlugins.nvim-treesitter-parsers.ralph
    vimPlugins.nvim-treesitter-parsers.rasi
    vimPlugins.nvim-treesitter-parsers.razor
    vimPlugins.nvim-treesitter-parsers.rbs
    vimPlugins.nvim-treesitter-parsers.re2c
    vimPlugins.nvim-treesitter-parsers.readline
    vimPlugins.nvim-treesitter-parsers.regex
    vimPlugins.nvim-treesitter-parsers.rego
    vimPlugins.nvim-treesitter-parsers.requirements
    vimPlugins.nvim-treesitter-parsers.rescript
    vimPlugins.nvim-treesitter-parsers.rifleconf
    vimPlugins.nvim-treesitter-parsers.rnoweb
    vimPlugins.nvim-treesitter-parsers.robot
    vimPlugins.nvim-treesitter-parsers.robots_txt
    vimPlugins.nvim-treesitter-parsers.roc
    vimPlugins.nvim-treesitter-parsers.ron
    vimPlugins.nvim-treesitter-parsers.rst
    vimPlugins.nvim-treesitter-parsers.ruby
    vimPlugins.nvim-treesitter-parsers.runescript
    vimPlugins.nvim-treesitter-parsers.rust
    vimPlugins.nvim-treesitter-parsers.scala
    vimPlugins.nvim-treesitter-parsers.scfg
    vimPlugins.nvim-treesitter-parsers.scheme
    vimPlugins.nvim-treesitter-parsers.scss
    vimPlugins.nvim-treesitter-parsers.sflog
    vimPlugins.nvim-treesitter-parsers.slang
    vimPlugins.nvim-treesitter-parsers.slim
    vimPlugins.nvim-treesitter-parsers.slint
    vimPlugins.nvim-treesitter-parsers.smali
    vimPlugins.nvim-treesitter-parsers.smithy
    vimPlugins.nvim-treesitter-parsers.snakemake
    vimPlugins.nvim-treesitter-parsers.snl
    vimPlugins.nvim-treesitter-parsers.solidity
    vimPlugins.nvim-treesitter-parsers.soql
    vimPlugins.nvim-treesitter-parsers.sosl
    vimPlugins.nvim-treesitter-parsers.sourcepawn
    vimPlugins.nvim-treesitter-parsers.sparql
    vimPlugins.nvim-treesitter-parsers.sproto
    vimPlugins.nvim-treesitter-parsers.sql
    vimPlugins.nvim-treesitter-parsers.squirrel
    vimPlugins.nvim-treesitter-parsers.ssh_config
    vimPlugins.nvim-treesitter-parsers.starlark
    vimPlugins.nvim-treesitter-parsers.strace
    vimPlugins.nvim-treesitter-parsers.styled
    vimPlugins.nvim-treesitter-parsers.supercollider
    vimPlugins.nvim-treesitter-parsers.superhtml
    vimPlugins.nvim-treesitter-parsers.surface
    vimPlugins.nvim-treesitter-parsers.svelte
    vimPlugins.nvim-treesitter-parsers.sway
    vimPlugins.nvim-treesitter-parsers.swift
    vimPlugins.nvim-treesitter-parsers.sxhkdrc
    vimPlugins.nvim-treesitter-parsers.systemtap
    vimPlugins.nvim-treesitter-parsers.systemverilog
    vimPlugins.nvim-treesitter-parsers.t32
    vimPlugins.nvim-treesitter-parsers.tablegen
    vimPlugins.nvim-treesitter-parsers.tact
    vimPlugins.nvim-treesitter-parsers.tcl
    vimPlugins.nvim-treesitter-parsers.teal
    vimPlugins.nvim-treesitter-parsers.templ
    vimPlugins.nvim-treesitter-parsers.tera
    vimPlugins.nvim-treesitter-parsers.terraform
    vimPlugins.nvim-treesitter-parsers.textproto
    vimPlugins.nvim-treesitter-parsers.thrift
    vimPlugins.nvim-treesitter-parsers.tiger
    vimPlugins.nvim-treesitter-parsers.tlaplus
    vimPlugins.nvim-treesitter-parsers.tmux
    vimPlugins.nvim-treesitter-parsers.todotxt
    vimPlugins.nvim-treesitter-parsers.toml
    vimPlugins.nvim-treesitter-parsers.tsv
    vimPlugins.nvim-treesitter-parsers.tsx
    vimPlugins.nvim-treesitter-parsers.turtle
    vimPlugins.nvim-treesitter-parsers.twig
    vimPlugins.nvim-treesitter-parsers.typescript
    vimPlugins.nvim-treesitter-parsers.typespec
    vimPlugins.nvim-treesitter-parsers.typoscript
    vimPlugins.nvim-treesitter-parsers.typst
    vimPlugins.nvim-treesitter-parsers.udev
    vimPlugins.nvim-treesitter-parsers.ungrammar
    vimPlugins.nvim-treesitter-parsers.unison
    vimPlugins.nvim-treesitter-parsers.usd
    vimPlugins.nvim-treesitter-parsers.uxntal
    vimPlugins.nvim-treesitter-parsers.v
    vimPlugins.nvim-treesitter-parsers.vala
    vimPlugins.nvim-treesitter-parsers.vento
    vimPlugins.nvim-treesitter-parsers.vhdl
    vimPlugins.nvim-treesitter-parsers.vhs
    vimPlugins.nvim-treesitter-parsers.vim
    vimPlugins.nvim-treesitter-parsers.vimdoc
    vimPlugins.nvim-treesitter-parsers.vrl
    vimPlugins.nvim-treesitter-parsers.vue
    vimPlugins.nvim-treesitter-parsers.wgsl
    vimPlugins.nvim-treesitter-parsers.wgsl_bevy
    vimPlugins.nvim-treesitter-parsers.wing
    vimPlugins.nvim-treesitter-parsers.wit
    vimPlugins.nvim-treesitter-parsers.wxml
    vimPlugins.nvim-treesitter-parsers.xcompose
    vimPlugins.nvim-treesitter-parsers.xml
    vimPlugins.nvim-treesitter-parsers.xresources
    vimPlugins.nvim-treesitter-parsers.yaml
    vimPlugins.nvim-treesitter-parsers.yang
    vimPlugins.nvim-treesitter-parsers.yuck
    vimPlugins.nvim-treesitter-parsers.zathurarc
    vimPlugins.nvim-treesitter-parsers.zig
    vimPlugins.nvim-treesitter-parsers.ziggy
    vimPlugins.nvim-treesitter-parsers.ziggy_schema
    vimPlugins.nvim-treesitter-parsers.zsh
    vimPlugins.nvim-treesitter-pyfold
    vimPlugins.nvim-treesitter-refactor
    vimPlugins.nvim-treesitter-sexp
    vimPlugins.nvim-treesitter-textobjects
    vimPlugins.nvim-treesitter-textobjects-legacy
    vimPlugins.nvim-treesitter-textsubjects
    vimPlugins.nvim-trevJ-lua
    vimPlugins.nvim-ts-autotag
    vimPlugins.nvim-ts-context-commentstring
    vimPlugins.nvim-ufo
    vimPlugins.nvim-unception
    vimPlugins.nvim-unity
    vimPlugins.nvim-various-textobjs
    vimPlugins.nvim-vtsls
    vimPlugins.nvim-web-devicons
    vimPlugins.nvim-whichkey-setup-lua
    vimPlugins.nvim-window-picker
    vimPlugins.nvim-yarp
    vimPlugins.nvterm
    vimPlugins.nvzone-menu
    vimPlugins.nvzone-minty
    vimPlugins.nvzone-typr
    vimPlugins.nvzone-volt
    vimPlugins.obsidian-nvim
    vimPlugins.ocaml-nvim
    vimPlugins.oceanic-material
    vimPlugins.oceanic-next
    vimPlugins.octo-nvim
    vimPlugins.oil-git-nvim
    vimPlugins.oil-git-status-nvim
    vimPlugins.oil-lsp-diagnostics-nvim
    vimPlugins.oil-nvim
    vimPlugins.oklch-color-picker-nvim
    vimPlugins.ollama-nvim
    vimPlugins.omnisharp-extended-lsp-nvim
    vimPlugins.omni-vim
    vimPlugins.onedarker-nvim
    vimPlugins.onedark-nvim
    vimPlugins.onedarkpro-nvim
    vimPlugins.onedark-vim
    vimPlugins.onehalf
    vimPlugins.onenord-nvim
    vimPlugins.one-nvim
    vimPlugins.one-small-step-for-vimkind
    vimPlugins.open-browser
    vimPlugins.open-browser-github-vim
    vimPlugins.open-browser-vim
    vimPlugins.opencode-nvim
    vimPlugins.openingh-nvim
    vimPlugins.openscad-nvim
    vimPlugins.orgmode
    vimPlugins.org-notebook-nvim
    vimPlugins.org-roam-nvim
    vimPlugins.other-nvim
    vimPlugins.Otree-nvim
    vimPlugins.otter-nvim
    vimPlugins.outline-nvim
    vimPlugins.overseer-nvim
    vimPlugins.oxocarbon-nvim
    vimPlugins.package-info-nvim
    vimPlugins.packer-nvim
    vimPlugins.palenightfall-nvim
    vimPlugins.palenight-vim
    vimPlugins.palette-nvim
    vimPlugins.papercolor-theme
    vimPlugins.papercolor-theme-slim
    vimPlugins.papis-nvim
    vimPlugins.parinfer-rust
    vimPlugins.parpar-nvim
    vimPlugins.parrot-nvim
    vimPlugins.pathogen
    vimPlugins.patterns-nvim
    vimPlugins.pckr-nvim
    vimPlugins.pears-nvim
    vimPlugins.pear-tree
    vimPlugins.peek-nvim
    vimPlugins.perfanno-nvim
    vimPlugins.persisted-nvim
    vimPlugins.persistence-nvim
    vimPlugins.persistent-breakpoints-nvim
    vimPlugins.pest-vim
    vimPlugins.pgsql-vim
    vimPlugins.phha-zenburn
    vimPlugins.phpactor
    vimPlugins.pig-vim
    vimPlugins.plantuml-nvim
    vimPlugins.plantuml-previewer-vim
    vimPlugins.plantuml-syntax
    vimPlugins.plenary-nvim
    vimPlugins.poimandres-nvim
    vimPlugins.polyglot
    vimPlugins.pomo-nvim
    vimPlugins.pony-vim-syntax
    vimPlugins.popfix
    vimPlugins.popup-nvim
    vimPlugins.precognition-nvim
    vimPlugins.presence-nvim
    vimPlugins.presenting-vim
    vimPlugins.PreserveNoEOL
    vimPlugins.preto
    vimPlugins.pretty-fold-nvim
    vimPlugins.prettyprint
    vimPlugins.Preview-nvim
    vimPlugins.prev_indent
    vimPlugins.projections-nvim
    vimPlugins.project-nvim
    vimPlugins.promise-async
    vimPlugins.psc-ide-vim
    vimPlugins.pum-vim
    vimPlugins.pure-lua
    vimPlugins.purescript-vim
    vimPlugins.python-mode
    vimPlugins.python-syntax
    vimPlugins.pywal-nvim
    vimPlugins.qfctl-nvim
    vimPlugins.QFEnter
    vimPlugins.qmk-nvim
    vimPlugins.quarto-nvim
    vimPlugins.quicker-nvim
    vimPlugins.quickfix-reflector-vim
    vimPlugins.quickfixstatus
    vimPlugins.quickmath-nvim
    vimPlugins.quickrun
    vimPlugins.quick-scope
    vimPlugins.rainbow
    vimPlugins.rainbow_csv
    vimPlugins.rainbow-delimiters-nvim
    vimPlugins.rainbow_parentheses
    vimPlugins.rainbow_parentheses-vim
    vimPlugins.random-vim
    vimPlugins.range-highlight-nvim
    vimPlugins.ranger-nvim
    vimPlugins.ranger-vim
    vimPlugins.rcshell-vim
    vimPlugins.readline-vim
    vimPlugins.Recover-vim
    vimPlugins.refactoring-nvim
    vimPlugins.refjump-nvim
    vimPlugins.registers-nvim
    vimPlugins.remember-nvim
    vimPlugins.remote-nvim-nvim
    vimPlugins.remote-sshfs-nvim
    vimPlugins.Rename
    vimPlugins.renamer-nvim
    vimPlugins.render-markdown
    vimPlugins.render-markdown-nvim
    vimPlugins.repeat
    vimPlugins.replacer-nvim
    vimPlugins.ReplaceWithRegister
    vimPlugins.repolink-nvim
    vimPlugins.resession-nvim
    vimPlugins.rest-nvim
    vimPlugins.restore-view-vim
    vimPlugins.rhubarb
    vimPlugins.riv
    vimPlugins.riv-vim
    vimPlugins.rnvimr
    vimPlugins.robotframework-vim
    vimPlugins.rocks-config-nvim
    vimPlugins.rocks-dev-nvim
    vimPlugins.rocks-git-nvim
    vimPlugins.rocks-nvim
    vimPlugins.ron-vim
    vimPlugins.rose-pine
    vimPlugins.roslyn-nvim
    vimPlugins.rspec-vim
    vimPlugins.rtorrent-syntax-file
    vimPlugins.rtp-nvim
    vimPlugins.rustaceanvim
    vimPlugins.rust-vim
    vimPlugins.rzls-nvim
    vimPlugins.sad-vim
    vimPlugins.salt-vim
    vimPlugins.samodostal-image-nvim
    vimPlugins.satellite-nvim
    vimPlugins.schema-companion-nvim
    vimPlugins.SchemaStore-nvim
    vimPlugins.scnvim
    vimPlugins.scope-nvim
    vimPlugins.scretch-nvim
    vimPlugins.scrollbar-nvim
    vimPlugins.scss-syntax-vim
    vimPlugins.search-and-replace-nvim
    vimPlugins.searchbox-nvim
    vimPlugins.securemodelines
    vimPlugins.self
    vimPlugins.semantic-highlight-vim
    vimPlugins.semshi
    vimPlugins.sensible
    vimPlugins.seoul256-vim
    vimPlugins.sg-nvim
    vimPlugins.shabadou-vim
    vimPlugins.Shade-nvim
    vimPlugins.showkeys
    vimPlugins.ShowMultiBase
    vimPlugins.sidekick-nvim
    vimPlugins.sideways-vim
    vimPlugins.signature
    vimPlugins.SimpylFold
    vimPlugins.skim
    vimPlugins.skim-vim
    vimPlugins.sky-color-clock-vim
    vimPlugins.sleuth
    vimPlugins.slimv
    vimPlugins.SmartCase
    vimPlugins.smartcolumn-nvim
    vimPlugins.smart-open-nvim
    vimPlugins.smartpairs-vim
    vimPlugins.smart-splits-nvim
    vimPlugins.smartyank-nvim
    vimPlugins.smear-cursor-nvim
    vimPlugins.snacks-nvim
    vimPlugins.snap
    vimPlugins.snipe-nvim
    vimPlugins.snipmate
    vimPlugins.snippets-nvim
    vimPlugins.sniprun
    vimPlugins.solarized
    vimPlugins.Solarized
    vimPlugins.solarized-nvim
    vimPlugins.solarized-osaka-nvim
    vimPlugins.solidity
    vimPlugins.sonarlint-nvim
    vimPlugins.sonarqube-nvim
    vimPlugins.sonokai
    vimPlugins.sort-nvim
    vimPlugins.sourcemap
    vimPlugins.sourcemap-vim
    vimPlugins.SpaceCamp
    vimPlugins.spaceman-nvim
    vimPlugins.space-vim
    vimPlugins.specs-nvim
    vimPlugins.spellsitter-nvim
    vimPlugins.spellwarn-nvim
    vimPlugins.sphinx-nvim
    vimPlugins.splice-vim
    vimPlugins.splitjoin-vim
    vimPlugins.split-term-vim
    vimPlugins.sqlite-lua
    vimPlugins.srcery-vim
    vimPlugins.sslsecure-vim
    vimPlugins.ssr
    vimPlugins.ssr-nvim
    vimPlugins.stabilize-nvim
    vimPlugins.staline-nvim
    vimPlugins.stan-vim
    vimPlugins.starrynight
    vimPlugins.starsearch-vim
    vimPlugins.startup-nvim
    vimPlugins.statix
    vimPlugins.statuscol-nvim
    vimPlugins.stay-centered-nvim
    vimPlugins.stringbreaker-nvim
    vimPlugins.styler-nvim
    vimPlugins.stylish-haskell
    vimPlugins.stylishHaskell
    vimPlugins.stylish-nvim
    vimPlugins.substitute-nvim
    vimPlugins.substrata-nvim
    vimPlugins.suda-vim
    vimPlugins.SudoEdit-vim
    vimPlugins.supermaven-nvim
    vimPlugins.supertab
    vimPlugins.Supertab
    vimPlugins.surround
    vimPlugins.surround-nvim
    vimPlugins.sved
    vimPlugins.swayconfig-vim
    vimPlugins.swift-vim
    vimPlugins.switcher-nvim
    vimPlugins.switch-vim
    vimPlugins.symbols-outline-nvim
    vimPlugins.symbol-usage-nvim
    vimPlugins.syntastic
    vimPlugins.Syntastic
    vimPlugins.SyntaxRange
    vimPlugins.tabby-nvim
    vimPlugins.table-mode
    vimPlugins.tabline-nvim
    vimPlugins.tabmerge
    vimPlugins.tabnine-vim
    vimPlugins.taboo-vim
    vimPlugins.tabout-nvim
    vimPlugins.tabpagebuffer
    vimPlugins.tabpagebuffer-vim
    vimPlugins.tabpagecd
    vimPlugins.tabular
    vimPlugins.Tabular
    vimPlugins.tagalong-vim
    vimPlugins.tagbar
    vimPlugins.Tagbar
    vimPlugins.taglist
    vimPlugins.taglist-vim
    vimPlugins.tailwindcss-colors-nvim
    vimPlugins.tailwind-tools-nvim
    vimPlugins.tardis-nvim
    vimPlugins.targets-vim
    vimPlugins.taskwarrior
    vimPlugins.taskwarrior2
    vimPlugins.taskwarrior3
    vimPlugins.taskwiki
    vimPlugins.tcomment_vim
    vimPlugins.teamtype
    vimPlugins.telekasten-nvim
    vimPlugins.telescope-ast-grep-nvim
    vimPlugins.telescope-asynctasks-nvim
    vimPlugins.telescope-cheat-nvim
    vimPlugins.telescope-coc-nvim
    vimPlugins.telescope-dap-nvim
    vimPlugins.telescope-emoji-nvim
    vimPlugins.telescope-file-browser-nvim
    vimPlugins.telescope-frecency-nvim
    vimPlugins.telescope-fzf-native-nvim
    vimPlugins.telescope-fzf-writer-nvim
    vimPlugins.telescope-fzy-native-nvim
    vimPlugins.telescope-git-conflicts-nvim
    vimPlugins.telescope-github-nvim
    vimPlugins.telescope-glyph-nvim
    vimPlugins.telescope-hierarchy-nvim
    vimPlugins.telescope_hoogle
    vimPlugins.telescope-live-grep-args-nvim
    vimPlugins.telescope-lsp-handlers-nvim
    vimPlugins.telescope-manix
    vimPlugins.telescope-media-files-nvim
    vimPlugins.telescope-nvim
    vimPlugins.telescope-project-nvim
    vimPlugins.telescope-sg
    vimPlugins.telescope-smart-history-nvim
    vimPlugins.telescope-symbols-nvim
    vimPlugins.telescope-ui-select-nvim
    vimPlugins.telescope-ultisnips-nvim
    vimPlugins.telescope-undo-nvim
    vimPlugins.telescope-vim-bookmarks-nvim
    vimPlugins.telescope-zf-native-nvim
    vimPlugins.telescope-z-nvim
    vimPlugins.telescope-zoxide
    vimPlugins.template-string-nvim
    vimPlugins.templ-vim
    vimPlugins.tender-vim
    vimPlugins.term-edit-nvim
    vimPlugins.terminal-nvim
    vimPlugins.terminus
    vimPlugins.termwrapper-nvim
    vimPlugins.tern_for_vim
    vimPlugins.tex-conceal-vim
    vimPlugins.texpresso-vim
    vimPlugins.text-case-nvim
    vimPlugins.thanks-nvim
    vimPlugins.themed-tabs-nvim
    vimPlugins.themery-nvim
    vimPlugins.The_NERD_Commenter
    vimPlugins.The_NERD_tree
    vimPlugins.thesaurus_query-vim
    vimPlugins.thumbnail
    vimPlugins.thumbnail-vim
    vimPlugins.timerly
    vimPlugins.timestamp-vim
    vimPlugins.tinted-nvim
    vimPlugins.tinted-vim
    vimPlugins.tint-nvim
    vimPlugins.tiny-devicons-auto-colors-nvim
    vimPlugins.tiny-glimmer-nvim
    vimPlugins.tiny-inline-diagnostic-nvim
    vimPlugins.tinykeymap
    vimPlugins.tlib
    vimPlugins.tlib_vim
    vimPlugins.tmux-complete-vim
    vimPlugins.tmuxline-vim
    vimPlugins.tmux-navigator
    vimPlugins.tmuxNavigator
    vimPlugins.tmux-nvim
    vimPlugins.todo-comments-nvim
    vimPlugins.todo-txt-vim
    vimPlugins.toggleterm-nvim
    vimPlugins.tokyonight-nvim
    vimPlugins.traces-vim
    vimPlugins.trailblazer-nvim
    vimPlugins.train-nvim
    vimPlugins.transparent-nvim
    vimPlugins.treesitter-modules-nvim
    vimPlugins.treesj
    vimPlugins.treewalker-nvim
    vimPlugins.tremor-vim
    vimPlugins.trim-nvim
    vimPlugins.triptych-nvim
    vimPlugins.trouble-nvim
    vimPlugins.true-zen-nvim
    vimPlugins.trust-vim
    vimPlugins.ts-autotag-nvim
    vimPlugins.tsc-nvim
    vimPlugins.ts-comments-nvim
    vimPlugins.tslime
    vimPlugins.tslime-vim
    vimPlugins.tssorter-nvim
    vimPlugins.tsuquyomi
    vimPlugins.tuis-nvim
    vimPlugins.tup
    vimPlugins.tv-nvim
    vimPlugins.twilight-nvim
    vimPlugins.typescript-nvim
    vimPlugins.typescript-tools-nvim
    vimPlugins.typescript-vim
    vimPlugins.typst-conceal-vim
    vimPlugins.typst-preview-nvim
    vimPlugins.typst-vim
    vimPlugins.typstwatch-nvim
    vimPlugins.ultimate-autopair-nvim
    vimPlugins.ultisnips
    vimPlugins.UltiSnips
    vimPlugins.undotree
    vimPlugins.unicode-vim
    vimPlugins.unified-nvim
    vimPlugins.unimpaired-nvim
    vimPlugins.unimpaired-which-key-nvim
    vimPlugins.unison
    vimPlugins.unite
    vimPlugins.unite-vim
    vimPluginsUpdater
    vimPlugins.url-open
    vimPlugins.urlview-nvim
    vimPlugins.utl-vim
    vimPlugins.uv-nvim
    vimPlugins.vader-vim
    vimPlugins.vague-nvim
    vimPlugins.vCoolor-vim
    vimPlugins.vectorcode-nvim
    vimPlugins.venn-nvim
    vimPlugins.venv-selector-nvim
    vimPlugins.verilog_systemverilog-vim
    vimPlugins.vifm-vim
    vimPlugins.vim2hs
    vimPlugins.vim2nix
    vimPlugins.vim9-stargate
    vimPlugins.vim-abolish
    vimPlugins.vimacs
    vimPlugins.vim-addon-actions
    vimPlugins.vim-addon-async
    vimPlugins.vim-addon-background-cmd
    vimPlugins.vim-addon-commenting
    vimPlugins.vim-addon-completion
    vimPlugins.vim-addon-errorformats
    vimPlugins.vim-addon-goto-thing-at-cursor
    vimPlugins.vim-addon-local-vimrc
    vimPlugins.vim-addon-manager
    vimPlugins.vim-addon-mru
    vimPlugins.vim-addon-mw-utils
    vimPlugins.vim-addon-nix
    vimPlugins.vim-addon-other
    vimPlugins.vim-addon-php-manual
    vimPlugins.vim-addon-signs
    vimPlugins.vim-addon-sql
    vimPlugins.vim-addon-syntax-checker
    vimPlugins.vim-addon-toggle-buffer
    vimPlugins.vim-addon-vim2nix
    vimPlugins.vim-addon-xdebug
    vimPlugins.vimade
    vimPlugins.vim-advanced-sorters
    vimPlugins.vim-afterglow
    vimPlugins.vim-after-object
    vimPlugins.vim-agda
    vimPlugins.vimagit
    vimPlugins.vim-airline
    vimPlugins.vim-airline-clock
    vimPlugins.vim-airline-themes
    vimPlugins.vim-alias
    vimPlugins.vim-android
    vimPlugins.vim-angry
    vimPlugins.vim-anzu
    vimPlugins.vim-apathy
    vimPlugins.vim-apm
    vimPlugins.vim-argumentative
    vimPlugins.vim-argwrap
    vimPlugins.vim-asterisk
    vimPlugins.vim-astro
    vimPlugins.vim-asymptote
    vimPlugins.vim-autoformat
    vimPlugins.vim-automkdir
    vimPlugins.vim-auto-save
    vimPlugins.vim-autosource
    vimPlugins.vim-autoswap
    vimPlugins.vim-bazel
    vimPlugins.vim-bbye
    vimPlugins.vim-beancount
    vimPlugins.vim-be-good
    vimPlugins.vim-bepoptimist
    vimPlugins.vim-better-whitespace
    vimPlugins.vim-bookmarks
    vimPlugins.vim-boxdraw
    vimPlugins.vim-bracketed-paste
    vimPlugins.vim-bsv
    vimPlugins.vim-buffergator
    vimPlugins.vim-bufferline
    vimPlugins.vim-buffet
    vimPlugins.vim-bufkill
    vimPlugins.vim-buftabline
    vimPlugins.vim-caddyfile
    vimPlugins.vim-capslock
    vimPlugins.vim-carbon-now-sh
    vimPlugins.vim-ccls
    vimPlugins.vim-characterize
    vimPlugins.vim-choosewin
    vimPlugins.vim-clang-format
    vimPlugins.vim-clap
    vimPlugins.vim-classpath
    vimPlugins.vim-clojure-highlight
    vimPlugins.vim-clojure-static
    vimPlugins.vim-closer
    vimPlugins.vim-closetag
    vimPlugins.vim-cmake
    vimPlugins.vim-code-dark
    vimPlugins.vim-codefmt
    vimPlugins.vim-coffee-script
    vimPlugins.vim-colemak
    vimPlugins.vim-colorschemes
    vimPlugins.vim-colors-paramount
    vimPlugins.vim-colors-solarized
    vimPlugins.vim-colorstepper
    vimPlugins.vim-commentary
    vimPlugins.VimCompletesMe
    vimPlugins.vim-concourse
    vimPlugins.vim-cool
    vimPlugins.vim-cpp-enhanced-highlight
    vimPlugins.vim-crates
    vimPlugins.vim-crystal
    vimPlugins.vim-crystalline
    vimPlugins.vim-csharp
    vimPlugins.vim-css-color
    vimPlugins.vim-CtrlXA
    vimPlugins.vim-cue
    vimPlugins.vim_current_word
    vimPlugins.vim-cursorword
    vimPlugins.vim-cute-python
    vimPlugins.vim-dadbod
    vimPlugins.vim-dadbod-completion
    vimPlugins.vim-dadbod-ui
    vimPlugins.vim-dasht
    vimPlugins.vim-DetectSpellLang
    vimPlugins.vim-deus
    vimPlugins.vim-devicons
    vimPlugins.vim-dim
    vimPlugins.vim-diminactive
    vimPlugins.vim-dirdiff
    vimPlugins.vim-dirvish
    vimPlugins.vim-dirvish-git
    vimPlugins.vim-dispatch
    vimPlugins.vim-dispatch-neovim
    vimPlugins.vim-docbk
    vimPlugins.vim-docbk-snippets
    vimPlugins.vim-dotenv
    vimPlugins.vim-easy-align
    vimPlugins.vim-easyescape
    vimPlugins.vim-easygit
    vimPlugins.vim-easymotion
    vimPlugins.vim-easytags
    vimPlugins.vim-eighties
    vimPlugins.vimelette
    vimPlugins.vim-elixir
    vimPlugins.vim-elm-syntax
    vimPlugins.vim-emacs-bindings
    vimPlugins.vim-emoji
    vimPlugins.vim-endwise
    vimPlugins.vim-enmasse
    vimPlugins.vim-erlang-compiler
    vimPlugins.vim-erlang-omnicomplete
    vimPlugins.vim-erlang-runtime
    vimPlugins.vim-erlang-tags
    vimPlugins.vim-eunuch
    vimPlugins.vim-exchange
    vimPlugins.vim-expand-region
    vimPlugins.vim-extradite
    vimPlugins.vim-fern
    vimPlugins.vim-fetch
    vimPlugins.vim-figlet
    vimPlugins.vimfiler-vim
    vimPlugins.vim-fireplace
    vimPlugins.vim-fish
    vimPlugins.vim-flagship
    vimPlugins.vim-flake8
    vimPlugins.vim-flatbuffers
    vimPlugins.vim-floaterm
    vimPlugins.vim-flog
    vimPlugins.vim-flutter
    vimPlugins.vim-fold-cycle
    vimPlugins.vim-foldsearch
    vimPlugins.vim-fsharp
    vimPlugins.vim-ft-diff_fold
    vimPlugins.vim-fubitive
    vimPlugins.vim-fugitive
    vimPlugins.vim-fzf-coauthorship
    vimPlugins.vim-gas
    vimPlugins.vim-gh-line
    vimPlugins.vim-ghost
    vimPlugins.vim-gina
    vimPlugins.vim-gist
    vimPlugins.vim-gista
    vimPlugins.vim-git
    vimPlugins.vim-gitbranch
    vimPlugins.vim-gitgutter
    vimPlugins.vim-github-dashboard
    vimPlugins.vim-glsl
    vimPlugins.vim-gml
    vimPlugins.vim-gnupg
    vimPlugins.vim-go
    vimPlugins.vim-godot
    vimPlugins.vim-grammarous
    vimPlugins.vim-graphql
    vimPlugins.vim-grepper
    vimPlugins.vim-gruvbox8
    vimPlugins.vim-gui-position
    vimPlugins.vim-gutentags
    vimPlugins.vim-habamax
    vimPlugins.vim-hardtime
    vimPlugins.vim-haskellconceal
    vimPlugins.vim-haskellConcealPlus
    vimPlugins.vim-haskell-module-name
    vimPlugins.vim-hcl
    vimPlugins.vim-hdevtools
    vimPlugins.vim-helm
    vimPlugins.vim-hexokinase
    vimPlugins.vim-hier
    vimPlugins.vim-highlightedyank
    vimPlugins.vim-hindent
    vimPlugins.vim-hocon
    vimPlugins.vim-hoogle
    vimPlugins.vim-horizon
    vimPlugins.vim-html-template-literals
    vimPlugins.vim-humanoid-colorscheme
    vimPlugins.vim-husk
    vimPlugins.vim-hy
    vimPlugins.vim-hybrid
    vimPlugins.vim-hybrid-material
    vimPlugins.vim-iced-coffee-script
    vimPlugins.vim-illuminate
    vimPlugins.vim-indent-guides
    vimPlugins.vim-indent-object
    vimPlugins.vim-indentwise
    vimPlugins.vim-indexed-search
    vimPlugins.vim-ipython
    vimPlugins.vim-isort
    vimPlugins.vim-jack-in
    vimPlugins.vim-janah
    vimPlugins.vim-javacomplete2
    vimPlugins.vim-javascript
    vimPlugins.vim-javascript-syntax
    vimPlugins.vim-jdaddy
    vimPlugins.vim-jetpack
    vimPlugins.vim-jinja
    vimPlugins.vim-jinja-languages
    vimPlugins.vim-jjdescription
    vimPlugins.vim-jsbeautify
    vimPlugins.vim-jsdoc
    vimPlugins.vim-json
    vimPlugins.vim-jsonnet
    vimPlugins.vim-jsonpath
    vimPlugins.vim-jsx-pretty
    vimPlugins.vim-jsx-typescript
    vimPlugins.vim-julia-cell
    vimPlugins.vim-just
    vimPlugins.vim-kitty-navigator
    vimPlugins.vim-LanguageTool
    vimPlugins.vim-lark-syntax
    vimPlugins.vim-lastplace
    vimPlugins.vim-latex-live-preview
    vimPlugins.vim-lawrencium
    vimPlugins.vim-leader-guide
    vimPlugins.vim-lean
    vimPlugins.vim-ledger
    vimPlugins.vim-lexical
    vimPlugins.vim-lfe
    vimPlugins.vim-lightline-coc
    vimPlugins.vim-lion
    vimPlugins.vim-liquid
    vimPlugins.vim-llvm
    vimPlugins.vim-localvimrc
    vimPlugins.vim-logreview
    vimPlugins.vim-loves-dafny
    vimPlugins.vim-lsc
    vimPlugins.vim-lsp
    vimPlugins.vim-lsp-ale
    vimPlugins.vim-lsp-cxx-highlight
    vimPlugins.vim-lsp-settings
    vimPlugins.vim-lsp-snippets
    vimPlugins.vim-lsp-ultisnips
    vimPlugins.vim-lua
    vimPlugins.vim-maktaba
    vimPlugins.vim-manpager
    vimPlugins.vim-markbar
    vimPlugins.vim-markdown
    vimPlugins.vim-markdown-composer
    vimPlugins.vim-markdown-toc
    vimPlugins.vim-matchtag
    vimPlugins.vim-matchup
    vimPlugins.vim-mediawiki-editor
    vimPlugins.vim-mergetool
    vimPlugins.vim-merginal
    vimPlugins.vim-metamath
    vimPlugins.vim-misc
    vimPlugins.vim-molokai-delroth
    vimPlugins.vim-monokai
    vimPlugins.vim-monokai-pro
    vimPlugins.vim-monokai-tasty
    vimPlugins.vim-moonfly-colors
    vimPlugins.vim-move
    vimPlugins.vim-mucomplete
    vimPlugins.vim-multiple-cursors
    vimPlugins.vim-mundo
    vimPlugins.vim-mustache-handlebars
    vimPlugins.vim-nerdtree-syntax-highlight
    vimPlugins.vim-nerdtree-tabs
    vimPlugins.vim-nftables
    vimPlugins.vim-niceblock
    vimPlugins.vim-nickel
    vimPlugins.vim-ninja-feet
    vimPlugins.vim-nix
    vimPlugins.vim-nixhash
    vimPlugins.vim-noctu
    vimPlugins.vim-nong-theme
    vimPlugins.vim-numbertoggle
    vimPlugins.vim-obsession
    vimPlugins.vim-ocaml
    vimPlugins.vim-one
    vimPlugins.vim-opencl
    vimPlugins.vim-openscad
    vimPlugins.vim-operator-replace
    vimPlugins.vim-operator-surround
    vimPlugins.vim-operator-user
    vimPlugins.VimOrganizer
    vimPlugins.vim-orgmode
    vimPlugins.vim-ormolu
    vimPlugins.vim-osc52
    vimPlugins.vim-oscyank
    vimPlugins.vimoutliner
    vimPlugins.vim-over
    vimPlugins.vim-packer
    vimPlugins.vim-pager
    vimPlugins.vim-pandoc
    vimPlugins.vim-pandoc-after
    vimPlugins.vim-pandoc-syntax
    vimPlugins.vim-paper
    vimPlugins.vim-parinfer
    vimPlugins.vim-pasta
    vimPlugins.vim-pathogen
    vimPlugins.vim-peekaboo
    vimPlugins.vim-pencil
    vimPlugins.vim-pets
    vimPlugins.vim-phabricator
    vimPlugins.vim-pico8-syntax
    vimPlugins.vim-plug
    vimPlugins.vim-plugin-AnsiEsc
    vimPlugins.vim-pluto
    vimPlugins.vim-polyglot
    vimPlugins.vim-pony
    vimPlugins.vim-poweryank
    vimPlugins.vim-prettier
    vimPlugins.vim-prettyprint
    vimPlugins.vimpreviewpandoc
    vimPlugins.vim-printer
    vimPlugins.vim-prisma
    vimPlugins.vimproc
    vimPlugins.vimproc-vim
    vimPlugins.vim-projectionist
    vimPlugins.vim-prosession
    vimPlugins.vim-protobuf
    vimPlugins.vim-ps1
    vimPlugins.vim-pug
    vimPlugins.vim-puppet
    vimPlugins.vim-python-pep8-indent
    vimPlugins.vim-pythonsense
    vimPlugins.vim-qf
    vimPlugins.vim-qlist
    vimPlugins.vim-qml
    vimPlugins.vim-quickrun
    vimPlugins.vim-racer
    vimPlugins.vim-racket
    vimPlugins.vim-ragtag
    vimPlugins.vim-rails
    vimPlugins.vim-reasonml
    vimPlugins.vim-repeat
    vimPlugins.vim-ReplaceWithRegister
    vimPlugins.vim-ReplaceWithSameIndentRegister
    vimPlugins.vim-rhai
    vimPlugins.vim-rhubarb
    vimPlugins.vim-rooter
    vimPlugins.vim-rsi
    vimPlugins.vim-ruby
    vimPlugins.vim-salve
    vimPlugins.vim-sandwich
    vimPlugins.vim-sayonara
    vimPlugins.vim-scala
    vimPlugins.vim-scouter
    vimPlugins.vim-scriptease
    vimPlugins.vim-search-pulse
    vimPlugins.vimsence
    vimPlugins.vim-sensible
    vimPlugins.vim-sentence-chopper
    vimPlugins.vim-sexp
    vimPlugins.vim-sexp-mappings-for-regular-people
    vimPlugins.vimshell
    vimPlugins.vim-shellcheck
    vimPlugins.vimshell-vim
    vimPlugins.vim-signature
    vimPlugins.vim-signify
    vimPlugins.vim-sile
    vimPlugins.vim-simpledb
    vimPlugins.vim-slash
    vimPlugins.vim-sleuth
    vimPlugins.vim-slime
    vimPlugins.vim-smali
    vimPlugins.vim-smalls
    vimPlugins.vim-smartbd
    vimPlugins.vim-smartbw
    vimPlugins.vim-smoothie
    vimPlugins.vim-smt2
    vimPlugins.vim-sneak
    vimPlugins.vim-snipmate
    vimPlugins.vim-snippets
    vimPlugins.vim-solarized8
    vimPlugins.vim-solidity
    vimPlugins.vim-sort-motion
    vimPlugins.vimspector
    vimPlugins.vim-speeddating
    vimPlugins.vim-spirv
    vimPlugins.vim-splunk
    vimPlugins.vim-startify
    vimPlugins.vim-startuptime
    vimPlugins.vim-stationeers-ic10-syntax
    vimPlugins.vim-strip-trailing-whitespace
    vimPlugins.vim-stylishask
    vimPlugins.vim-stylish-haskell
    vimPlugins.vim-substrata
    vimPlugins.vim-subversive
    vimPlugins.vim-suda
    vimPlugins.vim-surround
    vimPlugins.vim-svelte
    vimPlugins.vim-swap
    vimPlugins.vim-SyntaxRange
    vimPlugins.vim-tabby
    vimPlugins.vim-table-mode
    vimPlugins.vim-tabpagecd
    vimPlugins.vim-tbone
    vimPlugins.vim-teal
    vimPlugins.vim-terminator
    vimPlugins.vim-terraform
    vimPlugins.vim-terraform-completion
    vimPlugins.vim-test
    vimPlugins.vimtex
    vimPlugins.vim-textobj-comment
    vimPlugins.vim-textobj-entire
    vimPlugins.vim-textobj-function
    vimPlugins.vim-textobj-haskell
    vimPlugins.vim-textobj-line
    vimPlugins.vim-textobj-multiblock
    vimPlugins.vim-textobj-quote
    vimPlugins.vim-textobj-user
    vimPlugins.vim-textobj-variable-segment
    vimPlugins.vim-themis
    vimPlugins.vim-tmux
    vimPlugins.vim-tmux-clipboard
    vimPlugins.vim-tmux-focus-events
    vimPlugins.vim-tmux-navigator
    vimPlugins.vim-togglelist
    vimPlugins.vim-toml
    vimPlugins.vim-tpipeline
    vimPlugins.vim-trailing-whitespace
    vimPlugins.vim-tridactyl
    vimPlugins.vim-tsx
    vimPlugins.vim-twig
    vimPlugins.vim-twiggy
    vimPlugins.vim-ultest
    vimPlugins.vim-unicoder
    vimPlugins.vim-unimpaired
    vimPlugins.vimux
    vimPlugins.vim-vagrant
    vimPlugins.vim-vinegar
    vimPlugins.vim-visual-increment
    vimPlugins.vim-visual-multi
    vimPlugins.vim-visualstar
    vimPlugins.vim-visual-star-search
    vimPlugins.vim-vp4
    vimPlugins.vim-vsnip
    vimPlugins.vim-vsnip-integ
    vimPlugins.vim-vue
    vimPlugins.vim-vue-plugin
    vimPlugins.vim-waikiki
    vimPlugins.vim-wakatime
    vimPlugins.vim-watchdogs
    vimPlugins.vim-wayland-clipboard
    vimPlugins.vim-which-key
    vimPlugins.vimwiki
    vimPlugins.vim-windowswap
    vimPlugins.vim-wordmotion
    vimPlugins.vim-wordy
    vimPlugins.vim-xdebug
    vimPlugins.vim-xkbswitch
    vimPlugins.vim-xtabline
    vimPlugins.vim-yaml
    vimPlugins.vim-yapf
    vimPlugins.vim-zettel
    vimPlugins.vim-zscript
    vimPlugins.vinegar
    vimPlugins.virt-column-nvim
    vimPlugins.virtual-types-nvim
    vimPlugins.vis
    vimPlugins.vissort-vim
    vimPlugins.vista-vim
    vimPlugins.visual-whitespace-nvim
    vimPlugins.vscode-diff-nvim
    vimPlugins.vscode-nvim
    vimPlugins.vs-tasks-nvim
    vimPlugins.Vundle-vim
    vimPlugins.wal-vim
    vimPlugins.watchdogs
    vimPlugins.WebAPI
    vimPlugins.webapi-vim
    vimPlugins.wezterm-nvim
    vimPlugins.wgsl-vim
    vimPlugins.whatif-vim
    vimPlugins.which-key-nvim
    vimPlugins.whichpy-nvim
    vimPlugins.whitespace-nvim
    vimPlugins.wiki-ft-vim
    vimPlugins.wiki-vim
    vimPlugins.wilder-nvim
    vimPlugins.wildfire-nvim
    vimPlugins.wildfire-vim
    vimPlugins.winbar-nvim
    vimPlugins.windows-nvim
    vimPlugins.windsurf-nvim
    vimPlugins.windsurf-vim
    vimPlugins.winshift-nvim
    vimPlugins.wmgraphviz-vim
    vimPlugins.wombat256
    vimPlugins.wombat256-vim
    vimPlugins.workflowish
    vimPlugins.workspaces-nvim
    vimPlugins.wrapping-nvim
    vimPlugins.wstrip-vim
    vimPlugins.wtf-nvim
    vimPlugins.xeno-nvim
    vimPlugins.xmake-nvim
    vimPlugins.xptemplate
    vimPlugins.xterm-color-table
    vimPlugins.xterm-color-table-vim
    vimPlugins.y9nika-nvim
    vimPlugins.yaml-companion-nvim
    vimPlugins.yaml-schema-detect-nvim
    vimPlugins.YankAssassin-vim
    vimPlugins.yankring
    vimPlugins.Yankring
    vimPlugins.YankRing-vim
    vimPlugins.yanky-nvim
    vimPlugins.yats-vim
    vimPlugins.yazi-nvim
    vimPlugins.yescapsquit-vim
    vimPlugins.YouCompleteMe
    vimPlugins.yuck-vim
    vimPlugins.YUNOcommit-vim
    vimPlugins.zarchive-vim-fsharp
    vimPlugins.zeavim
    vimPlugins.zeavim-vim
    vimPlugins.zellij-nav-nvim
    vimPlugins.zellij-nvim
    vimPlugins.zenbones-nvim
    vimPlugins.zenburn
    vimPlugins.zen-mode-nvim
    vimPlugins.zephyr-nvim
    vimPlugins.zig-vim
    vimPlugins.zk-nvim
    vimPlugins.zoomwintab-vim
    vimPlugins.zotcite
    vimPlugins.zoxide-vim
    virter
    virtiofsd
    virt-manager
    virt-top
    visidata
    vit
    vivid
    #vllm
    #      vscodeExtensions = with vscode-extensions; [
    #      vscode = vscodium;
    #    (vscode-with-extensions.override {
    vscodium
    w3m
    watch
    waybar
    wdisplays
    #    webex
    wezterm
    wget
    whipper
    wireguard-tools
    wl-clipboard
    wl-clip-persist
    wlogout
    # wl-screenrec
    wlsunset
    wofi
    wpgtk
    wsdd
    wshowkeys
    xan
    # xdg-desktop-portal-gtk
    # xdg-desktop-portal-hyprland
    #xfce.thunar
    xkcd-font
    xkcdpass
    yarn
    yazi
    yt-dlp
    zathura
    #zed-editor
    zellij
    #    zenmonitor
    zip
    zlib
    zoxide
    zstd

  ];
}
