{
  system,
  config,
  pkgs,
  pkgs-stable,
  inputs,
  ...
}:
{

  environment.systemPackages = with pkgs; [

    tree-sitter-grammars.tree-sitter-ada
    tree-sitter-grammars.tree-sitter-adl
    tree-sitter-grammars.tree-sitter-agda
    tree-sitter-grammars.tree-sitter-alloy
    tree-sitter-grammars.tree-sitter-amber
    tree-sitter-grammars.tree-sitter-astro
    tree-sitter-grammars.tree-sitter-awk
    tree-sitter-grammars.tree-sitter-bash
    tree-sitter-grammars.tree-sitter-bass
    tree-sitter-grammars.tree-sitter-beancount
    tree-sitter-grammars.tree-sitter-bibtex
    tree-sitter-grammars.tree-sitter-bicep
    tree-sitter-grammars.tree-sitter-bitbake
    tree-sitter-grammars.tree-sitter-blade
    tree-sitter-grammars.tree-sitter-blueprint
    tree-sitter-grammars.tree-sitter-bqn
    tree-sitter-grammars.tree-sitter-c
    tree-sitter-grammars.tree-sitter-caddyfile
    tree-sitter-grammars.tree-sitter-cairo
    tree-sitter-grammars.tree-sitter-capnp
    tree-sitter-grammars.tree-sitter-cel
    tree-sitter-grammars.tree-sitter-circom
    tree-sitter-grammars.tree-sitter-clarity
    tree-sitter-grammars.tree-sitter-clojure
    tree-sitter-grammars.tree-sitter-cmake
    tree-sitter-grammars.tree-sitter-comment
    tree-sitter-grammars.tree-sitter-commonlisp
    tree-sitter-grammars.tree-sitter-cpon
    tree-sitter-grammars.tree-sitter-cpp
    tree-sitter-grammars.tree-sitter-crystal
    tree-sitter-grammars.tree-sitter-c-sharp
    tree-sitter-grammars.tree-sitter-css
    tree-sitter-grammars.tree-sitter-csv
    tree-sitter-grammars.tree-sitter-cuda
    tree-sitter-grammars.tree-sitter-cue
    tree-sitter-grammars.tree-sitter-cylc
    tree-sitter-grammars.tree-sitter-d
    tree-sitter-grammars.tree-sitter-dart
    tree-sitter-grammars.tree-sitter-dbml
    tree-sitter-grammars.tree-sitter-debian
    tree-sitter-grammars.tree-sitter-devicetree
    tree-sitter-grammars.tree-sitter-dhall
    tree-sitter-grammars.tree-sitter-diff
    tree-sitter-grammars.tree-sitter-djot
    tree-sitter-grammars.tree-sitter-dockerfile
    tree-sitter-grammars.tree-sitter-dot
    tree-sitter-grammars.tree-sitter-dtd
    tree-sitter-grammars.tree-sitter-dunstrc
    tree-sitter-grammars.tree-sitter-earthfile
    tree-sitter-grammars.tree-sitter-edoc
    tree-sitter-grammars.tree-sitter-eex
    tree-sitter-grammars.tree-sitter-elisp
    tree-sitter-grammars.tree-sitter-elixir
    tree-sitter-grammars.tree-sitter-elm
    tree-sitter-grammars.tree-sitter-elvish
    tree-sitter-grammars.tree-sitter-embedded-template
    tree-sitter-grammars.tree-sitter-erlang
    tree-sitter-grammars.tree-sitter-esdl
    tree-sitter-grammars.tree-sitter-factor
    tree-sitter-grammars.tree-sitter-fennel
    tree-sitter-grammars.tree-sitter-fga
    tree-sitter-grammars.tree-sitter-fidl
    tree-sitter-grammars.tree-sitter-fish
    tree-sitter-grammars.tree-sitter-forth
    tree-sitter-grammars.tree-sitter-fortran
    tree-sitter-grammars.tree-sitter-fsharp
    tree-sitter-grammars.tree-sitter-gas
    tree-sitter-grammars.tree-sitter-gdscript
    tree-sitter-grammars.tree-sitter-gemini
    tree-sitter-grammars.tree-sitter-gherkin
    tree-sitter-grammars.tree-sitter-ghostty
    tree-sitter-grammars.tree-sitter-gitattributes
    tree-sitter-grammars.tree-sitter-gitcommit
    tree-sitter-grammars.tree-sitter-git-config
    tree-sitter-grammars.tree-sitter-gitignore
    tree-sitter-grammars.tree-sitter-git-rebase
    tree-sitter-grammars.tree-sitter-gleam
    tree-sitter-grammars.tree-sitter-glimmer
    tree-sitter-grammars.tree-sitter-glsl
    tree-sitter-grammars.tree-sitter-gn
    tree-sitter-grammars.tree-sitter-go
    tree-sitter-grammars.tree-sitter-godot-resource
    tree-sitter-grammars.tree-sitter-gomod
    tree-sitter-grammars.tree-sitter-go-template
    tree-sitter-grammars.tree-sitter-gotmpl
    tree-sitter-grammars.tree-sitter-gowork
    tree-sitter-grammars.tree-sitter-gpr
    tree-sitter-grammars.tree-sitter-graphql
    tree-sitter-grammars.tree-sitter-gren
    tree-sitter-grammars.tree-sitter-groovy
    tree-sitter-grammars.tree-sitter-hare
    tree-sitter-grammars.tree-sitter-haskell
    tree-sitter-grammars.tree-sitter-haskell-persistent
    tree-sitter-grammars.tree-sitter-hcl
    tree-sitter-grammars.tree-sitter-heex
    tree-sitter-grammars.tree-sitter-hjson
    tree-sitter-grammars.tree-sitter-hocon
    tree-sitter-grammars.tree-sitter-hoon
    tree-sitter-grammars.tree-sitter-hosts
    tree-sitter-grammars.tree-sitter-html
    tree-sitter-grammars.tree-sitter-htmldjango
    tree-sitter-grammars.tree-sitter-http
    tree-sitter-grammars.tree-sitter-hurl
    tree-sitter-grammars.tree-sitter-hyprlang
    tree-sitter-grammars.tree-sitter-iex
    tree-sitter-grammars.tree-sitter-ini
    tree-sitter-grammars.tree-sitter-ink
    tree-sitter-grammars.tree-sitter-inko
    tree-sitter-grammars.tree-sitter-janet-simple
    tree-sitter-grammars.tree-sitter-java
    tree-sitter-grammars.tree-sitter-javascript
    tree-sitter-grammars.tree-sitter-jinja2
    tree-sitter-grammars.tree-sitter-jjdescription
    tree-sitter-grammars.tree-sitter-jq
    tree-sitter-grammars.tree-sitter-jsdoc
    tree-sitter-grammars.tree-sitter-json
    tree-sitter-grammars.tree-sitter-json5
    tree-sitter-grammars.tree-sitter-jsonnet
    tree-sitter-grammars.tree-sitter-julia
    tree-sitter-grammars.tree-sitter-just
    tree-sitter-grammars.tree-sitter-kdl
    tree-sitter-grammars.tree-sitter-koka
    tree-sitter-grammars.tree-sitter-kotlin
    tree-sitter-grammars.tree-sitter-koto
    tree-sitter-grammars.tree-sitter-latex
    tree-sitter-grammars.tree-sitter-ld
    tree-sitter-grammars.tree-sitter-ldif
    tree-sitter-grammars.tree-sitter-lean
    tree-sitter-grammars.tree-sitter-ledger
    tree-sitter-grammars.tree-sitter-llvm
    tree-sitter-grammars.tree-sitter-llvm-mir
    tree-sitter-grammars.tree-sitter-log
    tree-sitter-grammars.tree-sitter-lpf
    tree-sitter-grammars.tree-sitter-lua
    tree-sitter-grammars.tree-sitter-luau
    tree-sitter-grammars.tree-sitter-mail
    tree-sitter-grammars.tree-sitter-make
    tree-sitter-grammars.tree-sitter-markdoc
    tree-sitter-grammars.tree-sitter-markdown
    tree-sitter-grammars.tree-sitter-markdown-inline
    tree-sitter-grammars.tree-sitter-matlab
    tree-sitter-grammars.tree-sitter-mermaid
    tree-sitter-grammars.tree-sitter-meson
    tree-sitter-grammars.tree-sitter-mojo
    tree-sitter-grammars.tree-sitter-move
    tree-sitter-grammars.tree-sitter-nasm
    tree-sitter-grammars.tree-sitter-netlinx
    tree-sitter-grammars.tree-sitter-nginx
    tree-sitter-grammars.tree-sitter-nickel
    tree-sitter-grammars.tree-sitter-nim
    tree-sitter-grammars.tree-sitter-nix
    tree-sitter-grammars.tree-sitter-norg
    tree-sitter-grammars.tree-sitter-norg-meta
    tree-sitter-grammars.tree-sitter-nu
    tree-sitter-grammars.tree-sitter-ocaml
    tree-sitter-grammars.tree-sitter-ocaml-interface
    tree-sitter-grammars.tree-sitter-odin
    tree-sitter-grammars.tree-sitter-ohm
    tree-sitter-grammars.tree-sitter-opencl
    tree-sitter-grammars.tree-sitter-openscad
    tree-sitter-grammars.tree-sitter-org
    tree-sitter-grammars.tree-sitter-org-nvim
    tree-sitter-grammars.tree-sitter-pascal
    tree-sitter-grammars.tree-sitter-passwd
    tree-sitter-grammars.tree-sitter-pem
    tree-sitter-grammars.tree-sitter-perl
    tree-sitter-grammars.tree-sitter-pest
    tree-sitter-grammars.tree-sitter-pgn
    tree-sitter-grammars.tree-sitter-php
    tree-sitter-grammars.tree-sitter-phpdoc
    tree-sitter-grammars.tree-sitter-php-only
    tree-sitter-grammars.tree-sitter-pioasm
    tree-sitter-grammars.tree-sitter-pkl
    tree-sitter-grammars.tree-sitter-po
    tree-sitter-grammars.tree-sitter-pod
    tree-sitter-grammars.tree-sitter-ponylang
    tree-sitter-grammars.tree-sitter-powershell
    tree-sitter-grammars.tree-sitter-prisma
    tree-sitter-grammars.tree-sitter-prolog
    tree-sitter-grammars.tree-sitter-properties
    tree-sitter-grammars.tree-sitter-proto
    tree-sitter-grammars.tree-sitter-prql
    tree-sitter-grammars.tree-sitter-pug
    tree-sitter-grammars.tree-sitter-purescript
    tree-sitter-grammars.tree-sitter-python
    tree-sitter-grammars.tree-sitter-ql
    tree-sitter-grammars.tree-sitter-ql-dbscheme
    tree-sitter-grammars.tree-sitter-qmljs
    tree-sitter-grammars.tree-sitter-query
    tree-sitter-grammars.tree-sitter-quint
    tree-sitter-grammars.tree-sitter-r
    tree-sitter-grammars.tree-sitter-razor
    tree-sitter-grammars.tree-sitter-readline
    tree-sitter-grammars.tree-sitter-regex
    tree-sitter-grammars.tree-sitter-rego
    tree-sitter-grammars.tree-sitter-rescript
    tree-sitter-grammars.tree-sitter-river
    tree-sitter-grammars.tree-sitter-robot
    tree-sitter-grammars.tree-sitter-ron
    tree-sitter-grammars.tree-sitter-rst
    tree-sitter-grammars.tree-sitter-ruby
    tree-sitter-grammars.tree-sitter-rust
    tree-sitter-grammars.tree-sitter-rust-format-args
    tree-sitter-grammars.tree-sitter-scala
    tree-sitter-grammars.tree-sitter-scheme
    tree-sitter-grammars.tree-sitter-scss
    tree-sitter-grammars.tree-sitter-slang
    tree-sitter-grammars.tree-sitter-slint
    tree-sitter-grammars.tree-sitter-smali
    tree-sitter-grammars.tree-sitter-smithy
    tree-sitter-grammars.tree-sitter-sml
    tree-sitter-grammars.tree-sitter-snakemake
    tree-sitter-grammars.tree-sitter-solidity
    tree-sitter-grammars.tree-sitter-sourcepawn
    tree-sitter-grammars.tree-sitter-spade
    tree-sitter-grammars.tree-sitter-sparql
    tree-sitter-grammars.tree-sitter-spicedb
    tree-sitter-grammars.tree-sitter-sql
    tree-sitter-grammars.tree-sitter-sshclientconfig
    tree-sitter-grammars.tree-sitter-strace
    tree-sitter-grammars.tree-sitter-supercollider
    tree-sitter-grammars.tree-sitter-surface
    tree-sitter-grammars.tree-sitter-svelte
    tree-sitter-grammars.tree-sitter-sway
    tree-sitter-grammars.tree-sitter-swift
    tree-sitter-grammars.tree-sitter-t32
    tree-sitter-grammars.tree-sitter-tablegen
    tree-sitter-grammars.tree-sitter-tact
    tree-sitter-grammars.tree-sitter-talon
    tree-sitter-grammars.tree-sitter-task
    tree-sitter-grammars.tree-sitter-tcl
    tree-sitter-grammars.tree-sitter-teal
    tree-sitter-grammars.tree-sitter-templ
    tree-sitter-grammars.tree-sitter-tera
    tree-sitter-grammars.tree-sitter-textproto
    tree-sitter-grammars.tree-sitter-thrift
    tree-sitter-grammars.tree-sitter-tiger
    tree-sitter-grammars.tree-sitter-tlaplus
    tree-sitter-grammars.tree-sitter-todotxt
    tree-sitter-grammars.tree-sitter-toml
    tree-sitter-grammars.tree-sitter-tsq
    tree-sitter-grammars.tree-sitter-tsx
    tree-sitter-grammars.tree-sitter-turtle
    tree-sitter-grammars.tree-sitter-twig
    tree-sitter-grammars.tree-sitter-typescript
    tree-sitter-grammars.tree-sitter-typespec
    tree-sitter-grammars.tree-sitter-typst
    tree-sitter-grammars.tree-sitter-uiua
    tree-sitter-grammars.tree-sitter-ungrammar
    tree-sitter-grammars.tree-sitter-unison
    tree-sitter-grammars.tree-sitter-uxntal
    tree-sitter-grammars.tree-sitter-v
    tree-sitter-grammars.tree-sitter-vala
    tree-sitter-grammars.tree-sitter-vento
    tree-sitter-grammars.tree-sitter-verilog
    tree-sitter-grammars.tree-sitter-vhdl
    tree-sitter-grammars.tree-sitter-vhs
    tree-sitter-grammars.tree-sitter-vim
    tree-sitter-grammars.tree-sitter-vue
    tree-sitter-grammars.tree-sitter-wast
    tree-sitter-grammars.tree-sitter-wat
    tree-sitter-grammars.tree-sitter-werk
    tree-sitter-grammars.tree-sitter-wesl
    tree-sitter-grammars.tree-sitter-wgsl
    tree-sitter-grammars.tree-sitter-wing
    tree-sitter-grammars.tree-sitter-wit
    tree-sitter-grammars.tree-sitter-wren
    tree-sitter-grammars.tree-sitter-xit
    tree-sitter-grammars.tree-sitter-xml
    tree-sitter-grammars.tree-sitter-xtc
    tree-sitter-grammars.tree-sitter-yaml
    tree-sitter-grammars.tree-sitter-yang
    tree-sitter-grammars.tree-sitter-yara
    tree-sitter-grammars.tree-sitter-yuck
    tree-sitter-grammars.tree-sitter-zig

  ];
}
